package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.Adicionales;
import pe.gob.ep.iclassq.negocio.bean.AdicionalesCriteria;
import pe.gob.ep.iclassq.negocio.dao.AdicionalesDAO;

public class AdicionalesDAOImpl extends SqlMapClientDaoSupport implements AdicionalesDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public AdicionalesDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public int countByExample(AdicionalesCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_ticket_adicionales.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public int deleteByExample(AdicionalesCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_ticket_adicionales.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Adicionales key = new Adicionales();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_ticket_adicionales.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public void insert(Adicionales record) {
		getSqlMapClientTemplate().insert("tbl_ticket_adicionales.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public void insertSelective(Adicionales record) {
		getSqlMapClientTemplate().insert("tbl_ticket_adicionales.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Adicionales> selectByExample(AdicionalesCriteria example) {
		List<Adicionales> list = getSqlMapClientTemplate()
				.queryForList("tbl_ticket_adicionales.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public Adicionales selectByPrimaryKey(Integer id) {
		Adicionales key = new Adicionales();
		key.setId(id);
		Adicionales record = (Adicionales) getSqlMapClientTemplate()
				.queryForObject("tbl_ticket_adicionales.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Adicionales record, AdicionalesCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_ticket_adicionales.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public int updateByExample(Adicionales record, AdicionalesCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_ticket_adicionales.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Adicionales record) {
		int rows = getSqlMapClientTemplate()
				.update("tbl_ticket_adicionales.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Adicionales record) {
		int rows = getSqlMapClientTemplate().update("tbl_ticket_adicionales.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_ticket_adicionales
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends AdicionalesCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, AdicionalesCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}