package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Agrupador;
import pe.gob.ep.iclassq.negocio.bean.AgrupadorCriteria;
import pe.gob.ep.iclassq.negocio.dao.AgrupadorDAO;

public class AgrupadorDAOImpl extends SqlMapClientDaoSupport implements AgrupadorDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public AgrupadorDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public int countByExample(AgrupadorCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_agrupador.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public int deleteByExample(AgrupadorCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_agrupador.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Agrupador key = new Agrupador();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_agrupador.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public void insert(Agrupador record) {
        getSqlMapClientTemplate().insert("tbl_agrupador.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public void insertSelective(Agrupador record) {
        getSqlMapClientTemplate().insert("tbl_agrupador.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Agrupador> selectByExample(AgrupadorCriteria example) {
        List<Agrupador> list = getSqlMapClientTemplate().queryForList("tbl_agrupador.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public Agrupador selectByPrimaryKey(Integer id) {
        Agrupador key = new Agrupador();
        key.setId(id);
        Agrupador record = (Agrupador) getSqlMapClientTemplate().queryForObject("tbl_agrupador.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Agrupador record, AgrupadorCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_agrupador.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public int updateByExample(Agrupador record, AgrupadorCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_agrupador.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Agrupador record) {
        int rows = getSqlMapClientTemplate().update("tbl_agrupador.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Agrupador record) {
        int rows = getSqlMapClientTemplate().update("tbl_agrupador.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_agrupador
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends AgrupadorCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, AgrupadorCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}