package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Algoritmo;
import pe.gob.ep.iclassq.negocio.bean.AlgoritmoCriteria;
import pe.gob.ep.iclassq.negocio.dao.AlgoritmoDAO;

public class AlgoritmoDAOImpl extends SqlMapClientDaoSupport implements AlgoritmoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public AlgoritmoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public int countByExample(AlgoritmoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_algoritmo.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public int deleteByExample(AlgoritmoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_algoritmo.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Algoritmo key = new Algoritmo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_algoritmo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public void insert(Algoritmo record) {
        getSqlMapClientTemplate().insert("tbl_algoritmo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public void insertSelective(Algoritmo record) {
        getSqlMapClientTemplate().insert("tbl_algoritmo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Algoritmo> selectByExample(AlgoritmoCriteria example) {
        List<Algoritmo> list = getSqlMapClientTemplate().queryForList("tbl_algoritmo.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public Algoritmo selectByPrimaryKey(Integer id) {
        Algoritmo key = new Algoritmo();
        key.setId(id);
        Algoritmo record = (Algoritmo) getSqlMapClientTemplate().queryForObject("tbl_algoritmo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Algoritmo record, AlgoritmoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_algoritmo.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public int updateByExample(Algoritmo record, AlgoritmoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_algoritmo.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Algoritmo record) {
        int rows = getSqlMapClientTemplate().update("tbl_algoritmo.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Algoritmo record) {
        int rows = getSqlMapClientTemplate().update("tbl_algoritmo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_algoritmo
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends AlgoritmoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, AlgoritmoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}