package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.AlgoritmoXGrupo;
import pe.gob.ep.iclassq.negocio.bean.AlgoritmoXGrupoCriteria;
import pe.gob.ep.iclassq.negocio.dao.AlgoritmoXGrupoDAO;

public class AlgoritmoXGrupoDAOImpl extends SqlMapClientDaoSupport implements AlgoritmoXGrupoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public AlgoritmoXGrupoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public int countByExample(AlgoritmoXGrupoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_algoritmoxgrupo.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public int deleteByExample(AlgoritmoXGrupoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_algoritmoxgrupo.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        AlgoritmoXGrupo key = new AlgoritmoXGrupo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_algoritmoxgrupo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public void insert(AlgoritmoXGrupo record) {
        getSqlMapClientTemplate().insert("tbl_algoritmoxgrupo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public void insertSelective(AlgoritmoXGrupo record) {
        getSqlMapClientTemplate().insert("tbl_algoritmoxgrupo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<AlgoritmoXGrupo> selectByExample(AlgoritmoXGrupoCriteria example) {
        List<AlgoritmoXGrupo> list = getSqlMapClientTemplate().queryForList("tbl_algoritmoxgrupo.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public AlgoritmoXGrupo selectByPrimaryKey(Integer id) {
        AlgoritmoXGrupo key = new AlgoritmoXGrupo();
        key.setId(id);
        AlgoritmoXGrupo record = (AlgoritmoXGrupo) getSqlMapClientTemplate().queryForObject("tbl_algoritmoxgrupo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(AlgoritmoXGrupo record, AlgoritmoXGrupoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_algoritmoxgrupo.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public int updateByExample(AlgoritmoXGrupo record, AlgoritmoXGrupoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_algoritmoxgrupo.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(AlgoritmoXGrupo record) {
        int rows = getSqlMapClientTemplate().update("tbl_algoritmoxgrupo.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(AlgoritmoXGrupo record) {
        int rows = getSqlMapClientTemplate().update("tbl_algoritmoxgrupo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends AlgoritmoXGrupoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, AlgoritmoXGrupoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}