package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanId;
import pe.gob.ep.iclassq.entidad.BeanTicketXArea;
import pe.gob.ep.iclassq.negocio.bean.Area;
import pe.gob.ep.iclassq.negocio.bean.AreaCriteria;
import pe.gob.ep.iclassq.negocio.dao.AreaDAO;

public class AreaDAOImpl extends SqlMapClientDaoSupport implements AreaDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public AreaDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public int countByExample(AreaCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tbl_area.ibatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public int deleteByExample(AreaCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_area.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Area key = new Area();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_area.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public void insert(Area record) {
		getSqlMapClientTemplate().insert("tbl_area.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public void insertSelective(Area record) {
		getSqlMapClientTemplate().insert("tbl_area.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Area> selectByExample(AreaCriteria example) {
		List<Area> list = getSqlMapClientTemplate().queryForList("tbl_area.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public Area selectByPrimaryKey(Integer id) {
		Area key = new Area();
		key.setId(id);
		Area record = (Area) getSqlMapClientTemplate().queryForObject("tbl_area.ibatorgenerated_selectByPrimaryKey",
				key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Area record, AreaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_area.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public int updateByExample(Area record, AreaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_area.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Area record) {
		int rows = getSqlMapClientTemplate().update("tbl_area.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Area record) {
		int rows = getSqlMapClientTemplate().update("tbl_area.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends AreaCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, AreaCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
 	public List<BeanId> listarAreaGrupoID(Map<String, Object> params) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_area.listarAreaGrupoID", params);
 	}    
    
    

}