package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanReporteAsistencia;
import pe.gob.ep.iclassq.entidad.BeanTicketXArea;
import pe.gob.ep.iclassq.negocio.bean.Asistencia;
import pe.gob.ep.iclassq.negocio.bean.AsistenciaCriteria;
import pe.gob.ep.iclassq.negocio.dao.AsistenciaDAO;
import pe.gob.ep.iclassq.negocio.bean.Asistencia;
import pe.gob.ep.iclassq.negocio.bean.AsistenciaCriteria;
import pe.gob.ep.iclassq.negocio.dao.AsistenciaDAO;

public class AsistenciaDAOImpl extends SqlMapClientDaoSupport implements AsistenciaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public AsistenciaDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public int countByExample(AsistenciaCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_asistencia.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public int deleteByExample(AsistenciaCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_asistencia.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Asistencia key = new Asistencia();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_asistencia.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public void insert(Asistencia record) {
		getSqlMapClientTemplate().insert("tbl_asistencia.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public void insertSelective(Asistencia record) {
		getSqlMapClientTemplate().insert("tbl_asistencia.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Asistencia> selectByExample(AsistenciaCriteria example) {
		List<Asistencia> list = getSqlMapClientTemplate().queryForList("tbl_asistencia.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public Asistencia selectByPrimaryKey(Integer id) {
		Asistencia key = new Asistencia();
		key.setId(id);
		Asistencia record = (Asistencia) getSqlMapClientTemplate()
				.queryForObject("tbl_asistencia.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Asistencia record, AsistenciaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_asistencia.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public int updateByExample(Asistencia record, AsistenciaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_asistencia.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Asistencia record) {
		int rows = getSqlMapClientTemplate().update("tbl_asistencia.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Asistencia record) {
		int rows = getSqlMapClientTemplate().update("tbl_asistencia.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends AsistenciaCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, AsistenciaCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
 	public List<BeanReporteAsistencia> listarReporteAsistencia(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
		List<BeanReporteAsistencia> list = getSqlMapClientTemplate().queryForList("tbl_asistencia.listDataAttendance", paramet);
      return list;
 	}
	
	@Override
 	public List<BeanReporteAsistencia> listarDetalleReporte(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
		List<BeanReporteAsistencia> list = getSqlMapClientTemplate().queryForList("tbl_asistencia.listarDetalleReporte", paramet);
      return list;
 	}
}