package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.Audio;
import pe.gob.ep.iclassq.negocio.bean.AudioCriteria;
import pe.gob.ep.iclassq.negocio.dao.AudioDAO;

public class AudioDAOImpl extends SqlMapClientDaoSupport implements AudioDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public AudioDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public int countByExample(AudioCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_audio.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public int deleteByExample(AudioCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_audio.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Audio key = new Audio();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_audio.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public void insert(Audio record) {
        getSqlMapClientTemplate().insert("tbl_audio.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public void insertSelective(Audio record) {
        getSqlMapClientTemplate().insert("tbl_audio.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Audio> selectByExample(AudioCriteria example) {
        List<Audio> list = getSqlMapClientTemplate().queryForList("tbl_audio.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public Audio selectByPrimaryKey(Integer id) {
        Audio key = new Audio();
        key.setId(id);
        Audio record = (Audio) getSqlMapClientTemplate().queryForObject("tbl_audio.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Audio record, AudioCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_audio.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public int updateByExample(Audio record, AudioCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_audio.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Audio record) {
        int rows = getSqlMapClientTemplate().update("tbl_audio.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Audio record) {
        int rows = getSqlMapClientTemplate().update("tbl_audio.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_audio
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends AudioCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, AudioCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}