package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanDni;
import pe.gob.ep.iclassq.negocio.bean.Dni;
import pe.gob.ep.iclassq.negocio.bean.DniCriteria;
import pe.gob.ep.iclassq.negocio.bean.TablaGeneral;
import pe.gob.ep.iclassq.negocio.dao.DniDAO;

public class DniDAOImpl extends SqlMapClientDaoSupport implements DniDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public DniDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public int countByExample(DniCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tbl_dni.ibatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public int deleteByExample(DniCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_dni.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Dni key = new Dni();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_dni.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public void insert(Dni record) {
		getSqlMapClientTemplate().insert("tbl_dni.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public void insertSelective(Dni record) {
		getSqlMapClientTemplate().insert("tbl_dni.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Dni> selectByExample(DniCriteria example) {
		List<Dni> list = getSqlMapClientTemplate().queryForList("tbl_dni.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public Dni selectByPrimaryKey(Integer id) {
		Dni key = new Dni();
		key.setId(id);
		Dni record = (Dni) getSqlMapClientTemplate().queryForObject("tbl_dni.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Dni record, DniCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_dni.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public int updateByExample(Dni record, DniCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_dni.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Dni record) {
		int rows = getSqlMapClientTemplate().update("tbl_dni.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Dni record) {
		int rows = getSqlMapClientTemplate().update("tbl_dni.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends DniCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, DniCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<BeanDni> listarPersonaXDni(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanDni> list = getSqlMapClientTemplate().queryForList("tbl_dni.listarPersonaXDni", params);
      return list;
	}
    
}