package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Empresa;
import pe.gob.ep.iclassq.negocio.bean.EmpresaCriteria;
import pe.gob.ep.iclassq.negocio.dao.EmpresaDAO;

public class EmpresaDAOImpl extends SqlMapClientDaoSupport implements EmpresaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public EmpresaDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public int countByExample(EmpresaCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tbl_empresa.ibatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public int deleteByExample(EmpresaCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_empresa.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Empresa key = new Empresa();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_empresa.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public void insert(Empresa record) {
		getSqlMapClientTemplate().insert("tbl_empresa.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public void insertSelective(Empresa record) {
		getSqlMapClientTemplate().insert("tbl_empresa.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Empresa> selectByExample(EmpresaCriteria example) {
		List<Empresa> list = getSqlMapClientTemplate().queryForList("tbl_empresa.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public Empresa selectByPrimaryKey(Integer id) {
		Empresa key = new Empresa();
		key.setId(id);
		Empresa record = (Empresa) getSqlMapClientTemplate()
				.queryForObject("tbl_empresa.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Empresa record, EmpresaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_empresa.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public int updateByExample(Empresa record, EmpresaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_empresa.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Empresa record) {
		int rows = getSqlMapClientTemplate().update("tbl_empresa.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Empresa record) {
		int rows = getSqlMapClientTemplate().update("tbl_empresa.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_empresa
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends EmpresaCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, EmpresaCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}