package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanEncuesta;
import pe.gob.ep.iclassq.entidad.BeanEncuestaPreguntas;
import pe.gob.ep.iclassq.negocio.bean.EncuestaPreguntas;
import pe.gob.ep.iclassq.negocio.bean.EncuestaPreguntasCriteria;
import pe.gob.ep.iclassq.negocio.dao.EncuestaPreguntasDAO;

public class EncuestaPreguntasDAOImpl extends SqlMapClientDaoSupport implements EncuestaPreguntasDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public EncuestaPreguntasDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public int countByExample(EncuestaPreguntasCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_encuesta_preguntas.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public int deleteByExample(EncuestaPreguntasCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_encuesta_preguntas.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		EncuestaPreguntas key = new EncuestaPreguntas();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_encuesta_preguntas.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public void insert(EncuestaPreguntas record) {
		getSqlMapClientTemplate().insert("tbl_encuesta_preguntas.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public void insertSelective(EncuestaPreguntas record) {
		getSqlMapClientTemplate().insert("tbl_encuesta_preguntas.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<EncuestaPreguntas> selectByExample(EncuestaPreguntasCriteria example) {
		List<EncuestaPreguntas> list = getSqlMapClientTemplate()
				.queryForList("tbl_encuesta_preguntas.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public EncuestaPreguntas selectByPrimaryKey(Integer id) {
		EncuestaPreguntas key = new EncuestaPreguntas();
		key.setId(id);
		EncuestaPreguntas record = (EncuestaPreguntas) getSqlMapClientTemplate()
				.queryForObject("tbl_encuesta_preguntas.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(EncuestaPreguntas record, EncuestaPreguntasCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_encuesta_preguntas.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public int updateByExample(EncuestaPreguntas record, EncuestaPreguntasCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_encuesta_preguntas.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(EncuestaPreguntas record) {
		int rows = getSqlMapClientTemplate()
				.update("tbl_encuesta_preguntas.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(EncuestaPreguntas record) {
		int rows = getSqlMapClientTemplate().update("tbl_encuesta_preguntas.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends EncuestaPreguntasCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, EncuestaPreguntasCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
	
	@Override
 	public List<BeanEncuestaPreguntas> getActiveQuestionsBySurvey(Map<String, Object> paramet) { 
 		// TODO Auto-generated method stub
		List<BeanEncuestaPreguntas> list = getSqlMapClientTemplate().queryForList("tbl_encuesta_preguntas.getActiveQuestionsBySurvey", paramet);
      return list;
 	}
}