package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanReporteEncuesta;
import pe.gob.ep.iclassq.negocio.bean.EncuestaRespuesta;
import pe.gob.ep.iclassq.negocio.bean.EncuestaRespuestaCriteria;
import pe.gob.ep.iclassq.negocio.dao.EncuestaRespuestaDAO;

public class EncuestaRespuestaDAOImpl extends SqlMapClientDaoSupport implements EncuestaRespuestaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	public EncuestaRespuestaDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	public int countByExample(EncuestaRespuestaCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_encuesta_respuesta.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	public int deleteByExample(EncuestaRespuestaCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_encuesta_respuesta.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	public void insert(EncuestaRespuesta record) {
		getSqlMapClientTemplate().insert("tbl_encuesta_respuesta.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	public void insertSelective(EncuestaRespuesta record) {
		getSqlMapClientTemplate().insert("tbl_encuesta_respuesta.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<EncuestaRespuesta> selectByExample(EncuestaRespuestaCriteria example) {
		List<EncuestaRespuesta> list = getSqlMapClientTemplate()
				.queryForList("tbl_encuesta_respuesta.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(EncuestaRespuesta record, EncuestaRespuestaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_encuesta_respuesta.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	public int updateByExample(EncuestaRespuesta record, EncuestaRespuestaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_encuesta_respuesta.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends EncuestaRespuestaCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, EncuestaRespuestaCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
	
	@Override
 	public List<BeanReporteEncuesta> listarReporteEncuesta(Map<String, Object> paramet) { 
 		// TODO Auto-generated method stub
		List<BeanReporteEncuesta> list = getSqlMapClientTemplate().queryForList("tbl_encuesta_respuesta.listarReporteEncuesta", paramet);
      return list;
 	}
}