package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanEncuesta;
import pe.gob.ep.iclassq.negocio.bean.Encuesta;
import pe.gob.ep.iclassq.negocio.bean.EncuestaCriteria;
import pe.gob.ep.iclassq.negocio.dao.EncuestaDAO;

public class EncuestaDAOImpl extends SqlMapClientDaoSupport implements EncuestaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public EncuestaDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public int countByExample(EncuestaCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_encuesta.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public int deleteByExample(EncuestaCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_encuesta.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Encuesta key = new Encuesta();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_encuesta.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public void insert(Encuesta record) {
		getSqlMapClientTemplate().insert("tbl_encuesta.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public void insertSelective(Encuesta record) {
		getSqlMapClientTemplate().insert("tbl_encuesta.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Encuesta> selectByExample(EncuestaCriteria example) {
		List<Encuesta> list = getSqlMapClientTemplate().queryForList("tbl_encuesta.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public Encuesta selectByPrimaryKey(Integer id) {
		Encuesta key = new Encuesta();
		key.setId(id);
		Encuesta record = (Encuesta) getSqlMapClientTemplate()
				.queryForObject("tbl_encuesta.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Encuesta record, EncuestaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_encuesta.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public int updateByExample(Encuesta record, EncuestaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_encuesta.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Encuesta record) {
		int rows = getSqlMapClientTemplate().update("tbl_encuesta.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Encuesta record) {
		int rows = getSqlMapClientTemplate().update("tbl_encuesta.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends EncuestaCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, EncuestaCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
	
	@Override
 	public List<BeanEncuesta> getEncuestasByRangeDate(Map<String, Object> paramet) { 
 		// TODO Auto-generated method stub
		List<BeanEncuesta> list = getSqlMapClientTemplate().queryForList("tbl_encuesta.getEncuestasByRangeDate", paramet);
      return list;
 	}
}