package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.EncuestaOpciones;
import pe.gob.ep.iclassq.negocio.bean.EncuestaOpcionesCriteria;
import pe.gob.ep.iclassq.negocio.dao.EncuestaOpcionesDAO;

public class EncuestaOpcionesDAOImpl extends SqlMapClientDaoSupport implements EncuestaOpcionesDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public EncuestaOpcionesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public int countByExample(EncuestaOpcionesCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_encuesta_opciones.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public int deleteByExample(EncuestaOpcionesCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_encuesta_opciones.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        EncuestaOpciones key = new EncuestaOpciones();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_encuesta_opciones.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public void insert(EncuestaOpciones record) {
        getSqlMapClientTemplate().insert("tbl_encuesta_opciones.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public void insertSelective(EncuestaOpciones record) {
        getSqlMapClientTemplate().insert("tbl_encuesta_opciones.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<EncuestaOpciones> selectByExample(EncuestaOpcionesCriteria example) {
        List<EncuestaOpciones> list = getSqlMapClientTemplate().queryForList("tbl_encuesta_opciones.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public EncuestaOpciones selectByPrimaryKey(Integer id) {
        EncuestaOpciones key = new EncuestaOpciones();
        key.setId(id);
        EncuestaOpciones record = (EncuestaOpciones) getSqlMapClientTemplate().queryForObject("tbl_encuesta_opciones.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(EncuestaOpciones record, EncuestaOpcionesCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_encuesta_opciones.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public int updateByExample(EncuestaOpciones record, EncuestaOpcionesCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_encuesta_opciones.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(EncuestaOpciones record) {
        int rows = getSqlMapClientTemplate().update("tbl_encuesta_opciones.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(EncuestaOpciones record) {
        int rows = getSqlMapClientTemplate().update("tbl_encuesta_opciones.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends EncuestaOpcionesCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, EncuestaOpcionesCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}