package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.Evaluador;
import pe.gob.ep.iclassq.negocio.bean.EvaluadorCriteria;
import pe.gob.ep.iclassq.negocio.dao.EvaluadorDAO;

public class EvaluadorDAOImpl extends SqlMapClientDaoSupport implements EvaluadorDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public EvaluadorDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public int countByExample(EvaluadorCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_evaluador.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public int deleteByExample(EvaluadorCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_evaluador.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Evaluador key = new Evaluador();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_evaluador.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public void insert(Evaluador record) {
        getSqlMapClientTemplate().insert("tbl_evaluador.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public void insertSelective(Evaluador record) {
        getSqlMapClientTemplate().insert("tbl_evaluador.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Evaluador> selectByExample(EvaluadorCriteria example) {
        List<Evaluador> list = getSqlMapClientTemplate().queryForList("tbl_evaluador.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public Evaluador selectByPrimaryKey(Integer id) {
        Evaluador key = new Evaluador();
        key.setId(id);
        Evaluador record = (Evaluador) getSqlMapClientTemplate().queryForObject("tbl_evaluador.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Evaluador record, EvaluadorCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_evaluador.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public int updateByExample(Evaluador record, EvaluadorCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_evaluador.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Evaluador record) {
        int rows = getSqlMapClientTemplate().update("tbl_evaluador.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Evaluador record) {
        int rows = getSqlMapClientTemplate().update("tbl_evaluador.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends EvaluadorCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, EvaluadorCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}