package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.GrupoXSede;
import pe.gob.ep.iclassq.negocio.bean.GrupoXSedeCriteria;
import pe.gob.ep.iclassq.negocio.dao.GrupoXSedeDAO;

public class GrupoXSedeDAOImpl extends SqlMapClientDaoSupport implements GrupoXSedeDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public GrupoXSedeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public int countByExample(GrupoXSedeCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_grupoxsede.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public int deleteByExample(GrupoXSedeCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_grupoxsede.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        GrupoXSede key = new GrupoXSede();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_grupoxsede.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public void insert(GrupoXSede record) {
        getSqlMapClientTemplate().insert("tbl_grupoxsede.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public void insertSelective(GrupoXSede record) {
        getSqlMapClientTemplate().insert("tbl_grupoxsede.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<GrupoXSede> selectByExample(GrupoXSedeCriteria example) {
        List<GrupoXSede> list = getSqlMapClientTemplate().queryForList("tbl_grupoxsede.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public GrupoXSede selectByPrimaryKey(Integer id) {
        GrupoXSede key = new GrupoXSede();
        key.setId(id);
        GrupoXSede record = (GrupoXSede) getSqlMapClientTemplate().queryForObject("tbl_grupoxsede.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(GrupoXSede record, GrupoXSedeCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_grupoxsede.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public int updateByExample(GrupoXSede record, GrupoXSedeCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_grupoxsede.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(GrupoXSede record) {
        int rows = getSqlMapClientTemplate().update("tbl_grupoxsede.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(GrupoXSede record) {
        int rows = getSqlMapClientTemplate().update("tbl_grupoxsede.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends GrupoXSedeCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, GrupoXSedeCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}