package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.GrupoXKiosko;
import pe.gob.ep.iclassq.negocio.bean.GrupoXKioskoCriteria;
import pe.gob.ep.iclassq.negocio.dao.GrupoXKioskoDAO;

public class GrupoXKioskoDAOImpl extends SqlMapClientDaoSupport implements GrupoXKioskoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public GrupoXKioskoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public int countByExample(GrupoXKioskoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_grupoxkiosko.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public int deleteByExample(GrupoXKioskoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_grupoxkiosko.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        GrupoXKiosko key = new GrupoXKiosko();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_grupoxkiosko.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public void insert(GrupoXKiosko record) {
        getSqlMapClientTemplate().insert("tbl_grupoxkiosko.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public void insertSelective(GrupoXKiosko record) {
        getSqlMapClientTemplate().insert("tbl_grupoxkiosko.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<GrupoXKiosko> selectByExample(GrupoXKioskoCriteria example) {
        List<GrupoXKiosko> list = getSqlMapClientTemplate().queryForList("tbl_grupoxkiosko.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public GrupoXKiosko selectByPrimaryKey(Integer id) {
        GrupoXKiosko key = new GrupoXKiosko();
        key.setId(id);
        GrupoXKiosko record = (GrupoXKiosko) getSqlMapClientTemplate().queryForObject("tbl_grupoxkiosko.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(GrupoXKiosko record, GrupoXKioskoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_grupoxkiosko.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public int updateByExample(GrupoXKiosko record, GrupoXKioskoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_grupoxkiosko.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(GrupoXKiosko record) {
        int rows = getSqlMapClientTemplate().update("tbl_grupoxkiosko.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(GrupoXKiosko record) {
        int rows = getSqlMapClientTemplate().update("tbl_grupoxkiosko.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_grupoxkiosko
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends GrupoXKioskoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, GrupoXKioskoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}