package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanGrupo;
import pe.gob.ep.iclassq.negocio.bean.Grupo;
import pe.gob.ep.iclassq.negocio.bean.GrupoCriteria;
import pe.gob.ep.iclassq.negocio.dao.GrupoDAO;

public class GrupoDAOImpl extends SqlMapClientDaoSupport implements GrupoDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public GrupoDAOImpl() {
		super();
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public int countByExample(GrupoCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tbl_grupo.ibatorgenerated_countByExample",
				example);
		return count;
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public int deleteByExample(GrupoCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_grupo.ibatorgenerated_deleteByExample", example);
		return rows;
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Grupo key = new Grupo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_grupo.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public void insert(Grupo record) {
		getSqlMapClientTemplate().insert("tbl_grupo.ibatorgenerated_insert", record);
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public void insertSelective(Grupo record) {
		getSqlMapClientTemplate().insert("tbl_grupo.ibatorgenerated_insertSelective", record);
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Grupo> selectByExample(GrupoCriteria example) {
		List<Grupo> list = getSqlMapClientTemplate().queryForList("tbl_grupo.ibatorgenerated_selectByExample", example);
		return list;
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public Grupo selectByPrimaryKey(Integer id) {
		Grupo key = new Grupo();
		key.setId(id);
		Grupo record = (Grupo) getSqlMapClientTemplate().queryForObject("tbl_grupo.ibatorgenerated_selectByPrimaryKey",
				key);
		return record;
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Grupo record, GrupoCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_grupo.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public int updateByExample(Grupo record, GrupoCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_grupo.ibatorgenerated_updateByExample", parms);
		return rows;
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Grupo record) {
		int rows = getSqlMapClientTemplate().update("tbl_grupo.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Grupo record) {
		int rows = getSqlMapClientTemplate().update("tbl_grupo.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_grupo
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends GrupoCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, GrupoCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<BeanGrupo> listarGruposBySucursal(Map<String, Object> parametro) {
	// TODO Auto-generated method stub
		
		return getSqlMapClientTemplate().queryForList("tbl_grupo.listarGruposBySucursal", parametro);
	}
    @Override
	public List<BeanGrupo> listargruposxparametroTipoDeriva(Map<String, Object> parametro) {
	// TODO Auto-generated method stub
		
		return getSqlMapClientTemplate().queryForList("tbl_grupo.listargruposxparametroTipoDeriva", parametro);
	}
   
    @Override
	public List<Grupo> listarGruposxventanilla(Map<String, Object> parametro) {
	// TODO Auto-generated method stub
		
		return getSqlMapClientTemplate().queryForList("tbl_grupo.listarGruposxventanilla", parametro);
	}

}