package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Maestra;
import pe.gob.ep.iclassq.negocio.bean.MaestraCriteria;
import pe.gob.ep.iclassq.negocio.dao.MaestraDAO;

public class MaestraDAOImpl extends SqlMapClientDaoSupport implements MaestraDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public MaestraDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public int countByExample(MaestraCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_maestra.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public int deleteByExample(MaestraCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_maestra.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Maestra key = new Maestra();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_maestra.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public void insert(Maestra record) {
        getSqlMapClientTemplate().insert("tbl_maestra.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public void insertSelective(Maestra record) {
        getSqlMapClientTemplate().insert("tbl_maestra.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Maestra> selectByExample(MaestraCriteria example) {
        List<Maestra> list = getSqlMapClientTemplate().queryForList("tbl_maestra.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public Maestra selectByPrimaryKey(Integer id) {
        Maestra key = new Maestra();
        key.setId(id);
        Maestra record = (Maestra) getSqlMapClientTemplate().queryForObject("tbl_maestra.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Maestra record, MaestraCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_maestra.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public int updateByExample(Maestra record, MaestraCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_maestra.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Maestra record) {
        int rows = getSqlMapClientTemplate().update("tbl_maestra.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Maestra record) {
        int rows = getSqlMapClientTemplate().update("tbl_maestra.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends MaestraCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, MaestraCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}