package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Monitor;
import pe.gob.ep.iclassq.negocio.bean.MonitorCriteria;
import pe.gob.ep.iclassq.negocio.dao.MonitorDAO;

public class MonitorDAOImpl extends SqlMapClientDaoSupport implements MonitorDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public MonitorDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public int countByExample(MonitorCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_monitor.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public int deleteByExample(MonitorCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_monitor.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Monitor key = new Monitor();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_monitor.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public void insert(Monitor record) {
        getSqlMapClientTemplate().insert("tbl_monitor.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public void insertSelective(Monitor record) {
        getSqlMapClientTemplate().insert("tbl_monitor.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Monitor> selectByExample(MonitorCriteria example) {
        List<Monitor> list = getSqlMapClientTemplate().queryForList("tbl_monitor.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public Monitor selectByPrimaryKey(Integer id) {
        Monitor key = new Monitor();
        key.setId(id);
        Monitor record = (Monitor) getSqlMapClientTemplate().queryForObject("tbl_monitor.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Monitor record, MonitorCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_monitor.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public int updateByExample(Monitor record, MonitorCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_monitor.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Monitor record) {
        int rows = getSqlMapClientTemplate().update("tbl_monitor.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Monitor record) {
        int rows = getSqlMapClientTemplate().update("tbl_monitor.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends MonitorCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, MonitorCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}