package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.MonitorCajas;
import pe.gob.ep.iclassq.negocio.bean.MonitorCajasCriteria;
import pe.gob.ep.iclassq.negocio.dao.MonitorCajasDAO;

public class MonitorCajasDAOImpl extends SqlMapClientDaoSupport implements MonitorCajasDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public MonitorCajasDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public int countByExample(MonitorCajasCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_monitor_cajas.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public int deleteByExample(MonitorCajasCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_monitor_cajas.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		MonitorCajas key = new MonitorCajas();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_monitor_cajas.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public void insert(MonitorCajas record) {
		getSqlMapClientTemplate().insert("tbl_monitor_cajas.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public void insertSelective(MonitorCajas record) {
		getSqlMapClientTemplate().insert("tbl_monitor_cajas.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<MonitorCajas> selectByExample(MonitorCajasCriteria example) {
		List<MonitorCajas> list = getSqlMapClientTemplate()
				.queryForList("tbl_monitor_cajas.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public MonitorCajas selectByPrimaryKey(Integer id) {
		MonitorCajas key = new MonitorCajas();
		key.setId(id);
		MonitorCajas record = (MonitorCajas) getSqlMapClientTemplate()
				.queryForObject("tbl_monitor_cajas.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(MonitorCajas record, MonitorCajasCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_monitor_cajas.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public int updateByExample(MonitorCajas record, MonitorCajasCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_monitor_cajas.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(MonitorCajas record) {
		int rows = getSqlMapClientTemplate().update("tbl_monitor_cajas.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(MonitorCajas record) {
		int rows = getSqlMapClientTemplate().update("tbl_monitor_cajas.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends MonitorCajasCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, MonitorCajasCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}