package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.MotivoAusencia;
import pe.gob.ep.iclassq.negocio.bean.MotivoAusenciaCriteria;
import pe.gob.ep.iclassq.negocio.dao.MotivoAusenciaDAO;

public class MotivoAusenciaDAOImpl extends SqlMapClientDaoSupport implements MotivoAusenciaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public MotivoAusenciaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public int countByExample(MotivoAusenciaCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cat_motivo_ausencia.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public int deleteByExample(MotivoAusenciaCriteria example) {
        int rows = getSqlMapClientTemplate().delete("cat_motivo_ausencia.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        MotivoAusencia key = new MotivoAusencia();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("cat_motivo_ausencia.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public void insert(MotivoAusencia record) {
        getSqlMapClientTemplate().insert("cat_motivo_ausencia.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public void insertSelective(MotivoAusencia record) {
        getSqlMapClientTemplate().insert("cat_motivo_ausencia.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<MotivoAusencia> selectByExample(MotivoAusenciaCriteria example) {
        List<MotivoAusencia> list = getSqlMapClientTemplate().queryForList("cat_motivo_ausencia.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public MotivoAusencia selectByPrimaryKey(Integer id) {
        MotivoAusencia key = new MotivoAusencia();
        key.setId(id);
        MotivoAusencia record = (MotivoAusencia) getSqlMapClientTemplate().queryForObject("cat_motivo_ausencia.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(MotivoAusencia record, MotivoAusenciaCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cat_motivo_ausencia.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public int updateByExample(MotivoAusencia record, MotivoAusenciaCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cat_motivo_ausencia.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(MotivoAusencia record) {
        int rows = getSqlMapClientTemplate().update("cat_motivo_ausencia.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(MotivoAusencia record) {
        int rows = getSqlMapClientTemplate().update("cat_motivo_ausencia.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table cat_motivo_ausencia
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends MotivoAusenciaCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, MotivoAusenciaCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}