package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.Parametro;
import pe.gob.ep.iclassq.negocio.bean.ParametroCriteria;
import pe.gob.ep.iclassq.negocio.dao.ParametroDAO;

public class ParametroDAOImpl extends SqlMapClientDaoSupport implements ParametroDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public ParametroDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int countByExample(ParametroCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_parametro.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int deleteByExample(ParametroCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_parametro.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(String codigo) {
		Parametro key = new Parametro();
		key.setCodigo(codigo);
		int rows = getSqlMapClientTemplate().delete("tbl_parametro.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public void insert(Parametro record) {
		getSqlMapClientTemplate().insert("tbl_parametro.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public void insertSelective(Parametro record) {
		getSqlMapClientTemplate().insert("tbl_parametro.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Parametro> selectByExampleWithBLOBs(ParametroCriteria example) {
		List<Parametro> list = getSqlMapClientTemplate()
				.queryForList("tbl_parametro.ibatorgenerated_selectByExampleWithBLOBs", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Parametro> selectByExampleWithoutBLOBs(ParametroCriteria example) {
		List<Parametro> list = getSqlMapClientTemplate().queryForList("tbl_parametro.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public Parametro selectByPrimaryKey(String codigo) {
		Parametro key = new Parametro();
		key.setCodigo(codigo);
		Parametro record = (Parametro) getSqlMapClientTemplate()
				.queryForObject("tbl_parametro.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Parametro record, ParametroCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_parametro.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int updateByExampleWithBLOBs(Parametro record, ParametroCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_parametro.ibatorgenerated_updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int updateByExampleWithoutBLOBs(Parametro record, ParametroCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_parametro.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Parametro record) {
		int rows = getSqlMapClientTemplate().update("tbl_parametro.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeyWithBLOBs(Parametro record) {
		int rows = getSqlMapClientTemplate().update("tbl_parametro.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeyWithoutBLOBs(Parametro record) {
		int rows = getSqlMapClientTemplate().update("tbl_parametro.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends ParametroCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, ParametroCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}