package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Prioridad;
import pe.gob.ep.iclassq.negocio.bean.PrioridadCriteria;
import pe.gob.ep.iclassq.negocio.dao.PrioridadDAO;

public class PrioridadDAOImpl extends SqlMapClientDaoSupport implements PrioridadDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public PrioridadDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public int countByExample(PrioridadCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_prioridad.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public int deleteByExample(PrioridadCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_prioridad.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Prioridad key = new Prioridad();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_prioridad.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public void insert(Prioridad record) {
        getSqlMapClientTemplate().insert("tbl_prioridad.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public void insertSelective(Prioridad record) {
        getSqlMapClientTemplate().insert("tbl_prioridad.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Prioridad> selectByExample(PrioridadCriteria example) {
        List<Prioridad> list = getSqlMapClientTemplate().queryForList("tbl_prioridad.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public Prioridad selectByPrimaryKey(Integer id) {
        Prioridad key = new Prioridad();
        key.setId(id);
        Prioridad record = (Prioridad) getSqlMapClientTemplate().queryForObject("tbl_prioridad.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Prioridad record, PrioridadCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_prioridad.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public int updateByExample(Prioridad record, PrioridadCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_prioridad.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Prioridad record) {
        int rows = getSqlMapClientTemplate().update("tbl_prioridad.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Prioridad record) {
        int rows = getSqlMapClientTemplate().update("tbl_prioridad.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends PrioridadCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, PrioridadCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}