package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Proyecto;
import pe.gob.ep.iclassq.negocio.bean.ProyectoCriteria;
import pe.gob.ep.iclassq.negocio.dao.ProyectoDAO;

public class ProyectoDAOImpl extends SqlMapClientDaoSupport implements ProyectoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public ProyectoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public int countByExample(ProyectoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_proyecto.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public int deleteByExample(ProyectoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_proyecto.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer idProyecto) {
        Proyecto key = new Proyecto();
        key.setIdProyecto(idProyecto);
        int rows = getSqlMapClientTemplate().delete("tbl_proyecto.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public void insert(Proyecto record) {
        getSqlMapClientTemplate().insert("tbl_proyecto.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public void insertSelective(Proyecto record) {
        getSqlMapClientTemplate().insert("tbl_proyecto.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Proyecto> selectByExample(ProyectoCriteria example) {
        List<Proyecto> list = getSqlMapClientTemplate().queryForList("tbl_proyecto.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public Proyecto selectByPrimaryKey(Integer idProyecto) {
        Proyecto key = new Proyecto();
        key.setIdProyecto(idProyecto);
        Proyecto record = (Proyecto) getSqlMapClientTemplate().queryForObject("tbl_proyecto.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Proyecto record, ProyectoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_proyecto.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public int updateByExample(Proyecto record, ProyectoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_proyecto.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Proyecto record) {
        int rows = getSqlMapClientTemplate().update("tbl_proyecto.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Proyecto record) {
        int rows = getSqlMapClientTemplate().update("tbl_proyecto.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends ProyectoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, ProyectoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}