package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Publicidad;
import pe.gob.ep.iclassq.negocio.bean.PublicidadCriteria;
import pe.gob.ep.iclassq.negocio.dao.PublicidadDAO;

public class PublicidadDAOImpl extends SqlMapClientDaoSupport implements PublicidadDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public PublicidadDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public int countByExample(PublicidadCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_publicidad.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public int deleteByExample(PublicidadCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_publicidad.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Publicidad key = new Publicidad();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_publicidad.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public void insert(Publicidad record) {
		getSqlMapClientTemplate().insert("tbl_publicidad.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public void insertSelective(Publicidad record) {
		getSqlMapClientTemplate().insert("tbl_publicidad.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Publicidad> selectByExample(PublicidadCriteria example) {
		List<Publicidad> list = getSqlMapClientTemplate().queryForList("tbl_publicidad.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public Publicidad selectByPrimaryKey(Integer id) {
		Publicidad key = new Publicidad();
		key.setId(id);
		Publicidad record = (Publicidad) getSqlMapClientTemplate()
				.queryForObject("tbl_publicidad.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Publicidad record, PublicidadCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_publicidad.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public int updateByExample(Publicidad record, PublicidadCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_publicidad.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Publicidad record) {
		int rows = getSqlMapClientTemplate().update("tbl_publicidad.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Publicidad record) {
		int rows = getSqlMapClientTemplate().update("tbl_publicidad.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends PublicidadCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, PublicidadCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}