package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.Reniec;
import pe.gob.ep.iclassq.negocio.bean.ReniecCriteria;
import pe.gob.ep.iclassq.negocio.dao.ReniecDAO;

public class ReniecDAOImpl extends SqlMapClientDaoSupport implements ReniecDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public ReniecDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public int countByExample(ReniecCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_reniec.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public int deleteByExample(ReniecCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_reniec.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Reniec key = new Reniec();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_reniec.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public void insert(Reniec record) {
        getSqlMapClientTemplate().insert("tbl_reniec.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public void insertSelective(Reniec record) {
        getSqlMapClientTemplate().insert("tbl_reniec.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Reniec> selectByExample(ReniecCriteria example) {
        List<Reniec> list = getSqlMapClientTemplate().queryForList("tbl_reniec.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public Reniec selectByPrimaryKey(Integer id) {
        Reniec key = new Reniec();
        key.setId(id);
        Reniec record = (Reniec) getSqlMapClientTemplate().queryForObject("tbl_reniec.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Reniec record, ReniecCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_reniec.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public int updateByExample(Reniec record, ReniecCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_reniec.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Reniec record) {
        int rows = getSqlMapClientTemplate().update("tbl_reniec.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Reniec record) {
        int rows = getSqlMapClientTemplate().update("tbl_reniec.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_reniec
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends ReniecCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, ReniecCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}