package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanRolEquipoSubGrupo;
import pe.gob.ep.iclassq.entidad.BeanSubGrupoProporcion;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoSubGrupo;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoSubGrupoCriteria;
import pe.gob.ep.iclassq.negocio.dao.RolEquipoSubGrupoDAO;

public class RolEquipoSubGrupoDAOImpl extends SqlMapClientDaoSupport implements RolEquipoSubGrupoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public RolEquipoSubGrupoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public int countByExample(RolEquipoSubGrupoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_rol_equipo_subgrupo.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public int deleteByExample(RolEquipoSubGrupoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_rol_equipo_subgrupo.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        RolEquipoSubGrupo key = new RolEquipoSubGrupo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_rol_equipo_subgrupo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public void insert(RolEquipoSubGrupo record) {
        getSqlMapClientTemplate().insert("tbl_rol_equipo_subgrupo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public void insertSelective(RolEquipoSubGrupo record) {
        getSqlMapClientTemplate().insert("tbl_rol_equipo_subgrupo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<RolEquipoSubGrupo> selectByExample(RolEquipoSubGrupoCriteria example) {
        List<RolEquipoSubGrupo> list = getSqlMapClientTemplate().queryForList("tbl_rol_equipo_subgrupo.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public RolEquipoSubGrupo selectByPrimaryKey(Integer id) {
        RolEquipoSubGrupo key = new RolEquipoSubGrupo();
        key.setId(id);
        RolEquipoSubGrupo record = (RolEquipoSubGrupo) getSqlMapClientTemplate().queryForObject("tbl_rol_equipo_subgrupo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(RolEquipoSubGrupo record, RolEquipoSubGrupoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_rol_equipo_subgrupo.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public int updateByExample(RolEquipoSubGrupo record, RolEquipoSubGrupoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_rol_equipo_subgrupo.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(RolEquipoSubGrupo record) {
        int rows = getSqlMapClientTemplate().update("tbl_rol_equipo_subgrupo.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(RolEquipoSubGrupo record) {
        int rows = getSqlMapClientTemplate().update("tbl_rol_equipo_subgrupo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends RolEquipoSubGrupoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, RolEquipoSubGrupoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    @Override
	public List<BeanRolEquipoSubGrupo> listarSubGrupoXRol(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanRolEquipoSubGrupo> list = getSqlMapClientTemplate().queryForList("tbl_rol_equipo_subgrupo.listarSubGrupoXRol", params);
      return list;
	}
 // Generdo por VBR 17/04/2023
 	@Override
 	public List<BeanSubGrupoProporcion> getSubGrupoByRolEquipo(Map<String, Object> params) {
 		// TODO Auto-generated method stub
 		return getSqlMapClientTemplate().queryForList("tbl_rol_equipo_subgrupo.getSubGrupoDelRolEquipo", params);
 	}
 	@Override
 	public int getCantidadRegistrosActualesSG(Map<String, Object> params) {
 		// TODO Auto-generated method stub
 		Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_ticket.getCantidadRegistrosActualesSG", params);
 		System.out.println("count-->>>>>.>>>>"+count);
         return count;
 	}
}