package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.RolEquipo;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoCriteria;
import pe.gob.ep.iclassq.negocio.dao.RolEquipoDAO;

public class RolEquipoDAOImpl extends SqlMapClientDaoSupport implements RolEquipoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public RolEquipoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public int countByExample(RolEquipoCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_rol_equipo.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public int deleteByExample(RolEquipoCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_rol_equipo.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		RolEquipo key = new RolEquipo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_rol_equipo.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public void insert(RolEquipo record) {
		getSqlMapClientTemplate().insert("tbl_rol_equipo.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public void insertSelective(RolEquipo record) {
		getSqlMapClientTemplate().insert("tbl_rol_equipo.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<RolEquipo> selectByExample(RolEquipoCriteria example) {
		List<RolEquipo> list = getSqlMapClientTemplate().queryForList("tbl_rol_equipo.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public RolEquipo selectByPrimaryKey(Integer id) {
		RolEquipo key = new RolEquipo();
		key.setId(id);
		RolEquipo record = (RolEquipo) getSqlMapClientTemplate()
				.queryForObject("tbl_rol_equipo.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(RolEquipo record, RolEquipoCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_rol_equipo.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public int updateByExample(RolEquipo record, RolEquipoCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_rol_equipo.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(RolEquipo record) {
		int rows = getSqlMapClientTemplate().update("tbl_rol_equipo.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(RolEquipo record) {
		int rows = getSqlMapClientTemplate().update("tbl_rol_equipo.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends RolEquipoCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, RolEquipoCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}