package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanGrupoProporcion;
import pe.gob.ep.iclassq.entidad.BeanGrupoXTiempo;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoGrupo;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoGrupoCriteria;
import pe.gob.ep.iclassq.negocio.dao.RolEquipoGrupoDAO;

public class RolEquipoGrupoDAOImpl extends SqlMapClientDaoSupport implements RolEquipoGrupoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public RolEquipoGrupoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public int countByExample(RolEquipoGrupoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_rol_equipo_grupo.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public int deleteByExample(RolEquipoGrupoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_rol_equipo_grupo.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        RolEquipoGrupo key = new RolEquipoGrupo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_rol_equipo_grupo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public void insert(RolEquipoGrupo record) {
        getSqlMapClientTemplate().insert("tbl_rol_equipo_grupo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public void insertSelective(RolEquipoGrupo record) {
        getSqlMapClientTemplate().insert("tbl_rol_equipo_grupo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<RolEquipoGrupo> selectByExample(RolEquipoGrupoCriteria example) {
        List<RolEquipoGrupo> list = getSqlMapClientTemplate().queryForList("tbl_rol_equipo_grupo.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public RolEquipoGrupo selectByPrimaryKey(Integer id) {
        RolEquipoGrupo key = new RolEquipoGrupo();
        key.setId(id);
        RolEquipoGrupo record = (RolEquipoGrupo) getSqlMapClientTemplate().queryForObject("tbl_rol_equipo_grupo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(RolEquipoGrupo record, RolEquipoGrupoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_rol_equipo_grupo.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public int updateByExample(RolEquipoGrupo record, RolEquipoGrupoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_rol_equipo_grupo.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(RolEquipoGrupo record) {
        int rows = getSqlMapClientTemplate().update("tbl_rol_equipo_grupo.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(RolEquipoGrupo record) {
        int rows = getSqlMapClientTemplate().update("tbl_rol_equipo_grupo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends RolEquipoGrupoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, RolEquipoGrupoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<BeanGrupoProporcion> getGrupoByRolEquipo(Map<String, Object> params) {
		// TODO Auto-generated method stub
		return getSqlMapClientTemplate().queryForList("tbl_rol_equipo_grupo.getGrupoDelRolEquipo", params);
	}

//	@Override
//	public int getRegistrosActuales(Map<String, Object> params) {
//		// TODO Auto-generated method stub
//		Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_rol_equipo_grupo.getCantidadRegistrosActuales", params);
//		System.out.println("count-->>>>>.>>>>"+count);
//        return count;
//	}
	
	@Override
	public int getCantidadRegistrosActuales(Map<String, Object> params) {
		// TODO Auto-generated method stub
		Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_rol_equipo_grupo.getCantidadRegistrosActuales", params);
		System.out.println("count-->>>>>.>>>>"+count);
        return count;
	}
	
	@Override
	public List<BeanGrupoXTiempo> listarGruposByTiempo(Map<String, Object> parametro) {
	// TODO Auto-generated method stub
		
		return getSqlMapClientTemplate().queryForList("tbl_rol_equipo_grupo.listarGruposByTiempo", parametro);
	}
	@Override
	public int getCantidadRegistrosActualesBalanceo(Map<String, Object> params) {
		// TODO Auto-generated method stub
		Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_rol_equipo_grupo.getCantidadRegistrosActualesBalanceo", params);
		System.out.println("count-->>>>>.>>>>"+count);
        return count;
	}
	
}