package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.negocio.bean.Secuencia;
import pe.gob.ep.iclassq.negocio.bean.SecuenciaCriteria;
import pe.gob.ep.iclassq.negocio.dao.SecuenciaDAO;

public class SecuenciaDAOImpl extends SqlMapClientDaoSupport implements SecuenciaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public SecuenciaDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public int countByExample(SecuenciaCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_secuencia.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public int deleteByExample(SecuenciaCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_secuencia.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Secuencia key = new Secuencia();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_secuencia.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public void insert(Secuencia record) {
		getSqlMapClientTemplate().insert("tbl_secuencia.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public void insertSelective(Secuencia record) {
		getSqlMapClientTemplate().insert("tbl_secuencia.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Secuencia> selectByExample(SecuenciaCriteria example) {
		List<Secuencia> list = getSqlMapClientTemplate().queryForList("tbl_secuencia.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public Secuencia selectByPrimaryKey(Integer id) {
		Secuencia key = new Secuencia();
		key.setId(id);
		Secuencia record = (Secuencia) getSqlMapClientTemplate()
				.queryForObject("tbl_secuencia.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Secuencia record, SecuenciaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_secuencia.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public int updateByExample(Secuencia record, SecuenciaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_secuencia.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Secuencia record) {
		int rows = getSqlMapClientTemplate().update("tbl_secuencia.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Secuencia record) {
		int rows = getSqlMapClientTemplate().update("tbl_secuencia.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_secuencia
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends SecuenciaCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, SecuenciaCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}