package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.Session;
import pe.gob.ep.iclassq.negocio.bean.SessionCriteria;
import pe.gob.ep.iclassq.negocio.dao.SessionDAO;

public class SessionDAOImpl extends SqlMapClientDaoSupport implements SessionDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public SessionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public int countByExample(SessionCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tbl_session.ibatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public int deleteByExample(SessionCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_session.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(String idSession) {
		Session key = new Session();
		key.setIdSession(idSession);
		int rows = getSqlMapClientTemplate().delete("tbl_session.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public void insert(Session record) {
		getSqlMapClientTemplate().insert("tbl_session.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public void insertSelective(Session record) {
		getSqlMapClientTemplate().insert("tbl_session.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Session> selectByExample(SessionCriteria example) {
		List<Session> list = getSqlMapClientTemplate().queryForList("tbl_session.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public Session selectByPrimaryKey(String idSession) {
		Session key = new Session();
		key.setIdSession(idSession);
		Session record = (Session) getSqlMapClientTemplate()
				.queryForObject("tbl_session.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Session record, SessionCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_session.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public int updateByExample(Session record, SessionCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_session.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Session record) {
		int rows = getSqlMapClientTemplate().update("tbl_session.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Session record) {
		int rows = getSqlMapClientTemplate().update("tbl_session.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_session
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends SessionCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, SessionCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}