package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanSubGrupo;
import pe.gob.ep.iclassq.negocio.bean.SubGrupo;
import pe.gob.ep.iclassq.negocio.bean.SubGrupoCriteria;
import pe.gob.ep.iclassq.negocio.dao.SubGrupoDAO;

public class SubGrupoDAOImpl extends SqlMapClientDaoSupport implements SubGrupoDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public SubGrupoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public int countByExample(SubGrupoCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_subgrupo.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public int deleteByExample(SubGrupoCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_subgrupo.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		SubGrupo key = new SubGrupo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_subgrupo.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public void insert(SubGrupo record) {
		getSqlMapClientTemplate().insert("tbl_subgrupo.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public void insertSelective(SubGrupo record) {
		getSqlMapClientTemplate().insert("tbl_subgrupo.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<SubGrupo> selectByExample(SubGrupoCriteria example) {
		List<SubGrupo> list = getSqlMapClientTemplate().queryForList("tbl_subgrupo.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public SubGrupo selectByPrimaryKey(Integer id) {
		SubGrupo key = new SubGrupo();
		key.setId(id);
		SubGrupo record = (SubGrupo) getSqlMapClientTemplate()
				.queryForObject("tbl_subgrupo.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(SubGrupo record, SubGrupoCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_subgrupo.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public int updateByExample(SubGrupo record, SubGrupoCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_subgrupo.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(SubGrupo record) {
		int rows = getSqlMapClientTemplate().update("tbl_subgrupo.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(SubGrupo record) {
		int rows = getSqlMapClientTemplate().update("tbl_subgrupo.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_subgrupo
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends SubGrupoCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, SubGrupoCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<BeanSubGrupo> listarSubGruposXGrupoAndSucursal(
			Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanSubGrupo> list = getSqlMapClientTemplate().queryForList("tbl_subgrupo.listarSubGruposXSucursal", params);
		return list;
	}
	
	@Override
	public List<SubGrupo> listarSubgrupoXOpcion(SubGrupoCriteria rq) {
	// TODO Auto-generated method stub
		
		return getSqlMapClientTemplate().queryForList("tbl_subgrupo.listarSubgrupoXOpcion", rq);
	} 
}