package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanSucursal;
import pe.gob.ep.iclassq.negocio.bean.Sucursal;
import pe.gob.ep.iclassq.negocio.bean.SucursalCriteria;
import pe.gob.ep.iclassq.negocio.dao.SucursalDAO;

public class SucursalDAOImpl extends SqlMapClientDaoSupport implements SucursalDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public SucursalDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public int countByExample(SucursalCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_sucursal.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public int deleteByExample(SucursalCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_sucursal.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Sucursal key = new Sucursal();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_sucursal.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public void insert(Sucursal record) {
		getSqlMapClientTemplate().insert("tbl_sucursal.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public void insertSelective(Sucursal record) {
		getSqlMapClientTemplate().insert("tbl_sucursal.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Sucursal> selectByExample(SucursalCriteria example) {
		List<Sucursal> list = getSqlMapClientTemplate().queryForList("tbl_sucursal.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public Sucursal selectByPrimaryKey(Integer id) {
		Sucursal key = new Sucursal();
		key.setId(id);
		Sucursal record = (Sucursal) getSqlMapClientTemplate()
				.queryForObject("tbl_sucursal.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Sucursal record, SucursalCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_sucursal.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public int updateByExample(Sucursal record, SucursalCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_sucursal.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Sucursal record) {
		int rows = getSqlMapClientTemplate().update("tbl_sucursal.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Sucursal record) {
		int rows = getSqlMapClientTemplate().update("tbl_sucursal.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends SucursalCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, SucursalCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
 	public List<BeanSucursal> listarSucursalByEmpresa(Map<String, Object> parametro) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_sucursal.listarSucursalByEmpresa", parametro);
 	}
 	
 	@Override
 	public List<BeanSucursal> listarSucursalByUsuario(Map<String, Object> parametro) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_sucursal.listarSucursalByUsuario", parametro);
 	}
 	
 	@Override
 	public List<BeanSucursal> listarSucursalByZona(Map<String, Object> parametro) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_sucursal.listarSucursalByZona", parametro);
 	}
 		
 	public void reiniciarServicio(Integer idSucursal) {
 		Map<String, Object> params = new HashMap<>();
 		params.put("idSucursal", idSucursal);
 		getSqlMapClientTemplate().update("tbl_sucursal.reiniciarServicio", params);
    }
}