package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanTablaGeneral;
import pe.gob.ep.iclassq.negocio.bean.TablaGeneral;
import pe.gob.ep.iclassq.negocio.bean.TablaGeneralCriteria;
import pe.gob.ep.iclassq.negocio.bean.TablaGeneralKey;
import pe.gob.ep.iclassq.negocio.bean.Ventanilla;
import pe.gob.ep.iclassq.negocio.dao.TablaGeneralDAO;

public class TablaGeneralDAOImpl extends SqlMapClientDaoSupport implements TablaGeneralDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public TablaGeneralDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public int countByExample(TablaGeneralCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_tabla_general.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public int deleteByExample(TablaGeneralCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_tabla_general.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(TablaGeneralKey key) {
		int rows = getSqlMapClientTemplate().delete("tbl_tabla_general.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public void insert(TablaGeneral record) {
		getSqlMapClientTemplate().insert("tbl_tabla_general.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public void insertSelective(TablaGeneral record) {
		getSqlMapClientTemplate().insert("tbl_tabla_general.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<TablaGeneral> selectByExample(TablaGeneralCriteria example) {
		List<TablaGeneral> list = getSqlMapClientTemplate()
				.queryForList("tbl_tabla_general.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public TablaGeneral selectByPrimaryKey(TablaGeneralKey key) {
		TablaGeneral record = (TablaGeneral) getSqlMapClientTemplate()
				.queryForObject("tbl_tabla_general.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(TablaGeneral record, TablaGeneralCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_tabla_general.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public int updateByExample(TablaGeneral record, TablaGeneralCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_tabla_general.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(TablaGeneral record) {
		int rows = getSqlMapClientTemplate().update("tbl_tabla_general.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(TablaGeneral record) {
		int rows = getSqlMapClientTemplate().update("tbl_tabla_general.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends TablaGeneralCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, TablaGeneralCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<TablaGeneral> listarTipoAtencion(Map<String, Object> tabla) {
	// TODO Auto-generated method stub
		
		return getSqlMapClientTemplate().queryForList("tbl_tabla_general.listarTipoAtencion", tabla);
	} 
	
}