package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.TicketDerivacion;
import pe.gob.ep.iclassq.negocio.bean.TicketDerivacionCriteria;
import pe.gob.ep.iclassq.negocio.dao.TicketDerivacionDAO;

public class TicketDerivacionDAOImpl extends SqlMapClientDaoSupport implements TicketDerivacionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public TicketDerivacionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public int countByExample(TicketDerivacionCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_ticket_derivacion.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public int deleteByExample(TicketDerivacionCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_ticket_derivacion.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        TicketDerivacion key = new TicketDerivacion();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_ticket_derivacion.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public void insert(TicketDerivacion record) {
        getSqlMapClientTemplate().insert("tbl_ticket_derivacion.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public void insertSelective(TicketDerivacion record) {
        getSqlMapClientTemplate().insert("tbl_ticket_derivacion.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<TicketDerivacion> selectByExample(TicketDerivacionCriteria example) {
        List<TicketDerivacion> list = getSqlMapClientTemplate().queryForList("tbl_ticket_derivacion.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public TicketDerivacion selectByPrimaryKey(Integer id) {
        TicketDerivacion key = new TicketDerivacion();
        key.setId(id);
        TicketDerivacion record = (TicketDerivacion) getSqlMapClientTemplate().queryForObject("tbl_ticket_derivacion.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(TicketDerivacion record, TicketDerivacionCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_ticket_derivacion.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public int updateByExample(TicketDerivacion record, TicketDerivacionCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_ticket_derivacion.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(TicketDerivacion record) {
        int rows = getSqlMapClientTemplate().update("tbl_ticket_derivacion.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(TicketDerivacion record) {
        int rows = getSqlMapClientTemplate().update("tbl_ticket_derivacion.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends TicketDerivacionCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, TicketDerivacionCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}