package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanTicketAreaproxTurno;
import pe.gob.ep.iclassq.entidad.BeanTicketId;
import pe.gob.ep.iclassq.entidad.BeanTicketIdSonido;
import pe.gob.ep.iclassq.entidad.BeanTicketLlamado;
import pe.gob.ep.iclassq.entidad.BeanTicketManagement;
import pe.gob.ep.iclassq.entidad.BeanTicketPreview;
import pe.gob.ep.iclassq.entidad.BeanTicketSecuencial;
import pe.gob.ep.iclassq.entidad.BeanTicketXAlgoritmo;
import pe.gob.ep.iclassq.entidad.BeanTicketXArea;
import pe.gob.ep.iclassq.entidad.BeanTicketXGrupo;
import pe.gob.ep.iclassq.entidad.BeanTicketXMesArea;
import pe.gob.ep.iclassq.entidad.BeanTicketXMesGrupo;
import pe.gob.ep.iclassq.entidad.BeanTicketXMesUsuario;
import pe.gob.ep.iclassq.entidad.BeanTicketXReporte;
import pe.gob.ep.iclassq.entidad.BeanTicketXUsuario;
import pe.gob.ep.iclassq.entidad.BeanUsuarioEstadoGestion;
import pe.gob.ep.iclassq.negocio.bean.Ticket;
import pe.gob.ep.iclassq.negocio.bean.TicketCriteria;
import pe.gob.ep.iclassq.negocio.dao.TicketDAO;

public class TicketDAOImpl extends SqlMapClientDaoSupport implements TicketDAO {

//  meotodos adicionales
    
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public TicketDAOImpl() {
		super();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public int countByExample(TicketCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.ibatorgenerated_countByExample",
				example);
		return count;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public int deleteByExample(TicketCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_ticket.ibatorgenerated_deleteByExample", example);
		return rows;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Ticket key = new Ticket();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_ticket.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public void insert(Ticket record) {
		getSqlMapClientTemplate().insert("tbl_ticket.ibatorgenerated_insert", record);
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public void insertSelective(Ticket record) {
		getSqlMapClientTemplate().insert("tbl_ticket.ibatorgenerated_insertSelective", record);
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Ticket> selectByExample(TicketCriteria example) {
		List<Ticket> list = getSqlMapClientTemplate().queryForList("tbl_ticket.ibatorgenerated_selectByExample",
				example);
		return list;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public Ticket selectByPrimaryKey(Integer id) {
		Ticket key = new Ticket();
		key.setId(id);
		Ticket record = (Ticket) getSqlMapClientTemplate()
				.queryForObject("tbl_ticket.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Ticket record, TicketCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_ticket.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public int updateByExample(Ticket record, TicketCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_ticket.ibatorgenerated_updateByExample", parms);
		return rows;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Ticket record) {
		int rows = getSqlMapClientTemplate().update("tbl_ticket.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Ticket record) {
		int rows = getSqlMapClientTemplate().update("tbl_ticket.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends TicketCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, TicketCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
 	public List<BeanTicketXArea> listarAtencionesXArea(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXArea", paramet);
 	}
     

  	@Override
 	public List<BeanTicketXAlgoritmo> listarAtencionesXAlgoritmo(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXAlgoritmo", paramet);
 	}
  	@Override
 	public List<BeanTicketXAlgoritmo> listaratencionestotalxalgoritmo(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXAlgoritmo", paramet);
 	}
  	
  	@Override
 	public List<BeanTicketXUsuario> listarAtencionesXUsuario(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXUsuario", paramet);
 	}
     

  

  	@Override
 	public List<BeanTicketXGrupo> listarAtencionesXGrupo(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXGrupo", paramet);
 	}
  	

     
  	@Override
	public Ticket listarTicketSecuencial(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (Ticket) getSqlMapClientTemplate().queryForObject("tbl_ticket.listarTicketSecuencial", paramet);
	}
  
  	//Victor adicional
  	@Override
	public int getCantidadTicketEst30_Alg3(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.getCantidadTicketEst30_Alg3", paramet);
	}
  
  	@Override
	public int getMaximaSecuencia31_Alg3(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.getMaximaSecuencia31_Alg3", paramet);
	}
  
  	@Override
	public int getCantidadTicketGrupoEst31_Alg3(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
  	
  	return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.getCantidadTicketGrupoEst31_Alg3", paramet);
	}
  
  	@Override
	public BeanTicketId getNextTicketSubGrupoEst30_Alg3(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketSubGrupoEst30_Alg3", paramet);
	}
  
  	@Override
	public BeanTicketId getNextTicketGrupoEst31_Alg3(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketGrupoEst31_Alg3", paramet);
	}
  
  	@Override
	public BeanTicketId getNextTicketGrupo_Alg_1_2(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketGrupo_Alg_1_2", paramet);
	}
  
  	@Override
	public BeanTicketId getNextTicketEst0_Alg3(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketEst0_Alg3", paramet);
	}

  	@Override
	public BeanTicketId getNextTicketGrupo_Alg3(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketGrupo_Alg3", paramet);
	}

  	@Override
 	public int getCantidadTicketEspera(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
     	
     	return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.getCantidadTicketEspera", paramet);
 	}
  	@Override
 	public int getCantidadTicketEsperaAllGrupo(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
     	
     	return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.getCantidadTicketEsperaAllGrupo", paramet);
 	} 
  	
  	@Override
  	public int getCantidadTicketEsperaByGrupo(Map<String, Object> paramet) {
  		// TODO Auto-generated method stub
  		
  		return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.getCantidadTicketEsperaByGrupo", paramet);
  	} 
  	
  	@Override
 	public int getCantidadTicketEsperaAllSubGrupo(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
     	
     	return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.getCantidadTicketEsperaAllSubGrupo", paramet);
 	}
  	@Override
  	public int getCantidadTicketEsperaAllVentAdmin(Map<String, Object> paramet) {
  		// TODO Auto-generated method stub
  		
  		return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.getCantidadTicketEsperaAllVentAdmin", paramet);
  	}
  	@Override
	public List<BeanTicketLlamado> getListTicketCallVoz(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanTicketLlamado> list = getSqlMapClientTemplate().queryForList("tbl_ticket.getListTicketCallVoz", params);
      return list;
	}

  	@Override
	public List<BeanTicketXReporte> getResultConsultaTicket(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanTicketXReporte> list = getSqlMapClientTemplate().queryForList("tbl_ticket.getResultConsultaTicket", params);
      return list;
	}


	@Override
	public List<BeanTicketXMesUsuario> listarAtencionesXMesUsuario(Map<String, Object> param) {
		// TODO Auto-generated method stub
		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXMesUsuario", param);
	}

	@Override
	public List<BeanTicketXMesGrupo> listarAtencionesXMesGrupo(Map<String, Object> params) {
		// TODO Auto-generated method stub
		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXMesGrupo", params);
	}

	
	@Override
	public List<BeanTicketXMesArea> listarAtencionesXMesArea(Map<String, Object> params) {
		// TODO Auto-generated method stub
		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXMesArea", params);
	}

	@Override
	public List<BeanTicketXMesArea> listarAtencionesComparativo(Map<String, Object> params) {
		// TODO Auto-generated method stub
		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesComparativo", params);
	}

	@Override
	public List<BeanTicketXReporte> getResultGestionTicket(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanTicketXReporte> list = getSqlMapClientTemplate().queryForList("tbl_ticket.getResultGestionTicket", params);
		return list;
	}

	@Override
	public List<BeanTicketXArea> GestionTicket_1_Apellido(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanTicketXArea> list = getSqlMapClientTemplate().queryForList("tbl_ticket.GestionTicket_1_Apellido", params);
		return list;
	}	
	@Override
	public List<BeanTicketXArea> GestionTicket_1_Codigo(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanTicketXArea> list = getSqlMapClientTemplate().queryForList("tbl_ticket.GestionTicket_1_Codigo", params);
		return list;
	}

	
  	@Override
	public BeanTicketIdSonido sonidoTimbreTicket(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (BeanTicketIdSonido) getSqlMapClientTemplate().queryForObject("tbl_ticket.sonidoTimbreTicket", paramet);
	}
  	@Override
  	public List<BeanTicketXArea> listarAtencionesXDni(Map<String, Object> params) {
		// TODO Auto-generated method stub
		return getSqlMapClientTemplate().queryForList("tbl_ticket.listarAtencionesXDni", params);
	}

  	@Override
	public List<BeanTicketAreaproxTurno> getProximosTurnosArea(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanTicketAreaproxTurno> list = getSqlMapClientTemplate().queryForList("tbl_ticket.getProximosTurnosArea", params);
      return list;
	}

  	@Override
	public BeanTicketId getNextTicketSubGrupo_Alg_1_2(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketSubGrupo_Alg_1_2", paramet);
	}
  	
  	@Override
	public BeanTicketId getNextTicketSubGrupo_Alg_1_2_VS(Map<String, Object> paramet) {
		// TODO Auto-generated method stub
		
		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketSubGrupo_Alg_1_2_VS", paramet);
	}
  	
  	@Override
  	public BeanTicketId getNextTicketSubGrupo_Alg_1_2_VA(Map<String, Object> paramet) {
  		// TODO Auto-generated method stub
  		
  		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketSubGrupo_Alg_1_2_VA", paramet);
  	}
  	
  	@Override
  	public BeanTicketId getNextTicketByGrupoAlg1(Map<String, Object> paramet) {
  		// TODO Auto-generated method stub
  		
  		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketByGrupoAlg1", paramet);
  	}
  	
  	@Override
  	public BeanTicketId getNextTicketByGrupoAlg2(Map<String, Object> paramet) {
  		// TODO Auto-generated method stub
  		
  		return (BeanTicketId) getSqlMapClientTemplate().queryForObject("tbl_ticket.getNextTicketByGrupoAlg2", paramet);
  	}
	
	//actualizacion de eventos desde JOB
	@Override
	public void actulizarMonitorcajas() {
		// TODO Auto-generated method stub
		//jobActualizarMonitorCajas1
		
	}
	
	// MATIAS: traer Nombre del grupo segun id subgrupo
	@Override
 	public List<BeanTicketXGrupo> getNombreGrupoByIdSucursal(Map<String, Object> paramet) {
 		// TODO Auto-generated method stub
 		
 		return getSqlMapClientTemplate().queryForList("tbl_ticket.getNombreGrupo", paramet);
 	}
	
	@Override
	public List<BeanTicketPreview> getDataTicketsPreview(Map<String, Object> paramet) { 
		// TODO Auto-generated method stub
		List<BeanTicketPreview> list = getSqlMapClientTemplate().queryForList("tbl_ticket.listResultTicketPreview", paramet);
		return list;
	}
	
	@Override
    public Ticket getOldestWaitingTicket(Map<String,Object> params) {
            return (Ticket) getSqlMapClientTemplate().queryForObject("tbl_ticket.getOldestWaitingTicket", params);
    }

    @Override
    public int assignTicketToUser(Map<String, Object> params) {
            return getSqlMapClientTemplate().update("tbl_ticket.assignTicketToUser", params);
    }
    
    @Override
    public int contarTicketAtendidosDia(Map<String, Object> params) {
    	return (Integer) getSqlMapClientTemplate().queryForObject("tbl_ticket.contarTicketsAtendidosDia", params);
    }
		
    @Override
	public List<BeanTicketManagement> getReportTicketManagement(Map<String, Object> paramet) { 
		// TODO Auto-generated method stub
		List<BeanTicketManagement> list = getSqlMapClientTemplate().queryForList("tbl_ticket.listReportTicketManagement", paramet);
		return list;
	}
}