package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.negocio.bean.TipoDocumento;
import pe.gob.ep.iclassq.negocio.bean.TipoDocumentoCriteria;
import pe.gob.ep.iclassq.negocio.dao.TipoDocumentoDAO;

public class TipoDocumentoDAOImpl extends SqlMapClientDaoSupport implements TipoDocumentoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public TipoDocumentoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public int countByExample(TipoDocumentoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cat_tipo_documento.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public int deleteByExample(TipoDocumentoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("cat_tipo_documento.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        TipoDocumento key = new TipoDocumento();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("cat_tipo_documento.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public void insert(TipoDocumento record) {
        getSqlMapClientTemplate().insert("cat_tipo_documento.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public void insertSelective(TipoDocumento record) {
        getSqlMapClientTemplate().insert("cat_tipo_documento.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<TipoDocumento> selectByExample(TipoDocumentoCriteria example) {
        List<TipoDocumento> list = getSqlMapClientTemplate().queryForList("cat_tipo_documento.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public TipoDocumento selectByPrimaryKey(Integer id) {
        TipoDocumento key = new TipoDocumento();
        key.setId(id);
        TipoDocumento record = (TipoDocumento) getSqlMapClientTemplate().queryForObject("cat_tipo_documento.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(TipoDocumento record, TipoDocumentoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cat_tipo_documento.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public int updateByExample(TipoDocumento record, TipoDocumentoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cat_tipo_documento.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(TipoDocumento record) {
        int rows = getSqlMapClientTemplate().update("cat_tipo_documento.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(TipoDocumento record) {
        int rows = getSqlMapClientTemplate().update("cat_tipo_documento.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends TipoDocumentoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, TipoDocumentoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}