package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanUsuarioAusencia;
import pe.gob.ep.iclassq.negocio.bean.UsuarioAusencia;
import pe.gob.ep.iclassq.negocio.bean.UsuarioAusenciaCriteria;
import pe.gob.ep.iclassq.negocio.dao.UsuarioAusenciaDAO;

public class UsuarioAusenciaDAOImpl extends SqlMapClientDaoSupport implements UsuarioAusenciaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public UsuarioAusenciaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public int countByExample(UsuarioAusenciaCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_usuario_ausencia.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public int deleteByExample(UsuarioAusenciaCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_usuario_ausencia.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        UsuarioAusencia key = new UsuarioAusencia();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_usuario_ausencia.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public void insert(UsuarioAusencia record) {
        getSqlMapClientTemplate().insert("tbl_usuario_ausencia.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public void insertSelective(UsuarioAusencia record) {
        getSqlMapClientTemplate().insert("tbl_usuario_ausencia.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<UsuarioAusencia> selectByExample(UsuarioAusenciaCriteria example) {
        List<UsuarioAusencia> list = getSqlMapClientTemplate().queryForList("tbl_usuario_ausencia.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public UsuarioAusencia selectByPrimaryKey(Integer id) {
        UsuarioAusencia key = new UsuarioAusencia();
        key.setId(id);
        UsuarioAusencia record = (UsuarioAusencia) getSqlMapClientTemplate().queryForObject("tbl_usuario_ausencia.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(UsuarioAusencia record, UsuarioAusenciaCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_usuario_ausencia.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public int updateByExample(UsuarioAusencia record, UsuarioAusenciaCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_usuario_ausencia.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(UsuarioAusencia record) {
        int rows = getSqlMapClientTemplate().update("tbl_usuario_ausencia.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(UsuarioAusencia record) {
        int rows = getSqlMapClientTemplate().update("tbl_usuario_ausencia.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends UsuarioAusenciaCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, UsuarioAusenciaCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    @Override
	public List<BeanUsuarioAusencia> getDataUserAbsence(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<BeanUsuarioAusencia> list = getSqlMapClientTemplate().queryForList("tbl_usuario_ausencia.listDataUserAbcense", params);
      return list;
	}
}