package pe.gob.ep.iclassq.negocio.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.iclassq.entidad.BeanGrupo;
import pe.gob.ep.iclassq.entidad.BeanTicketAreaproxTurno;
import pe.gob.ep.iclassq.entidad.BeanTicketXArea;
import pe.gob.ep.iclassq.negocio.bean.Ventanilla;
import pe.gob.ep.iclassq.negocio.bean.VentanillaCriteria;
import pe.gob.ep.iclassq.negocio.dao.VentanillaDAO;

public class VentanillaDAOImpl extends SqlMapClientDaoSupport implements VentanillaDAO {

	
    
//  metodos adicionales

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public VentanillaDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public int countByExample(VentanillaCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("tbl_ventanilla.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public int deleteByExample(VentanillaCriteria example) {
		int rows = getSqlMapClientTemplate().delete("tbl_ventanilla.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		Ventanilla key = new Ventanilla();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("tbl_ventanilla.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public void insert(Ventanilla record) {
		getSqlMapClientTemplate().insert("tbl_ventanilla.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public void insertSelective(Ventanilla record) {
		getSqlMapClientTemplate().insert("tbl_ventanilla.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<Ventanilla> selectByExample(VentanillaCriteria example) {
		List<Ventanilla> list = getSqlMapClientTemplate().queryForList("tbl_ventanilla.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public Ventanilla selectByPrimaryKey(Integer id) {
		Ventanilla key = new Ventanilla();
		key.setId(id);
		Ventanilla record = (Ventanilla) getSqlMapClientTemplate()
				.queryForObject("tbl_ventanilla.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(Ventanilla record, VentanillaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_ventanilla.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public int updateByExample(Ventanilla record, VentanillaCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("tbl_ventanilla.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(Ventanilla record) {
		int rows = getSqlMapClientTemplate().update("tbl_ventanilla.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(Ventanilla record) {
		int rows = getSqlMapClientTemplate().update("tbl_ventanilla.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends VentanillaCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, VentanillaCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Ventanilla> listarventanillasxparametroTipoDeriva(Map<String, Object> parametro) {
	// TODO Auto-generated method stub
		
		return getSqlMapClientTemplate().queryForList("tbl_ventanilla.listarventanillaxparametroTipoDeriva", parametro);
	} 

    
}