package pe.gob.ep.iclassq.negocio.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AlgoritmoXGrupoCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public AlgoritmoXGrupoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    protected AlgoritmoXGrupoCriteria(AlgoritmoXGrupoCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andIdGrupoIsNull() {
            addCriterion("id_grupo is null");
            return this;
        }

        public Criteria andIdGrupoIsNotNull() {
            addCriterion("id_grupo is not null");
            return this;
        }

        public Criteria andIdGrupoEqualTo(Integer value) {
            addCriterion("id_grupo =", value, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoNotEqualTo(Integer value) {
            addCriterion("id_grupo <>", value, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoGreaterThan(Integer value) {
            addCriterion("id_grupo >", value, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_grupo >=", value, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoLessThan(Integer value) {
            addCriterion("id_grupo <", value, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoLessThanOrEqualTo(Integer value) {
            addCriterion("id_grupo <=", value, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoIn(List<Integer> values) {
            addCriterion("id_grupo in", values, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoNotIn(List<Integer> values) {
            addCriterion("id_grupo not in", values, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoBetween(Integer value1, Integer value2) {
            addCriterion("id_grupo between", value1, value2, "idGrupo");
            return this;
        }

        public Criteria andIdGrupoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_grupo not between", value1, value2, "idGrupo");
            return this;
        }

        public Criteria andIdAlgoritmoIsNull() {
            addCriterion("id_algoritmo is null");
            return this;
        }

        public Criteria andIdAlgoritmoIsNotNull() {
            addCriterion("id_algoritmo is not null");
            return this;
        }

        public Criteria andIdAlgoritmoEqualTo(Integer value) {
            addCriterion("id_algoritmo =", value, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoNotEqualTo(Integer value) {
            addCriterion("id_algoritmo <>", value, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoGreaterThan(Integer value) {
            addCriterion("id_algoritmo >", value, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_algoritmo >=", value, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoLessThan(Integer value) {
            addCriterion("id_algoritmo <", value, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoLessThanOrEqualTo(Integer value) {
            addCriterion("id_algoritmo <=", value, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoIn(List<Integer> values) {
            addCriterion("id_algoritmo in", values, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoNotIn(List<Integer> values) {
            addCriterion("id_algoritmo not in", values, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoBetween(Integer value1, Integer value2) {
            addCriterion("id_algoritmo between", value1, value2, "idAlgoritmo");
            return this;
        }

        public Criteria andIdAlgoritmoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_algoritmo not between", value1, value2, "idAlgoritmo");
            return this;
        }
    }
}