package pe.gob.ep.iclassq.negocio.bean;

public class AlgoritmoXGrupo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_algoritmoxgrupo.id
     *
     * @ibatorgenerated
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_algoritmoxgrupo.id_grupo
     *
     * @ibatorgenerated
     */
    private Integer idGrupo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_algoritmoxgrupo.id_algoritmo
     *
     * @ibatorgenerated
     */
    private Integer idAlgoritmo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_algoritmoxgrupo.id
     *
     * @return the value of tbl_algoritmoxgrupo.id
     *
     * @ibatorgenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_algoritmoxgrupo.id
     *
     * @param id the value for tbl_algoritmoxgrupo.id
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_algoritmoxgrupo.id_grupo
     *
     * @return the value of tbl_algoritmoxgrupo.id_grupo
     *
     * @ibatorgenerated
     */
    public Integer getIdGrupo() {
        return idGrupo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_algoritmoxgrupo.id_grupo
     *
     * @param idGrupo the value for tbl_algoritmoxgrupo.id_grupo
     *
     * @ibatorgenerated
     */
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_algoritmoxgrupo.id_algoritmo
     *
     * @return the value of tbl_algoritmoxgrupo.id_algoritmo
     *
     * @ibatorgenerated
     */
    public Integer getIdAlgoritmo() {
        return idAlgoritmo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_algoritmoxgrupo.id_algoritmo
     *
     * @param idAlgoritmo the value for tbl_algoritmoxgrupo.id_algoritmo
     *
     * @ibatorgenerated
     */
    public void setIdAlgoritmo(Integer idAlgoritmo) {
        this.idAlgoritmo = idAlgoritmo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof AlgoritmoXGrupo)) {
            return false;
        }
        AlgoritmoXGrupo other = (AlgoritmoXGrupo) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getIdGrupo() == null ? other == null : this.getIdGrupo().equals(other.getIdGrupo())
            && this.getIdAlgoritmo() == null ? other == null : this.getIdAlgoritmo().equals(other.getIdAlgoritmo());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_algoritmoxgrupo
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getIdGrupo() != null) {
            hash *= getIdGrupo().hashCode();
        }
        if (getIdAlgoritmo() != null) {
            hash *= getIdAlgoritmo().hashCode();
        }
        return hash;
    }
}