package pe.gob.ep.iclassq.negocio.bean;

public class EncuestaOpciones {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_encuesta_opciones.id
     *
     * @ibatorgenerated
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_encuesta_opciones.descripcion
     *
     * @ibatorgenerated
     */
    private String descripcion;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_encuesta_opciones.id
     *
     * @return the value of tbl_encuesta_opciones.id
     *
     * @ibatorgenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_encuesta_opciones.id
     *
     * @param id the value for tbl_encuesta_opciones.id
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_encuesta_opciones.descripcion
     *
     * @return the value of tbl_encuesta_opciones.descripcion
     *
     * @ibatorgenerated
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_encuesta_opciones.descripcion
     *
     * @param descripcion the value for tbl_encuesta_opciones.descripcion
     *
     * @ibatorgenerated
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof EncuestaOpciones)) {
            return false;
        }
        EncuestaOpciones other = (EncuestaOpciones) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getDescripcion() == null ? other == null : this.getDescripcion().equals(other.getDescripcion());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_encuesta_opciones
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getDescripcion() != null) {
            hash *= getDescripcion().hashCode();
        }
        return hash;
    }
}