package pe.gob.ep.iclassq.negocio.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class EncuestaPreguntasCriteria {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public EncuestaPreguntasCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	protected EncuestaPreguntasCriteria(EncuestaPreguntasCriteria example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andIdEncuestaIsNull() {
			addCriterion("id_encuesta is null");
			return this;
		}

		public Criteria andIdEncuestaIsNotNull() {
			addCriterion("id_encuesta is not null");
			return this;
		}

		public Criteria andIdEncuestaEqualTo(Integer value) {
			addCriterion("id_encuesta =", value, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaNotEqualTo(Integer value) {
			addCriterion("id_encuesta <>", value, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaGreaterThan(Integer value) {
			addCriterion("id_encuesta >", value, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_encuesta >=", value, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaLessThan(Integer value) {
			addCriterion("id_encuesta <", value, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaLessThanOrEqualTo(Integer value) {
			addCriterion("id_encuesta <=", value, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaIn(List<Integer> values) {
			addCriterion("id_encuesta in", values, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaNotIn(List<Integer> values) {
			addCriterion("id_encuesta not in", values, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaBetween(Integer value1, Integer value2) {
			addCriterion("id_encuesta between", value1, value2, "idEncuesta");
			return this;
		}

		public Criteria andIdEncuestaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_encuesta not between", value1, value2, "idEncuesta");
			return this;
		}

		public Criteria andIdSucursalIsNull() {
			addCriterion("id_sucursal is null");
			return this;
		}

		public Criteria andIdSucursalIsNotNull() {
			addCriterion("id_sucursal is not null");
			return this;
		}

		public Criteria andIdSucursalEqualTo(Integer value) {
			addCriterion("id_sucursal =", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotEqualTo(Integer value) {
			addCriterion("id_sucursal <>", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalGreaterThan(Integer value) {
			addCriterion("id_sucursal >", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_sucursal >=", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalLessThan(Integer value) {
			addCriterion("id_sucursal <", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalLessThanOrEqualTo(Integer value) {
			addCriterion("id_sucursal <=", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalIn(List<Integer> values) {
			addCriterion("id_sucursal in", values, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotIn(List<Integer> values) {
			addCriterion("id_sucursal not in", values, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalBetween(Integer value1, Integer value2) {
			addCriterion("id_sucursal between", value1, value2, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotBetween(Integer value1, Integer value2) {
			addCriterion("id_sucursal not between", value1, value2, "idSucursal");
			return this;
		}

		public Criteria andDescripcionIsNull() {
			addCriterion("descripcion is null");
			return this;
		}

		public Criteria andDescripcionIsNotNull() {
			addCriterion("descripcion is not null");
			return this;
		}

		public Criteria andDescripcionEqualTo(String value) {
			addCriterion("descripcion =", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotEqualTo(String value) {
			addCriterion("descripcion <>", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThan(String value) {
			addCriterion("descripcion >", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
			addCriterion("descripcion >=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThan(String value) {
			addCriterion("descripcion <", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThanOrEqualTo(String value) {
			addCriterion("descripcion <=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLike(String value) {
			addCriterion("descripcion like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotLike(String value) {
			addCriterion("descripcion not like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionIn(List<String> values) {
			addCriterion("descripcion in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotIn(List<String> values) {
			addCriterion("descripcion not in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionBetween(String value1, String value2) {
			addCriterion("descripcion between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotBetween(String value1, String value2) {
			addCriterion("descripcion not between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andFechaCreacionIsNull() {
			addCriterion("fecha_creacion is null");
			return this;
		}

		public Criteria andFechaCreacionIsNotNull() {
			addCriterion("fecha_creacion is not null");
			return this;
		}

		public Criteria andFechaCreacionEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_creacion =", value, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionNotEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_creacion <>", value, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionGreaterThan(Date value) {
			addCriterionForJDBCDate("fecha_creacion >", value, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_creacion >=", value, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionLessThan(Date value) {
			addCriterionForJDBCDate("fecha_creacion <", value, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_creacion <=", value, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionIn(List<Date> values) {
			addCriterionForJDBCDate("fecha_creacion in", values, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionNotIn(List<Date> values) {
			addCriterionForJDBCDate("fecha_creacion not in", values, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_creacion between", value1, value2, "fechaCreacion");
			return this;
		}

		public Criteria andFechaCreacionNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_creacion not between", value1, value2, "fechaCreacion");
			return this;
		}

		public Criteria andFechaModificacionIsNull() {
			addCriterion("fecha_modificacion is null");
			return this;
		}

		public Criteria andFechaModificacionIsNotNull() {
			addCriterion("fecha_modificacion is not null");
			return this;
		}

		public Criteria andFechaModificacionEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_modificacion =", value, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionNotEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_modificacion <>", value, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionGreaterThan(Date value) {
			addCriterionForJDBCDate("fecha_modificacion >", value, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_modificacion >=", value, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionLessThan(Date value) {
			addCriterionForJDBCDate("fecha_modificacion <", value, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_modificacion <=", value, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionIn(List<Date> values) {
			addCriterionForJDBCDate("fecha_modificacion in", values, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionNotIn(List<Date> values) {
			addCriterionForJDBCDate("fecha_modificacion not in", values, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_modificacion between", value1, value2, "fechaModificacion");
			return this;
		}

		public Criteria andFechaModificacionNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_modificacion not between", value1, value2, "fechaModificacion");
			return this;
		}

		public Criteria andEstadoIsNull() {
			addCriterion("estado is null");
			return this;
		}

		public Criteria andEstadoIsNotNull() {
			addCriterion("estado is not null");
			return this;
		}

		public Criteria andEstadoEqualTo(Integer value) {
			addCriterion("estado =", value, "estado");
			return this;
		}

		public Criteria andEstadoNotEqualTo(Integer value) {
			addCriterion("estado <>", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThan(Integer value) {
			addCriterion("estado >", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("estado >=", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThan(Integer value) {
			addCriterion("estado <", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThanOrEqualTo(Integer value) {
			addCriterion("estado <=", value, "estado");
			return this;
		}

		public Criteria andEstadoIn(List<Integer> values) {
			addCriterion("estado in", values, "estado");
			return this;
		}

		public Criteria andEstadoNotIn(List<Integer> values) {
			addCriterion("estado not in", values, "estado");
			return this;
		}

		public Criteria andEstadoBetween(Integer value1, Integer value2) {
			addCriterion("estado between", value1, value2, "estado");
			return this;
		}

		public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
			addCriterion("estado not between", value1, value2, "estado");
			return this;
		}
	}
}