package pe.gob.ep.iclassq.negocio.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GrupoXSedeCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public GrupoXSedeCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    protected GrupoXSedeCriteria(GrupoXSedeCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_grupoxsede
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andCodSedeIsNull() {
            addCriterion("cod_sede is null");
            return this;
        }

        public Criteria andCodSedeIsNotNull() {
            addCriterion("cod_sede is not null");
            return this;
        }

        public Criteria andCodSedeEqualTo(String value) {
            addCriterion("cod_sede =", value, "codSede");
            return this;
        }

        public Criteria andCodSedeNotEqualTo(String value) {
            addCriterion("cod_sede <>", value, "codSede");
            return this;
        }

        public Criteria andCodSedeGreaterThan(String value) {
            addCriterion("cod_sede >", value, "codSede");
            return this;
        }

        public Criteria andCodSedeGreaterThanOrEqualTo(String value) {
            addCriterion("cod_sede >=", value, "codSede");
            return this;
        }

        public Criteria andCodSedeLessThan(String value) {
            addCriterion("cod_sede <", value, "codSede");
            return this;
        }

        public Criteria andCodSedeLessThanOrEqualTo(String value) {
            addCriterion("cod_sede <=", value, "codSede");
            return this;
        }

        public Criteria andCodSedeLike(String value) {
            addCriterion("cod_sede like", value, "codSede");
            return this;
        }

        public Criteria andCodSedeNotLike(String value) {
            addCriterion("cod_sede not like", value, "codSede");
            return this;
        }

        public Criteria andCodSedeIn(List<String> values) {
            addCriterion("cod_sede in", values, "codSede");
            return this;
        }

        public Criteria andCodSedeNotIn(List<String> values) {
            addCriterion("cod_sede not in", values, "codSede");
            return this;
        }

        public Criteria andCodSedeBetween(String value1, String value2) {
            addCriterion("cod_sede between", value1, value2, "codSede");
            return this;
        }

        public Criteria andCodSedeNotBetween(String value1, String value2) {
            addCriterion("cod_sede not between", value1, value2, "codSede");
            return this;
        }

        public Criteria andGrupoIsNull() {
            addCriterion("grupo is null");
            return this;
        }

        public Criteria andGrupoIsNotNull() {
            addCriterion("grupo is not null");
            return this;
        }

        public Criteria andGrupoEqualTo(String value) {
            addCriterion("grupo =", value, "grupo");
            return this;
        }

        public Criteria andGrupoNotEqualTo(String value) {
            addCriterion("grupo <>", value, "grupo");
            return this;
        }

        public Criteria andGrupoGreaterThan(String value) {
            addCriterion("grupo >", value, "grupo");
            return this;
        }

        public Criteria andGrupoGreaterThanOrEqualTo(String value) {
            addCriterion("grupo >=", value, "grupo");
            return this;
        }

        public Criteria andGrupoLessThan(String value) {
            addCriterion("grupo <", value, "grupo");
            return this;
        }

        public Criteria andGrupoLessThanOrEqualTo(String value) {
            addCriterion("grupo <=", value, "grupo");
            return this;
        }

        public Criteria andGrupoLike(String value) {
            addCriterion("grupo like", value, "grupo");
            return this;
        }

        public Criteria andGrupoNotLike(String value) {
            addCriterion("grupo not like", value, "grupo");
            return this;
        }

        public Criteria andGrupoIn(List<String> values) {
            addCriterion("grupo in", values, "grupo");
            return this;
        }

        public Criteria andGrupoNotIn(List<String> values) {
            addCriterion("grupo not in", values, "grupo");
            return this;
        }

        public Criteria andGrupoBetween(String value1, String value2) {
            addCriterion("grupo between", value1, value2, "grupo");
            return this;
        }

        public Criteria andGrupoNotBetween(String value1, String value2) {
            addCriterion("grupo not between", value1, value2, "grupo");
            return this;
        }

        public Criteria andTipoAsignacionTurnoIsNull() {
            addCriterion("tipo_asignacion_turno is null");
            return this;
        }

        public Criteria andTipoAsignacionTurnoIsNotNull() {
            addCriterion("tipo_asignacion_turno is not null");
            return this;
        }

        public Criteria andTipoAsignacionTurnoEqualTo(String value) {
            addCriterion("tipo_asignacion_turno =", value, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoNotEqualTo(String value) {
            addCriterion("tipo_asignacion_turno <>", value, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoGreaterThan(String value) {
            addCriterion("tipo_asignacion_turno >", value, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoGreaterThanOrEqualTo(String value) {
            addCriterion("tipo_asignacion_turno >=", value, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoLessThan(String value) {
            addCriterion("tipo_asignacion_turno <", value, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoLessThanOrEqualTo(String value) {
            addCriterion("tipo_asignacion_turno <=", value, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoLike(String value) {
            addCriterion("tipo_asignacion_turno like", value, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoNotLike(String value) {
            addCriterion("tipo_asignacion_turno not like", value, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoIn(List<String> values) {
            addCriterion("tipo_asignacion_turno in", values, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoNotIn(List<String> values) {
            addCriterion("tipo_asignacion_turno not in", values, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoBetween(String value1, String value2) {
            addCriterion("tipo_asignacion_turno between", value1, value2, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andTipoAsignacionTurnoNotBetween(String value1, String value2) {
            addCriterion("tipo_asignacion_turno not between", value1, value2, "tipoAsignacionTurno");
            return this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("estado =", value, "estado");
            return this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("estado <>", value, "estado");
            return this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("estado >", value, "estado");
            return this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("estado >=", value, "estado");
            return this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("estado <", value, "estado");
            return this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("estado <=", value, "estado");
            return this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("estado in", values, "estado");
            return this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("estado not in", values, "estado");
            return this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("estado between", value1, value2, "estado");
            return this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return this;
        }
    }
}