package pe.gob.ep.iclassq.negocio.bean;

import java.util.Date;

public class MonitorCajas {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.id
	 * @ibatorgenerated
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.id_usuario
	 * @ibatorgenerated
	 */
	private Integer idUsuario;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.id_sucursal
	 * @ibatorgenerated
	 */
	private Integer idSucursal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.secuencia
	 * @ibatorgenerated
	 */
	private Integer secuencia;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.id_ticket
	 * @ibatorgenerated
	 */
	private Integer idTicket;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.nombre_ventanilla
	 * @ibatorgenerated
	 */
	private String nombreVentanilla;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.ticket_texto
	 * @ibatorgenerated
	 */
	private String ticketTexto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.estado
	 * @ibatorgenerated
	 */
	private Integer estado;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_monitor_cajas.fecha_hora_llamado
	 * @ibatorgenerated
	 */
	private Date fechaHoraLlamado;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.id
	 * @return  the value of tbl_monitor_cajas.id
	 * @ibatorgenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.id
	 * @param id  the value for tbl_monitor_cajas.id
	 * @ibatorgenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.id_usuario
	 * @return  the value of tbl_monitor_cajas.id_usuario
	 * @ibatorgenerated
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.id_usuario
	 * @param idUsuario  the value for tbl_monitor_cajas.id_usuario
	 * @ibatorgenerated
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.id_sucursal
	 * @return  the value of tbl_monitor_cajas.id_sucursal
	 * @ibatorgenerated
	 */
	public Integer getIdSucursal() {
		return idSucursal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.id_sucursal
	 * @param idSucursal  the value for tbl_monitor_cajas.id_sucursal
	 * @ibatorgenerated
	 */
	public void setIdSucursal(Integer idSucursal) {
		this.idSucursal = idSucursal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.secuencia
	 * @return  the value of tbl_monitor_cajas.secuencia
	 * @ibatorgenerated
	 */
	public Integer getSecuencia() {
		return secuencia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.secuencia
	 * @param secuencia  the value for tbl_monitor_cajas.secuencia
	 * @ibatorgenerated
	 */
	public void setSecuencia(Integer secuencia) {
		this.secuencia = secuencia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.id_ticket
	 * @return  the value of tbl_monitor_cajas.id_ticket
	 * @ibatorgenerated
	 */
	public Integer getIdTicket() {
		return idTicket;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.id_ticket
	 * @param idTicket  the value for tbl_monitor_cajas.id_ticket
	 * @ibatorgenerated
	 */
	public void setIdTicket(Integer idTicket) {
		this.idTicket = idTicket;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.nombre_ventanilla
	 * @return  the value of tbl_monitor_cajas.nombre_ventanilla
	 * @ibatorgenerated
	 */
	public String getNombreVentanilla() {
		return nombreVentanilla;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.nombre_ventanilla
	 * @param nombreVentanilla  the value for tbl_monitor_cajas.nombre_ventanilla
	 * @ibatorgenerated
	 */
	public void setNombreVentanilla(String nombreVentanilla) {
		this.nombreVentanilla = nombreVentanilla;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.ticket_texto
	 * @return  the value of tbl_monitor_cajas.ticket_texto
	 * @ibatorgenerated
	 */
	public String getTicketTexto() {
		return ticketTexto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.ticket_texto
	 * @param ticketTexto  the value for tbl_monitor_cajas.ticket_texto
	 * @ibatorgenerated
	 */
	public void setTicketTexto(String ticketTexto) {
		this.ticketTexto = ticketTexto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.estado
	 * @return  the value of tbl_monitor_cajas.estado
	 * @ibatorgenerated
	 */
	public Integer getEstado() {
		return estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.estado
	 * @param estado  the value for tbl_monitor_cajas.estado
	 * @ibatorgenerated
	 */
	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_monitor_cajas.fecha_hora_llamado
	 * @return  the value of tbl_monitor_cajas.fecha_hora_llamado
	 * @ibatorgenerated
	 */
	public Date getFechaHoraLlamado() {
		return fechaHoraLlamado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_monitor_cajas.fecha_hora_llamado
	 * @param fechaHoraLlamado  the value for tbl_monitor_cajas.fecha_hora_llamado
	 * @ibatorgenerated
	 */
	public void setFechaHoraLlamado(Date fechaHoraLlamado) {
		this.fechaHoraLlamado = fechaHoraLlamado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof MonitorCajas)) {
			return false;
		}
		MonitorCajas other = (MonitorCajas) that;
		return this.getId() == null ? other == null
				: this.getId().equals(other.getId()) && this.getIdUsuario() == null ? other == null
						: this.getIdUsuario().equals(other.getIdUsuario()) && this.getIdSucursal() == null
								? other == null
								: this.getIdSucursal().equals(other.getIdSucursal()) && this.getSecuencia() == null
										? other == null
										: this.getSecuencia().equals(other.getSecuencia()) && this.getIdTicket() == null
												? other == null
												: this.getIdTicket().equals(other.getIdTicket())
														&& this.getNombreVentanilla() == null
																? other == null
																: this.getNombreVentanilla()
																		.equals(other.getNombreVentanilla())
																		&& this.getTicketTexto() == null
																				? other == null
																				: this.getTicketTexto()
																						.equals(other.getTicketTexto())
																						&& this.getEstado() == null
																								? other == null
																								: this.getEstado()
																										.equals(other
																												.getEstado())
																										&& this.getFechaHoraLlamado() == null
																												? other == null
																												: this.getFechaHoraLlamado()
																														.equals(other
																																.getFechaHoraLlamado());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getIdUsuario() != null) {
			hash *= getIdUsuario().hashCode();
		}
		if (getIdSucursal() != null) {
			hash *= getIdSucursal().hashCode();
		}
		if (getSecuencia() != null) {
			hash *= getSecuencia().hashCode();
		}
		if (getIdTicket() != null) {
			hash *= getIdTicket().hashCode();
		}
		if (getNombreVentanilla() != null) {
			hash *= getNombreVentanilla().hashCode();
		}
		if (getTicketTexto() != null) {
			hash *= getTicketTexto().hashCode();
		}
		if (getEstado() != null) {
			hash *= getEstado().hashCode();
		}
		if (getFechaHoraLlamado() != null) {
			hash *= getFechaHoraLlamado().hashCode();
		}
		return hash;
	}
}