package pe.gob.ep.iclassq.negocio.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MonitorCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public MonitorCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    protected MonitorCriteria(MonitorCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andCodigoAtencionIsNull() {
            addCriterion("codigo_atencion is null");
            return this;
        }

        public Criteria andCodigoAtencionIsNotNull() {
            addCriterion("codigo_atencion is not null");
            return this;
        }

        public Criteria andCodigoAtencionEqualTo(String value) {
            addCriterion("codigo_atencion =", value, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionNotEqualTo(String value) {
            addCriterion("codigo_atencion <>", value, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionGreaterThan(String value) {
            addCriterion("codigo_atencion >", value, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionGreaterThanOrEqualTo(String value) {
            addCriterion("codigo_atencion >=", value, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionLessThan(String value) {
            addCriterion("codigo_atencion <", value, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionLessThanOrEqualTo(String value) {
            addCriterion("codigo_atencion <=", value, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionLike(String value) {
            addCriterion("codigo_atencion like", value, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionNotLike(String value) {
            addCriterion("codigo_atencion not like", value, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionIn(List<String> values) {
            addCriterion("codigo_atencion in", values, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionNotIn(List<String> values) {
            addCriterion("codigo_atencion not in", values, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionBetween(String value1, String value2) {
            addCriterion("codigo_atencion between", value1, value2, "codigoAtencion");
            return this;
        }

        public Criteria andCodigoAtencionNotBetween(String value1, String value2) {
            addCriterion("codigo_atencion not between", value1, value2, "codigoAtencion");
            return this;
        }

        public Criteria andVentanillaIsNull() {
            addCriterion("ventanilla is null");
            return this;
        }

        public Criteria andVentanillaIsNotNull() {
            addCriterion("ventanilla is not null");
            return this;
        }

        public Criteria andVentanillaEqualTo(String value) {
            addCriterion("ventanilla =", value, "ventanilla");
            return this;
        }

        public Criteria andVentanillaNotEqualTo(String value) {
            addCriterion("ventanilla <>", value, "ventanilla");
            return this;
        }

        public Criteria andVentanillaGreaterThan(String value) {
            addCriterion("ventanilla >", value, "ventanilla");
            return this;
        }

        public Criteria andVentanillaGreaterThanOrEqualTo(String value) {
            addCriterion("ventanilla >=", value, "ventanilla");
            return this;
        }

        public Criteria andVentanillaLessThan(String value) {
            addCriterion("ventanilla <", value, "ventanilla");
            return this;
        }

        public Criteria andVentanillaLessThanOrEqualTo(String value) {
            addCriterion("ventanilla <=", value, "ventanilla");
            return this;
        }

        public Criteria andVentanillaLike(String value) {
            addCriterion("ventanilla like", value, "ventanilla");
            return this;
        }

        public Criteria andVentanillaNotLike(String value) {
            addCriterion("ventanilla not like", value, "ventanilla");
            return this;
        }

        public Criteria andVentanillaIn(List<String> values) {
            addCriterion("ventanilla in", values, "ventanilla");
            return this;
        }

        public Criteria andVentanillaNotIn(List<String> values) {
            addCriterion("ventanilla not in", values, "ventanilla");
            return this;
        }

        public Criteria andVentanillaBetween(String value1, String value2) {
            addCriterion("ventanilla between", value1, value2, "ventanilla");
            return this;
        }

        public Criteria andVentanillaNotBetween(String value1, String value2) {
            addCriterion("ventanilla not between", value1, value2, "ventanilla");
            return this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("estado =", value, "estado");
            return this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("estado <>", value, "estado");
            return this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("estado >", value, "estado");
            return this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("estado >=", value, "estado");
            return this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("estado <", value, "estado");
            return this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("estado <=", value, "estado");
            return this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("estado in", values, "estado");
            return this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("estado not in", values, "estado");
            return this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("estado between", value1, value2, "estado");
            return this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return this;
        }

        public Criteria andTipoIsNull() {
            addCriterion("tipo is null");
            return this;
        }

        public Criteria andTipoIsNotNull() {
            addCriterion("tipo is not null");
            return this;
        }

        public Criteria andTipoEqualTo(Integer value) {
            addCriterion("tipo =", value, "tipo");
            return this;
        }

        public Criteria andTipoNotEqualTo(Integer value) {
            addCriterion("tipo <>", value, "tipo");
            return this;
        }

        public Criteria andTipoGreaterThan(Integer value) {
            addCriterion("tipo >", value, "tipo");
            return this;
        }

        public Criteria andTipoGreaterThanOrEqualTo(Integer value) {
            addCriterion("tipo >=", value, "tipo");
            return this;
        }

        public Criteria andTipoLessThan(Integer value) {
            addCriterion("tipo <", value, "tipo");
            return this;
        }

        public Criteria andTipoLessThanOrEqualTo(Integer value) {
            addCriterion("tipo <=", value, "tipo");
            return this;
        }

        public Criteria andTipoIn(List<Integer> values) {
            addCriterion("tipo in", values, "tipo");
            return this;
        }

        public Criteria andTipoNotIn(List<Integer> values) {
            addCriterion("tipo not in", values, "tipo");
            return this;
        }

        public Criteria andTipoBetween(Integer value1, Integer value2) {
            addCriterion("tipo between", value1, value2, "tipo");
            return this;
        }

        public Criteria andTipoNotBetween(Integer value1, Integer value2) {
            addCriterion("tipo not between", value1, value2, "tipo");
            return this;
        }
    }
}