package pe.gob.ep.iclassq.negocio.bean;

public class Monitor {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_monitor.id
     *
     * @ibatorgenerated
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_monitor.codigo_atencion
     *
     * @ibatorgenerated
     */
    private String codigoAtencion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_monitor.ventanilla
     *
     * @ibatorgenerated
     */
    private String ventanilla;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_monitor.estado
     *
     * @ibatorgenerated
     */
    private Integer estado;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_monitor.tipo
     *
     * @ibatorgenerated
     */
    private Integer tipo;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_monitor.id
     *
     * @return the value of tbl_monitor.id
     *
     * @ibatorgenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_monitor.id
     *
     * @param id the value for tbl_monitor.id
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_monitor.codigo_atencion
     *
     * @return the value of tbl_monitor.codigo_atencion
     *
     * @ibatorgenerated
     */
    public String getCodigoAtencion() {
        return codigoAtencion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_monitor.codigo_atencion
     *
     * @param codigoAtencion the value for tbl_monitor.codigo_atencion
     *
     * @ibatorgenerated
     */
    public void setCodigoAtencion(String codigoAtencion) {
        this.codigoAtencion = codigoAtencion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_monitor.ventanilla
     *
     * @return the value of tbl_monitor.ventanilla
     *
     * @ibatorgenerated
     */
    public String getVentanilla() {
        return ventanilla;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_monitor.ventanilla
     *
     * @param ventanilla the value for tbl_monitor.ventanilla
     *
     * @ibatorgenerated
     */
    public void setVentanilla(String ventanilla) {
        this.ventanilla = ventanilla;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_monitor.estado
     *
     * @return the value of tbl_monitor.estado
     *
     * @ibatorgenerated
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_monitor.estado
     *
     * @param estado the value for tbl_monitor.estado
     *
     * @ibatorgenerated
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_monitor.tipo
     *
     * @return the value of tbl_monitor.tipo
     *
     * @ibatorgenerated
     */
    public Integer getTipo() {
        return tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_monitor.tipo
     *
     * @param tipo the value for tbl_monitor.tipo
     *
     * @ibatorgenerated
     */
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Monitor)) {
            return false;
        }
        Monitor other = (Monitor) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getCodigoAtencion() == null ? other == null : this.getCodigoAtencion().equals(other.getCodigoAtencion())
            && this.getVentanilla() == null ? other == null : this.getVentanilla().equals(other.getVentanilla())
            && this.getEstado() == null ? other == null : this.getEstado().equals(other.getEstado())
            && this.getTipo() == null ? other == null : this.getTipo().equals(other.getTipo());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getCodigoAtencion() != null) {
            hash *= getCodigoAtencion().hashCode();
        }
        if (getVentanilla() != null) {
            hash *= getVentanilla().hashCode();
        }
        if (getEstado() != null) {
            hash *= getEstado().hashCode();
        }
        if (getTipo() != null) {
            hash *= getTipo().hashCode();
        }
        return hash;
    }
}