package pe.gob.ep.iclassq.negocio.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ParametroCriteria {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public ParametroCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	protected ParametroCriteria(ParametroCriteria example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return this;
		}

		public Criteria andCodigoEqualTo(String value) {
			addCriterion("codigo =", value, "codigo");
			return this;
		}

		public Criteria andCodigoNotEqualTo(String value) {
			addCriterion("codigo <>", value, "codigo");
			return this;
		}

		public Criteria andCodigoGreaterThan(String value) {
			addCriterion("codigo >", value, "codigo");
			return this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(String value) {
			addCriterion("codigo >=", value, "codigo");
			return this;
		}

		public Criteria andCodigoLessThan(String value) {
			addCriterion("codigo <", value, "codigo");
			return this;
		}

		public Criteria andCodigoLessThanOrEqualTo(String value) {
			addCriterion("codigo <=", value, "codigo");
			return this;
		}

		public Criteria andCodigoLike(String value) {
			addCriterion("codigo like", value, "codigo");
			return this;
		}

		public Criteria andCodigoNotLike(String value) {
			addCriterion("codigo not like", value, "codigo");
			return this;
		}

		public Criteria andCodigoIn(List<String> values) {
			addCriterion("codigo in", values, "codigo");
			return this;
		}

		public Criteria andCodigoNotIn(List<String> values) {
			addCriterion("codigo not in", values, "codigo");
			return this;
		}

		public Criteria andCodigoBetween(String value1, String value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return this;
		}

		public Criteria andCodigoNotBetween(String value1, String value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return this;
		}

		public Criteria andDescripcionIsNull() {
			addCriterion("descripcion is null");
			return this;
		}

		public Criteria andDescripcionIsNotNull() {
			addCriterion("descripcion is not null");
			return this;
		}

		public Criteria andDescripcionEqualTo(String value) {
			addCriterion("descripcion =", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotEqualTo(String value) {
			addCriterion("descripcion <>", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThan(String value) {
			addCriterion("descripcion >", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
			addCriterion("descripcion >=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThan(String value) {
			addCriterion("descripcion <", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThanOrEqualTo(String value) {
			addCriterion("descripcion <=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLike(String value) {
			addCriterion("descripcion like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotLike(String value) {
			addCriterion("descripcion not like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionIn(List<String> values) {
			addCriterion("descripcion in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotIn(List<String> values) {
			addCriterion("descripcion not in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionBetween(String value1, String value2) {
			addCriterion("descripcion between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotBetween(String value1, String value2) {
			addCriterion("descripcion not between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andDescripcionLargaIsNull() {
			addCriterion("descripcion_larga is null");
			return this;
		}

		public Criteria andDescripcionLargaIsNotNull() {
			addCriterion("descripcion_larga is not null");
			return this;
		}

		public Criteria andDescripcionLargaEqualTo(String value) {
			addCriterion("descripcion_larga =", value, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaNotEqualTo(String value) {
			addCriterion("descripcion_larga <>", value, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaGreaterThan(String value) {
			addCriterion("descripcion_larga >", value, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaGreaterThanOrEqualTo(String value) {
			addCriterion("descripcion_larga >=", value, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaLessThan(String value) {
			addCriterion("descripcion_larga <", value, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaLessThanOrEqualTo(String value) {
			addCriterion("descripcion_larga <=", value, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaLike(String value) {
			addCriterion("descripcion_larga like", value, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaNotLike(String value) {
			addCriterion("descripcion_larga not like", value, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaIn(List<String> values) {
			addCriterion("descripcion_larga in", values, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaNotIn(List<String> values) {
			addCriterion("descripcion_larga not in", values, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaBetween(String value1, String value2) {
			addCriterion("descripcion_larga between", value1, value2, "descripcionLarga");
			return this;
		}

		public Criteria andDescripcionLargaNotBetween(String value1, String value2) {
			addCriterion("descripcion_larga not between", value1, value2, "descripcionLarga");
			return this;
		}

		public Criteria andValorIsNull() {
			addCriterion("valor is null");
			return this;
		}

		public Criteria andValorIsNotNull() {
			addCriterion("valor is not null");
			return this;
		}

		public Criteria andValorEqualTo(BigDecimal value) {
			addCriterion("valor =", value, "valor");
			return this;
		}

		public Criteria andValorNotEqualTo(BigDecimal value) {
			addCriterion("valor <>", value, "valor");
			return this;
		}

		public Criteria andValorGreaterThan(BigDecimal value) {
			addCriterion("valor >", value, "valor");
			return this;
		}

		public Criteria andValorGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("valor >=", value, "valor");
			return this;
		}

		public Criteria andValorLessThan(BigDecimal value) {
			addCriterion("valor <", value, "valor");
			return this;
		}

		public Criteria andValorLessThanOrEqualTo(BigDecimal value) {
			addCriterion("valor <=", value, "valor");
			return this;
		}

		public Criteria andValorIn(List<BigDecimal> values) {
			addCriterion("valor in", values, "valor");
			return this;
		}

		public Criteria andValorNotIn(List<BigDecimal> values) {
			addCriterion("valor not in", values, "valor");
			return this;
		}

		public Criteria andValorBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("valor between", value1, value2, "valor");
			return this;
		}

		public Criteria andValorNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("valor not between", value1, value2, "valor");
			return this;
		}

		public Criteria andEstadoIsNull() {
			addCriterion("estado is null");
			return this;
		}

		public Criteria andEstadoIsNotNull() {
			addCriterion("estado is not null");
			return this;
		}

		public Criteria andEstadoEqualTo(Integer value) {
			addCriterion("estado =", value, "estado");
			return this;
		}

		public Criteria andEstadoNotEqualTo(Integer value) {
			addCriterion("estado <>", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThan(Integer value) {
			addCriterion("estado >", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("estado >=", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThan(Integer value) {
			addCriterion("estado <", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThanOrEqualTo(Integer value) {
			addCriterion("estado <=", value, "estado");
			return this;
		}

		public Criteria andEstadoIn(List<Integer> values) {
			addCriterion("estado in", values, "estado");
			return this;
		}

		public Criteria andEstadoNotIn(List<Integer> values) {
			addCriterion("estado not in", values, "estado");
			return this;
		}

		public Criteria andEstadoBetween(Integer value1, Integer value2) {
			addCriterion("estado between", value1, value2, "estado");
			return this;
		}

		public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
			addCriterion("estado not between", value1, value2, "estado");
			return this;
		}
	}
}