package pe.gob.ep.iclassq.negocio.bean;

public class Prioridad {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_prioridad.id
     *
     * @ibatorgenerated
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_prioridad.descripcion
     *
     * @ibatorgenerated
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_prioridad.estado
     *
     * @ibatorgenerated
     */
    private Integer estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_prioridad.id
     *
     * @return the value of tbl_prioridad.id
     *
     * @ibatorgenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_prioridad.id
     *
     * @param id the value for tbl_prioridad.id
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_prioridad.descripcion
     *
     * @return the value of tbl_prioridad.descripcion
     *
     * @ibatorgenerated
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_prioridad.descripcion
     *
     * @param descripcion the value for tbl_prioridad.descripcion
     *
     * @ibatorgenerated
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_prioridad.estado
     *
     * @return the value of tbl_prioridad.estado
     *
     * @ibatorgenerated
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_prioridad.estado
     *
     * @param estado the value for tbl_prioridad.estado
     *
     * @ibatorgenerated
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Prioridad)) {
            return false;
        }
        Prioridad other = (Prioridad) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getDescripcion() == null ? other == null : this.getDescripcion().equals(other.getDescripcion())
            && this.getEstado() == null ? other == null : this.getEstado().equals(other.getEstado());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prioridad
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getDescripcion() != null) {
            hash *= getDescripcion().hashCode();
        }
        if (getEstado() != null) {
            hash *= getEstado().hashCode();
        }
        return hash;
    }
}