package pe.gob.ep.iclassq.negocio.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class ProyectoCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public ProyectoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    protected ProyectoCriteria(ProyectoCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_proyecto
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdProyectoIsNull() {
            addCriterion("id_proyecto is null");
            return this;
        }

        public Criteria andIdProyectoIsNotNull() {
            addCriterion("id_proyecto is not null");
            return this;
        }

        public Criteria andIdProyectoEqualTo(Integer value) {
            addCriterion("id_proyecto =", value, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoNotEqualTo(Integer value) {
            addCriterion("id_proyecto <>", value, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoGreaterThan(Integer value) {
            addCriterion("id_proyecto >", value, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_proyecto >=", value, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoLessThan(Integer value) {
            addCriterion("id_proyecto <", value, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoLessThanOrEqualTo(Integer value) {
            addCriterion("id_proyecto <=", value, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoIn(List<Integer> values) {
            addCriterion("id_proyecto in", values, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoNotIn(List<Integer> values) {
            addCriterion("id_proyecto not in", values, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoBetween(Integer value1, Integer value2) {
            addCriterion("id_proyecto between", value1, value2, "idProyecto");
            return this;
        }

        public Criteria andIdProyectoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_proyecto not between", value1, value2, "idProyecto");
            return this;
        }

        public Criteria andIdCategoriaIsNull() {
            addCriterion("id_categoria is null");
            return this;
        }

        public Criteria andIdCategoriaIsNotNull() {
            addCriterion("id_categoria is not null");
            return this;
        }

        public Criteria andIdCategoriaEqualTo(Integer value) {
            addCriterion("id_categoria =", value, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaNotEqualTo(Integer value) {
            addCriterion("id_categoria <>", value, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaGreaterThan(Integer value) {
            addCriterion("id_categoria >", value, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_categoria >=", value, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaLessThan(Integer value) {
            addCriterion("id_categoria <", value, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaLessThanOrEqualTo(Integer value) {
            addCriterion("id_categoria <=", value, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaIn(List<Integer> values) {
            addCriterion("id_categoria in", values, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaNotIn(List<Integer> values) {
            addCriterion("id_categoria not in", values, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaBetween(Integer value1, Integer value2) {
            addCriterion("id_categoria between", value1, value2, "idCategoria");
            return this;
        }

        public Criteria andIdCategoriaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_categoria not between", value1, value2, "idCategoria");
            return this;
        }

        public Criteria andRucIsNull() {
            addCriterion("ruc is null");
            return this;
        }

        public Criteria andRucIsNotNull() {
            addCriterion("ruc is not null");
            return this;
        }

        public Criteria andRucEqualTo(String value) {
            addCriterion("ruc =", value, "ruc");
            return this;
        }

        public Criteria andRucNotEqualTo(String value) {
            addCriterion("ruc <>", value, "ruc");
            return this;
        }

        public Criteria andRucGreaterThan(String value) {
            addCriterion("ruc >", value, "ruc");
            return this;
        }

        public Criteria andRucGreaterThanOrEqualTo(String value) {
            addCriterion("ruc >=", value, "ruc");
            return this;
        }

        public Criteria andRucLessThan(String value) {
            addCriterion("ruc <", value, "ruc");
            return this;
        }

        public Criteria andRucLessThanOrEqualTo(String value) {
            addCriterion("ruc <=", value, "ruc");
            return this;
        }

        public Criteria andRucLike(String value) {
            addCriterion("ruc like", value, "ruc");
            return this;
        }

        public Criteria andRucNotLike(String value) {
            addCriterion("ruc not like", value, "ruc");
            return this;
        }

        public Criteria andRucIn(List<String> values) {
            addCriterion("ruc in", values, "ruc");
            return this;
        }

        public Criteria andRucNotIn(List<String> values) {
            addCriterion("ruc not in", values, "ruc");
            return this;
        }

        public Criteria andRucBetween(String value1, String value2) {
            addCriterion("ruc between", value1, value2, "ruc");
            return this;
        }

        public Criteria andRucNotBetween(String value1, String value2) {
            addCriterion("ruc not between", value1, value2, "ruc");
            return this;
        }

        public Criteria andRazonSocialIsNull() {
            addCriterion("razon_social is null");
            return this;
        }

        public Criteria andRazonSocialIsNotNull() {
            addCriterion("razon_social is not null");
            return this;
        }

        public Criteria andRazonSocialEqualTo(String value) {
            addCriterion("razon_social =", value, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialNotEqualTo(String value) {
            addCriterion("razon_social <>", value, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialGreaterThan(String value) {
            addCriterion("razon_social >", value, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialGreaterThanOrEqualTo(String value) {
            addCriterion("razon_social >=", value, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialLessThan(String value) {
            addCriterion("razon_social <", value, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialLessThanOrEqualTo(String value) {
            addCriterion("razon_social <=", value, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialLike(String value) {
            addCriterion("razon_social like", value, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialNotLike(String value) {
            addCriterion("razon_social not like", value, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialIn(List<String> values) {
            addCriterion("razon_social in", values, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialNotIn(List<String> values) {
            addCriterion("razon_social not in", values, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialBetween(String value1, String value2) {
            addCriterion("razon_social between", value1, value2, "razonSocial");
            return this;
        }

        public Criteria andRazonSocialNotBetween(String value1, String value2) {
            addCriterion("razon_social not between", value1, value2, "razonSocial");
            return this;
        }

        public Criteria andPresupuestoIsNull() {
            addCriterion("presupuesto is null");
            return this;
        }

        public Criteria andPresupuestoIsNotNull() {
            addCriterion("presupuesto is not null");
            return this;
        }

        public Criteria andPresupuestoEqualTo(String value) {
            addCriterion("presupuesto =", value, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoNotEqualTo(String value) {
            addCriterion("presupuesto <>", value, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoGreaterThan(String value) {
            addCriterion("presupuesto >", value, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoGreaterThanOrEqualTo(String value) {
            addCriterion("presupuesto >=", value, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoLessThan(String value) {
            addCriterion("presupuesto <", value, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoLessThanOrEqualTo(String value) {
            addCriterion("presupuesto <=", value, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoLike(String value) {
            addCriterion("presupuesto like", value, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoNotLike(String value) {
            addCriterion("presupuesto not like", value, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoIn(List<String> values) {
            addCriterion("presupuesto in", values, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoNotIn(List<String> values) {
            addCriterion("presupuesto not in", values, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoBetween(String value1, String value2) {
            addCriterion("presupuesto between", value1, value2, "presupuesto");
            return this;
        }

        public Criteria andPresupuestoNotBetween(String value1, String value2) {
            addCriterion("presupuesto not between", value1, value2, "presupuesto");
            return this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("nombre is null");
            return this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("nombre is not null");
            return this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("nombre =", value, "nombre");
            return this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("nombre <>", value, "nombre");
            return this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("nombre >", value, "nombre");
            return this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("nombre >=", value, "nombre");
            return this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("nombre <", value, "nombre");
            return this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("nombre <=", value, "nombre");
            return this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("nombre like", value, "nombre");
            return this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("nombre not like", value, "nombre");
            return this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("nombre in", values, "nombre");
            return this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("nombre not in", values, "nombre");
            return this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("nombre between", value1, value2, "nombre");
            return this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("nombre not between", value1, value2, "nombre");
            return this;
        }

        public Criteria andFechaInicioIsNull() {
            addCriterion("fecha_inicio is null");
            return this;
        }

        public Criteria andFechaInicioIsNotNull() {
            addCriterion("fecha_inicio is not null");
            return this;
        }

        public Criteria andFechaInicioEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio =", value, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio <>", value, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha_inicio >", value, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio >=", value, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioLessThan(Date value) {
            addCriterionForJDBCDate("fecha_inicio <", value, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha_inicio <=", value, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_inicio in", values, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha_inicio not in", values, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_inicio between", value1, value2, "fechaInicio");
            return this;
        }

        public Criteria andFechaInicioNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha_inicio not between", value1, value2, "fechaInicio");
            return this;
        }

        public Criteria andOrigenIsNull() {
            addCriterion("origen is null");
            return this;
        }

        public Criteria andOrigenIsNotNull() {
            addCriterion("origen is not null");
            return this;
        }

        public Criteria andOrigenEqualTo(String value) {
            addCriterion("origen =", value, "origen");
            return this;
        }

        public Criteria andOrigenNotEqualTo(String value) {
            addCriterion("origen <>", value, "origen");
            return this;
        }

        public Criteria andOrigenGreaterThan(String value) {
            addCriterion("origen >", value, "origen");
            return this;
        }

        public Criteria andOrigenGreaterThanOrEqualTo(String value) {
            addCriterion("origen >=", value, "origen");
            return this;
        }

        public Criteria andOrigenLessThan(String value) {
            addCriterion("origen <", value, "origen");
            return this;
        }

        public Criteria andOrigenLessThanOrEqualTo(String value) {
            addCriterion("origen <=", value, "origen");
            return this;
        }

        public Criteria andOrigenLike(String value) {
            addCriterion("origen like", value, "origen");
            return this;
        }

        public Criteria andOrigenNotLike(String value) {
            addCriterion("origen not like", value, "origen");
            return this;
        }

        public Criteria andOrigenIn(List<String> values) {
            addCriterion("origen in", values, "origen");
            return this;
        }

        public Criteria andOrigenNotIn(List<String> values) {
            addCriterion("origen not in", values, "origen");
            return this;
        }

        public Criteria andOrigenBetween(String value1, String value2) {
            addCriterion("origen between", value1, value2, "origen");
            return this;
        }

        public Criteria andOrigenNotBetween(String value1, String value2) {
            addCriterion("origen not between", value1, value2, "origen");
            return this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("estado =", value, "estado");
            return this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("estado <>", value, "estado");
            return this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("estado >", value, "estado");
            return this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("estado >=", value, "estado");
            return this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("estado <", value, "estado");
            return this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("estado <=", value, "estado");
            return this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("estado in", values, "estado");
            return this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("estado not in", values, "estado");
            return this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("estado between", value1, value2, "estado");
            return this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return this;
        }

        public Criteria andTipoIsNull() {
            addCriterion("tipo is null");
            return this;
        }

        public Criteria andTipoIsNotNull() {
            addCriterion("tipo is not null");
            return this;
        }

        public Criteria andTipoEqualTo(Integer value) {
            addCriterion("tipo =", value, "tipo");
            return this;
        }

        public Criteria andTipoNotEqualTo(Integer value) {
            addCriterion("tipo <>", value, "tipo");
            return this;
        }

        public Criteria andTipoGreaterThan(Integer value) {
            addCriterion("tipo >", value, "tipo");
            return this;
        }

        public Criteria andTipoGreaterThanOrEqualTo(Integer value) {
            addCriterion("tipo >=", value, "tipo");
            return this;
        }

        public Criteria andTipoLessThan(Integer value) {
            addCriterion("tipo <", value, "tipo");
            return this;
        }

        public Criteria andTipoLessThanOrEqualTo(Integer value) {
            addCriterion("tipo <=", value, "tipo");
            return this;
        }

        public Criteria andTipoIn(List<Integer> values) {
            addCriterion("tipo in", values, "tipo");
            return this;
        }

        public Criteria andTipoNotIn(List<Integer> values) {
            addCriterion("tipo not in", values, "tipo");
            return this;
        }

        public Criteria andTipoBetween(Integer value1, Integer value2) {
            addCriterion("tipo between", value1, value2, "tipo");
            return this;
        }

        public Criteria andTipoNotBetween(Integer value1, Integer value2) {
            addCriterion("tipo not between", value1, value2, "tipo");
            return this;
        }

        public Criteria andFechaCreaIsNull() {
            addCriterion("fecha_crea is null");
            return this;
        }

        public Criteria andFechaCreaIsNotNull() {
            addCriterion("fecha_crea is not null");
            return this;
        }

        public Criteria andFechaCreaEqualTo(Date value) {
            addCriterion("fecha_crea =", value, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaNotEqualTo(Date value) {
            addCriterion("fecha_crea <>", value, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaGreaterThan(Date value) {
            addCriterion("fecha_crea >", value, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_crea >=", value, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaLessThan(Date value) {
            addCriterion("fecha_crea <", value, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaLessThanOrEqualTo(Date value) {
            addCriterion("fecha_crea <=", value, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaIn(List<Date> values) {
            addCriterion("fecha_crea in", values, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaNotIn(List<Date> values) {
            addCriterion("fecha_crea not in", values, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaBetween(Date value1, Date value2) {
            addCriterion("fecha_crea between", value1, value2, "fechaCrea");
            return this;
        }

        public Criteria andFechaCreaNotBetween(Date value1, Date value2) {
            addCriterion("fecha_crea not between", value1, value2, "fechaCrea");
            return this;
        }

        public Criteria andFechaModIsNull() {
            addCriterion("fecha_mod is null");
            return this;
        }

        public Criteria andFechaModIsNotNull() {
            addCriterion("fecha_mod is not null");
            return this;
        }

        public Criteria andFechaModEqualTo(Date value) {
            addCriterion("fecha_mod =", value, "fechaMod");
            return this;
        }

        public Criteria andFechaModNotEqualTo(Date value) {
            addCriterion("fecha_mod <>", value, "fechaMod");
            return this;
        }

        public Criteria andFechaModGreaterThan(Date value) {
            addCriterion("fecha_mod >", value, "fechaMod");
            return this;
        }

        public Criteria andFechaModGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_mod >=", value, "fechaMod");
            return this;
        }

        public Criteria andFechaModLessThan(Date value) {
            addCriterion("fecha_mod <", value, "fechaMod");
            return this;
        }

        public Criteria andFechaModLessThanOrEqualTo(Date value) {
            addCriterion("fecha_mod <=", value, "fechaMod");
            return this;
        }

        public Criteria andFechaModIn(List<Date> values) {
            addCriterion("fecha_mod in", values, "fechaMod");
            return this;
        }

        public Criteria andFechaModNotIn(List<Date> values) {
            addCriterion("fecha_mod not in", values, "fechaMod");
            return this;
        }

        public Criteria andFechaModBetween(Date value1, Date value2) {
            addCriterion("fecha_mod between", value1, value2, "fechaMod");
            return this;
        }

        public Criteria andFechaModNotBetween(Date value1, Date value2) {
            addCriterion("fecha_mod not between", value1, value2, "fechaMod");
            return this;
        }

        public Criteria andIpCreaIsNull() {
            addCriterion("ip_crea is null");
            return this;
        }

        public Criteria andIpCreaIsNotNull() {
            addCriterion("ip_crea is not null");
            return this;
        }

        public Criteria andIpCreaEqualTo(String value) {
            addCriterion("ip_crea =", value, "ipCrea");
            return this;
        }

        public Criteria andIpCreaNotEqualTo(String value) {
            addCriterion("ip_crea <>", value, "ipCrea");
            return this;
        }

        public Criteria andIpCreaGreaterThan(String value) {
            addCriterion("ip_crea >", value, "ipCrea");
            return this;
        }

        public Criteria andIpCreaGreaterThanOrEqualTo(String value) {
            addCriterion("ip_crea >=", value, "ipCrea");
            return this;
        }

        public Criteria andIpCreaLessThan(String value) {
            addCriterion("ip_crea <", value, "ipCrea");
            return this;
        }

        public Criteria andIpCreaLessThanOrEqualTo(String value) {
            addCriterion("ip_crea <=", value, "ipCrea");
            return this;
        }

        public Criteria andIpCreaLike(String value) {
            addCriterion("ip_crea like", value, "ipCrea");
            return this;
        }

        public Criteria andIpCreaNotLike(String value) {
            addCriterion("ip_crea not like", value, "ipCrea");
            return this;
        }

        public Criteria andIpCreaIn(List<String> values) {
            addCriterion("ip_crea in", values, "ipCrea");
            return this;
        }

        public Criteria andIpCreaNotIn(List<String> values) {
            addCriterion("ip_crea not in", values, "ipCrea");
            return this;
        }

        public Criteria andIpCreaBetween(String value1, String value2) {
            addCriterion("ip_crea between", value1, value2, "ipCrea");
            return this;
        }

        public Criteria andIpCreaNotBetween(String value1, String value2) {
            addCriterion("ip_crea not between", value1, value2, "ipCrea");
            return this;
        }

        public Criteria andIpModificaIsNull() {
            addCriterion("ip_modifica is null");
            return this;
        }

        public Criteria andIpModificaIsNotNull() {
            addCriterion("ip_modifica is not null");
            return this;
        }

        public Criteria andIpModificaEqualTo(String value) {
            addCriterion("ip_modifica =", value, "ipModifica");
            return this;
        }

        public Criteria andIpModificaNotEqualTo(String value) {
            addCriterion("ip_modifica <>", value, "ipModifica");
            return this;
        }

        public Criteria andIpModificaGreaterThan(String value) {
            addCriterion("ip_modifica >", value, "ipModifica");
            return this;
        }

        public Criteria andIpModificaGreaterThanOrEqualTo(String value) {
            addCriterion("ip_modifica >=", value, "ipModifica");
            return this;
        }

        public Criteria andIpModificaLessThan(String value) {
            addCriterion("ip_modifica <", value, "ipModifica");
            return this;
        }

        public Criteria andIpModificaLessThanOrEqualTo(String value) {
            addCriterion("ip_modifica <=", value, "ipModifica");
            return this;
        }

        public Criteria andIpModificaLike(String value) {
            addCriterion("ip_modifica like", value, "ipModifica");
            return this;
        }

        public Criteria andIpModificaNotLike(String value) {
            addCriterion("ip_modifica not like", value, "ipModifica");
            return this;
        }

        public Criteria andIpModificaIn(List<String> values) {
            addCriterion("ip_modifica in", values, "ipModifica");
            return this;
        }

        public Criteria andIpModificaNotIn(List<String> values) {
            addCriterion("ip_modifica not in", values, "ipModifica");
            return this;
        }

        public Criteria andIpModificaBetween(String value1, String value2) {
            addCriterion("ip_modifica between", value1, value2, "ipModifica");
            return this;
        }

        public Criteria andIpModificaNotBetween(String value1, String value2) {
            addCriterion("ip_modifica not between", value1, value2, "ipModifica");
            return this;
        }
    }
}