package pe.gob.ep.iclassq.negocio.bean;

import java.util.Date;

public class Publicidad {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.id
	 * @ibatorgenerated
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.tipo_publicidad
	 * @ibatorgenerated
	 */
	private String tipoPublicidad;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.pub_texto
	 * @ibatorgenerated
	 */
	private String pubTexto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.secuencia_texto
	 * @ibatorgenerated
	 */
	private Integer secuenciaTexto;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.url_video
	 * @ibatorgenerated
	 */
	private String urlVideo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.tipo_video
	 * @ibatorgenerated
	 */
	private String tipoVideo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.secuencia_video
	 * @ibatorgenerated
	 */
	private Integer secuenciaVideo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.fecha_inicio
	 * @ibatorgenerated
	 */
	private Date fechaInicio;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.fecha_fin
	 * @ibatorgenerated
	 */
	private Date fechaFin;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.estado
	 * @ibatorgenerated
	 */
	private Integer estado;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_publicidad.id_sucursal
	 * @ibatorgenerated
	 */
	private Integer idSucursal;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.id
	 * @return  the value of tbl_publicidad.id
	 * @ibatorgenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.id
	 * @param id  the value for tbl_publicidad.id
	 * @ibatorgenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.tipo_publicidad
	 * @return  the value of tbl_publicidad.tipo_publicidad
	 * @ibatorgenerated
	 */
	public String getTipoPublicidad() {
		return tipoPublicidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.tipo_publicidad
	 * @param tipoPublicidad  the value for tbl_publicidad.tipo_publicidad
	 * @ibatorgenerated
	 */
	public void setTipoPublicidad(String tipoPublicidad) {
		this.tipoPublicidad = tipoPublicidad;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.pub_texto
	 * @return  the value of tbl_publicidad.pub_texto
	 * @ibatorgenerated
	 */
	public String getPubTexto() {
		return pubTexto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.pub_texto
	 * @param pubTexto  the value for tbl_publicidad.pub_texto
	 * @ibatorgenerated
	 */
	public void setPubTexto(String pubTexto) {
		this.pubTexto = pubTexto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.secuencia_texto
	 * @return  the value of tbl_publicidad.secuencia_texto
	 * @ibatorgenerated
	 */
	public Integer getSecuenciaTexto() {
		return secuenciaTexto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.secuencia_texto
	 * @param secuenciaTexto  the value for tbl_publicidad.secuencia_texto
	 * @ibatorgenerated
	 */
	public void setSecuenciaTexto(Integer secuenciaTexto) {
		this.secuenciaTexto = secuenciaTexto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.url_video
	 * @return  the value of tbl_publicidad.url_video
	 * @ibatorgenerated
	 */
	public String getUrlVideo() {
		return urlVideo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.url_video
	 * @param urlVideo  the value for tbl_publicidad.url_video
	 * @ibatorgenerated
	 */
	public void setUrlVideo(String urlVideo) {
		this.urlVideo = urlVideo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.tipo_video
	 * @return  the value of tbl_publicidad.tipo_video
	 * @ibatorgenerated
	 */
	public String getTipoVideo() {
		return tipoVideo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.tipo_video
	 * @param tipoVideo  the value for tbl_publicidad.tipo_video
	 * @ibatorgenerated
	 */
	public void setTipoVideo(String tipoVideo) {
		this.tipoVideo = tipoVideo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.secuencia_video
	 * @return  the value of tbl_publicidad.secuencia_video
	 * @ibatorgenerated
	 */
	public Integer getSecuenciaVideo() {
		return secuenciaVideo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.secuencia_video
	 * @param secuenciaVideo  the value for tbl_publicidad.secuencia_video
	 * @ibatorgenerated
	 */
	public void setSecuenciaVideo(Integer secuenciaVideo) {
		this.secuenciaVideo = secuenciaVideo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.fecha_inicio
	 * @return  the value of tbl_publicidad.fecha_inicio
	 * @ibatorgenerated
	 */
	public Date getFechaInicio() {
		return fechaInicio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.fecha_inicio
	 * @param fechaInicio  the value for tbl_publicidad.fecha_inicio
	 * @ibatorgenerated
	 */
	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.fecha_fin
	 * @return  the value of tbl_publicidad.fecha_fin
	 * @ibatorgenerated
	 */
	public Date getFechaFin() {
		return fechaFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.fecha_fin
	 * @param fechaFin  the value for tbl_publicidad.fecha_fin
	 * @ibatorgenerated
	 */
	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.estado
	 * @return  the value of tbl_publicidad.estado
	 * @ibatorgenerated
	 */
	public Integer getEstado() {
		return estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.estado
	 * @param estado  the value for tbl_publicidad.estado
	 * @ibatorgenerated
	 */
	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_publicidad.id_sucursal
	 * @return  the value of tbl_publicidad.id_sucursal
	 * @ibatorgenerated
	 */
	public Integer getIdSucursal() {
		return idSucursal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_publicidad.id_sucursal
	 * @param idSucursal  the value for tbl_publicidad.id_sucursal
	 * @ibatorgenerated
	 */
	public void setIdSucursal(Integer idSucursal) {
		this.idSucursal = idSucursal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof Publicidad)) {
			return false;
		}
		Publicidad other = (Publicidad) that;
		return this.getId() == null ? other == null
				: this.getId().equals(other.getId()) && this.getTipoPublicidad() == null ? other == null
						: this.getTipoPublicidad().equals(other.getTipoPublicidad()) && this.getPubTexto() == null
								? other == null
								: this.getPubTexto().equals(other.getPubTexto()) && this.getSecuenciaTexto() == null
										? other == null
										: this.getSecuenciaTexto().equals(other.getSecuenciaTexto())
												&& this.getUrlVideo() == null
														? other == null
														: this.getUrlVideo().equals(other.getUrlVideo())
																&& this.getTipoVideo() == null
																		? other == null
																		: this.getTipoVideo()
																				.equals(other.getTipoVideo())
																				&& this.getSecuenciaVideo() == null
																						? other == null
																						: this.getSecuenciaVideo()
																								.equals(other
																										.getSecuenciaVideo())
																								&& this.getFechaInicio() == null
																										? other == null
																										: this.getFechaInicio()
																												.equals(other
																														.getFechaInicio())
																												&& this.getFechaFin() == null
																														? other == null
																														: this.getFechaFin()
																																.equals(other
																																		.getFechaFin())
																																&& this.getEstado() == null
																																		? other == null
																																		: this.getEstado()
																																				.equals(other
																																						.getEstado())
																																				&& this.getIdSucursal() == null
																																						? other == null
																																						: this.getIdSucursal()
																																								.equals(other
																																										.getIdSucursal());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getTipoPublicidad() != null) {
			hash *= getTipoPublicidad().hashCode();
		}
		if (getPubTexto() != null) {
			hash *= getPubTexto().hashCode();
		}
		if (getSecuenciaTexto() != null) {
			hash *= getSecuenciaTexto().hashCode();
		}
		if (getUrlVideo() != null) {
			hash *= getUrlVideo().hashCode();
		}
		if (getTipoVideo() != null) {
			hash *= getTipoVideo().hashCode();
		}
		if (getSecuenciaVideo() != null) {
			hash *= getSecuenciaVideo().hashCode();
		}
		if (getFechaInicio() != null) {
			hash *= getFechaInicio().hashCode();
		}
		if (getFechaFin() != null) {
			hash *= getFechaFin().hashCode();
		}
		if (getEstado() != null) {
			hash *= getEstado().hashCode();
		}
		if (getIdSucursal() != null) {
			hash *= getIdSucursal().hashCode();
		}
		return hash;
	}
}