package pe.gob.ep.iclassq.negocio.bean;
import java.math.BigDecimal;
public class RolEquipoSubGrupo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_rol_equipo_subgrupo.id
     *
     * @ibatorgenerated
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_rol_equipo_subgrupo.id_rol_equipo
     *
     * @ibatorgenerated
     */
    private Integer idRolEquipo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_rol_equipo_subgrupo.id_subgrupo
     *
     * @ibatorgenerated
     */
    private Integer idSubgrupo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_rol_equipo_subgrupo.proporcion
     *
     * @ibatorgenerated
     */
    private BigDecimal proporcion;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_rol_equipo_subgrupo.id
     *
     * @return the value of tbl_rol_equipo_subgrupo.id
     *
     * @ibatorgenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_rol_equipo_subgrupo.id
     *
     * @param id the value for tbl_rol_equipo_subgrupo.id
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_rol_equipo_subgrupo.id_rol_equipo
     *
     * @return the value of tbl_rol_equipo_subgrupo.id_rol_equipo
     *
     * @ibatorgenerated
     */
    public Integer getIdRolEquipo() {
        return idRolEquipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_rol_equipo_subgrupo.id_rol_equipo
     *
     * @param idRolEquipo the value for tbl_rol_equipo_subgrupo.id_rol_equipo
     *
     * @ibatorgenerated
     */
    public void setIdRolEquipo(Integer idRolEquipo) {
        this.idRolEquipo = idRolEquipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_rol_equipo_subgrupo.id_subgrupo
     *
     * @return the value of tbl_rol_equipo_subgrupo.id_subgrupo
     *
     * @ibatorgenerated
     */
    public Integer getIdSubgrupo() {
        return idSubgrupo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_rol_equipo_subgrupo.id_subgrupo
     *
     * @param idSubgrupo the value for tbl_rol_equipo_subgrupo.id_subgrupo
     *
     * @ibatorgenerated
     */
    public void setIdSubgrupo(Integer idSubgrupo) {
        this.idSubgrupo = idSubgrupo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_rol_equipo_subgrupo.proporcion
     *
     * @return the value of tbl_rol_equipo_subgrupo.proporcion
     *
     * @ibatorgenerated
     */
    public BigDecimal getProporcion() {
        return proporcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_rol_equipo_subgrupo.proporcion
     *
     * @param proporcion the value for tbl_rol_equipo_subgrupo.proporcion
     *
     * @ibatorgenerated
     */
    public void setProporcion(BigDecimal proporcion) {
        this.proporcion = proporcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof RolEquipoSubGrupo)) {
            return false;
        }
        RolEquipoSubGrupo other = (RolEquipoSubGrupo) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getIdRolEquipo() == null ? other == null : this.getIdRolEquipo().equals(other.getIdRolEquipo())
            && this.getIdSubgrupo() == null ? other == null : this.getIdSubgrupo().equals(other.getIdSubgrupo())
            && this.getProporcion() == null ? other == null : this.getProporcion().equals(other.getProporcion());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getIdRolEquipo() != null) {
            hash *= getIdRolEquipo().hashCode();
        }
        if (getIdSubgrupo() != null) {
            hash *= getIdSubgrupo().hashCode();
        }
        if (getProporcion() != null) {
            hash *= getProporcion().hashCode();
        }
        return hash;
    }
    
    private String nombreSubGrupo;
    private String prefijoSubGrupo;
    private String horaInicio;
    private String horaFin;

	public String getNombreSubGrupo() {
		return nombreSubGrupo;
	}

	public void setNombreSubGrupo(String nombreSubGrupo) {
		this.nombreSubGrupo = nombreSubGrupo;
	}

	public String getPrefijoSubGrupo() {
		return prefijoSubGrupo;
	}

	public void setPrefijoSubGrupo(String prefijoSubGrupo) {
		this.prefijoSubGrupo = prefijoSubGrupo;
	}

	public String getHoraInicio() {
		return horaInicio;
	}

	public void setHoraInicio(String horaInicio) {
		this.horaInicio = horaInicio;
	}

	public String getHoraFin() {
		return horaFin;
	}

	public void setHoraFin(String horaFin) {
		this.horaFin = horaFin;
	}
	
}