package pe.gob.ep.iclassq.negocio.bean;

import java.util.Date;

public class Ticket {
    /**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.id
	 * @ibatorgenerated
	 */
	private Integer id;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.codigo
	 * @ibatorgenerated
	 */
	private String codigo;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.id_sucursal
	 * @ibatorgenerated
	 */
	private Integer idSucursal;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.hora_emision
	 * @ibatorgenerated
	 */
	private Date horaEmision;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.hora_inicio_atencion
	 * @ibatorgenerated
	 */
	private Date horaInicioAtencion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.hora_fin_atencion
	 * @ibatorgenerated
	 */
	private Date horaFinAtencion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.id_subgrupo
	 * @ibatorgenerated
	 */
	private Integer idSubgrupo;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.hora_inicio_reactivacion
	 * @ibatorgenerated
	 */
	private Date horaInicioReactivacion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.hora_fin_reactivacion
	 * @ibatorgenerated
	 */
	private Date horaFinReactivacion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.fecha_hora_prog_alg_2_tiempo
	 * @ibatorgenerated
	 */
	private Date fechaHoraProgAlg2Tiempo;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.estado
	 * @ibatorgenerated
	 */
	private Integer estado;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.secuencia_algo_3_proporcion
	 * @ibatorgenerated
	 */
	private Integer secuenciaAlgo3Proporcion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.id_ticket_derivado
	 * @ibatorgenerated
	 */
	private Integer idTicketDerivado;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.nombre_subgrupo
	 * @ibatorgenerated
	 */
	private String nombreSubgrupo;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.prefijo
	 * @ibatorgenerated
	 */
	private String prefijo;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.id_ventanilla_derivacion
	 * @ibatorgenerated
	 */
	private Integer idVentanillaDerivacion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.activa_audio_texto
	 * @ibatorgenerated
	 */
	private Integer activaAudioTexto;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.tipo_identificacion
	 * @ibatorgenerated
	 */
	private Integer tipoIdentificacion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.numero_identificacion
	 * @ibatorgenerated
	 */
	private String numeroIdentificacion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.descripcion
	 * @ibatorgenerated
	 */
	private String descripcion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.ventanilla_id_usuario
	 * @ibatorgenerated
	 */
	private Integer ventanillaIdUsuario;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.ticket_secuencia
	 * @ibatorgenerated
	 */
	private Integer ticketSecuencia;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.envia_audio
	 * @ibatorgenerated
	 */
	private Integer enviaAudio;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.ventanilla_caja
	 * @ibatorgenerated
	 */
	private Integer ventanillaCaja;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.evaluacion
	 * @ibatorgenerated
	 */
	private Integer evaluacion;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column tbl_ticket.fecha_atencion
	 * @ibatorgenerated
	 */
	private Date fechaAtencion;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.id
	 * @return  the value of tbl_ticket.id
	 * @ibatorgenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.id
	 * @param id  the value for tbl_ticket.id
	 * @ibatorgenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.codigo
	 * @return  the value of tbl_ticket.codigo
	 * @ibatorgenerated
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.codigo
	 * @param codigo  the value for tbl_ticket.codigo
	 * @ibatorgenerated
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.id_sucursal
	 * @return  the value of tbl_ticket.id_sucursal
	 * @ibatorgenerated
	 */
	public Integer getIdSucursal() {
		return idSucursal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.id_sucursal
	 * @param idSucursal  the value for tbl_ticket.id_sucursal
	 * @ibatorgenerated
	 */
	public void setIdSucursal(Integer idSucursal) {
		this.idSucursal = idSucursal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.hora_emision
	 * @return  the value of tbl_ticket.hora_emision
	 * @ibatorgenerated
	 */
	public Date getHoraEmision() {
		return horaEmision;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.hora_emision
	 * @param horaEmision  the value for tbl_ticket.hora_emision
	 * @ibatorgenerated
	 */
	public void setHoraEmision(Date horaEmision) {
		this.horaEmision = horaEmision;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.hora_inicio_atencion
	 * @return  the value of tbl_ticket.hora_inicio_atencion
	 * @ibatorgenerated
	 */
	public Date getHoraInicioAtencion() {
		return horaInicioAtencion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.hora_inicio_atencion
	 * @param horaInicioAtencion  the value for tbl_ticket.hora_inicio_atencion
	 * @ibatorgenerated
	 */
	public void setHoraInicioAtencion(Date horaInicioAtencion) {
		this.horaInicioAtencion = horaInicioAtencion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.hora_fin_atencion
	 * @return  the value of tbl_ticket.hora_fin_atencion
	 * @ibatorgenerated
	 */
	public Date getHoraFinAtencion() {
		return horaFinAtencion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.hora_fin_atencion
	 * @param horaFinAtencion  the value for tbl_ticket.hora_fin_atencion
	 * @ibatorgenerated
	 */
	public void setHoraFinAtencion(Date horaFinAtencion) {
		this.horaFinAtencion = horaFinAtencion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.id_subgrupo
	 * @return  the value of tbl_ticket.id_subgrupo
	 * @ibatorgenerated
	 */
	public Integer getIdSubgrupo() {
		return idSubgrupo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.id_subgrupo
	 * @param idSubgrupo  the value for tbl_ticket.id_subgrupo
	 * @ibatorgenerated
	 */
	public void setIdSubgrupo(Integer idSubgrupo) {
		this.idSubgrupo = idSubgrupo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.hora_inicio_reactivacion
	 * @return  the value of tbl_ticket.hora_inicio_reactivacion
	 * @ibatorgenerated
	 */
	public Date getHoraInicioReactivacion() {
		return horaInicioReactivacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.hora_inicio_reactivacion
	 * @param horaInicioReactivacion  the value for tbl_ticket.hora_inicio_reactivacion
	 * @ibatorgenerated
	 */
	public void setHoraInicioReactivacion(Date horaInicioReactivacion) {
		this.horaInicioReactivacion = horaInicioReactivacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.hora_fin_reactivacion
	 * @return  the value of tbl_ticket.hora_fin_reactivacion
	 * @ibatorgenerated
	 */
	public Date getHoraFinReactivacion() {
		return horaFinReactivacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.hora_fin_reactivacion
	 * @param horaFinReactivacion  the value for tbl_ticket.hora_fin_reactivacion
	 * @ibatorgenerated
	 */
	public void setHoraFinReactivacion(Date horaFinReactivacion) {
		this.horaFinReactivacion = horaFinReactivacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.fecha_hora_prog_alg_2_tiempo
	 * @return  the value of tbl_ticket.fecha_hora_prog_alg_2_tiempo
	 * @ibatorgenerated
	 */
	public Date getFechaHoraProgAlg2Tiempo() {
		return fechaHoraProgAlg2Tiempo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.fecha_hora_prog_alg_2_tiempo
	 * @param fechaHoraProgAlg2Tiempo  the value for tbl_ticket.fecha_hora_prog_alg_2_tiempo
	 * @ibatorgenerated
	 */
	public void setFechaHoraProgAlg2Tiempo(Date fechaHoraProgAlg2Tiempo) {
		this.fechaHoraProgAlg2Tiempo = fechaHoraProgAlg2Tiempo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.estado
	 * @return  the value of tbl_ticket.estado
	 * @ibatorgenerated
	 */
	public Integer getEstado() {
		return estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.estado
	 * @param estado  the value for tbl_ticket.estado
	 * @ibatorgenerated
	 */
	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.secuencia_algo_3_proporcion
	 * @return  the value of tbl_ticket.secuencia_algo_3_proporcion
	 * @ibatorgenerated
	 */
	public Integer getSecuenciaAlgo3Proporcion() {
		return secuenciaAlgo3Proporcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.secuencia_algo_3_proporcion
	 * @param secuenciaAlgo3Proporcion  the value for tbl_ticket.secuencia_algo_3_proporcion
	 * @ibatorgenerated
	 */
	public void setSecuenciaAlgo3Proporcion(Integer secuenciaAlgo3Proporcion) {
		this.secuenciaAlgo3Proporcion = secuenciaAlgo3Proporcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.id_ticket_derivado
	 * @return  the value of tbl_ticket.id_ticket_derivado
	 * @ibatorgenerated
	 */
	public Integer getIdTicketDerivado() {
		return idTicketDerivado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.id_ticket_derivado
	 * @param idTicketDerivado  the value for tbl_ticket.id_ticket_derivado
	 * @ibatorgenerated
	 */
	public void setIdTicketDerivado(Integer idTicketDerivado) {
		this.idTicketDerivado = idTicketDerivado;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.nombre_subgrupo
	 * @return  the value of tbl_ticket.nombre_subgrupo
	 * @ibatorgenerated
	 */
	public String getNombreSubgrupo() {
		return nombreSubgrupo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.nombre_subgrupo
	 * @param nombreSubgrupo  the value for tbl_ticket.nombre_subgrupo
	 * @ibatorgenerated
	 */
	public void setNombreSubgrupo(String nombreSubgrupo) {
		this.nombreSubgrupo = nombreSubgrupo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.prefijo
	 * @return  the value of tbl_ticket.prefijo
	 * @ibatorgenerated
	 */
	public String getPrefijo() {
		return prefijo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.prefijo
	 * @param prefijo  the value for tbl_ticket.prefijo
	 * @ibatorgenerated
	 */
	public void setPrefijo(String prefijo) {
		this.prefijo = prefijo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.id_ventanilla_derivacion
	 * @return  the value of tbl_ticket.id_ventanilla_derivacion
	 * @ibatorgenerated
	 */
	public Integer getIdVentanillaDerivacion() {
		return idVentanillaDerivacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.id_ventanilla_derivacion
	 * @param idVentanillaDerivacion  the value for tbl_ticket.id_ventanilla_derivacion
	 * @ibatorgenerated
	 */
	public void setIdVentanillaDerivacion(Integer idVentanillaDerivacion) {
		this.idVentanillaDerivacion = idVentanillaDerivacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.activa_audio_texto
	 * @return  the value of tbl_ticket.activa_audio_texto
	 * @ibatorgenerated
	 */
	public Integer getActivaAudioTexto() {
		return activaAudioTexto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.activa_audio_texto
	 * @param activaAudioTexto  the value for tbl_ticket.activa_audio_texto
	 * @ibatorgenerated
	 */
	public void setActivaAudioTexto(Integer activaAudioTexto) {
		this.activaAudioTexto = activaAudioTexto;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.tipo_identificacion
	 * @return  the value of tbl_ticket.tipo_identificacion
	 * @ibatorgenerated
	 */
	public Integer getTipoIdentificacion() {
		return tipoIdentificacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.tipo_identificacion
	 * @param tipoIdentificacion  the value for tbl_ticket.tipo_identificacion
	 * @ibatorgenerated
	 */
	public void setTipoIdentificacion(Integer tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.numero_identificacion
	 * @return  the value of tbl_ticket.numero_identificacion
	 * @ibatorgenerated
	 */
	public String getNumeroIdentificacion() {
		return numeroIdentificacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.numero_identificacion
	 * @param numeroIdentificacion  the value for tbl_ticket.numero_identificacion
	 * @ibatorgenerated
	 */
	public void setNumeroIdentificacion(String numeroIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.descripcion
	 * @return  the value of tbl_ticket.descripcion
	 * @ibatorgenerated
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.descripcion
	 * @param descripcion  the value for tbl_ticket.descripcion
	 * @ibatorgenerated
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.ventanilla_id_usuario
	 * @return  the value of tbl_ticket.ventanilla_id_usuario
	 * @ibatorgenerated
	 */
	public Integer getVentanillaIdUsuario() {
		return ventanillaIdUsuario;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.ventanilla_id_usuario
	 * @param ventanillaIdUsuario  the value for tbl_ticket.ventanilla_id_usuario
	 * @ibatorgenerated
	 */
	public void setVentanillaIdUsuario(Integer ventanillaIdUsuario) {
		this.ventanillaIdUsuario = ventanillaIdUsuario;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.ticket_secuencia
	 * @return  the value of tbl_ticket.ticket_secuencia
	 * @ibatorgenerated
	 */
	public Integer getTicketSecuencia() {
		return ticketSecuencia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.ticket_secuencia
	 * @param ticketSecuencia  the value for tbl_ticket.ticket_secuencia
	 * @ibatorgenerated
	 */
	public void setTicketSecuencia(Integer ticketSecuencia) {
		this.ticketSecuencia = ticketSecuencia;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.envia_audio
	 * @return  the value of tbl_ticket.envia_audio
	 * @ibatorgenerated
	 */
	public Integer getEnviaAudio() {
		return enviaAudio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.envia_audio
	 * @param enviaAudio  the value for tbl_ticket.envia_audio
	 * @ibatorgenerated
	 */
	public void setEnviaAudio(Integer enviaAudio) {
		this.enviaAudio = enviaAudio;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.ventanilla_caja
	 * @return  the value of tbl_ticket.ventanilla_caja
	 * @ibatorgenerated
	 */
	public Integer getVentanillaCaja() {
		return ventanillaCaja;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.ventanilla_caja
	 * @param ventanillaCaja  the value for tbl_ticket.ventanilla_caja
	 * @ibatorgenerated
	 */
	public void setVentanillaCaja(Integer ventanillaCaja) {
		this.ventanillaCaja = ventanillaCaja;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.evaluacion
	 * @return  the value of tbl_ticket.evaluacion
	 * @ibatorgenerated
	 */
	public Integer getEvaluacion() {
		return evaluacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.evaluacion
	 * @param evaluacion  the value for tbl_ticket.evaluacion
	 * @ibatorgenerated
	 */
	public void setEvaluacion(Integer evaluacion) {
		this.evaluacion = evaluacion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column tbl_ticket.fecha_atencion
	 * @return  the value of tbl_ticket.fecha_atencion
	 * @ibatorgenerated
	 */
	public Date getFechaAtencion() {
		return fechaAtencion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column tbl_ticket.fecha_atencion
	 * @param fechaAtencion  the value for tbl_ticket.fecha_atencion
	 * @ibatorgenerated
	 */
	public void setFechaAtencion(Date fechaAtencion) {
		this.fechaAtencion = fechaAtencion;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (!(that instanceof Ticket)) {
			return false;
		}
		Ticket other = (Ticket) that;
		return this.getId() == null ? other == null
				: this.getId().equals(other.getId()) && this.getCodigo() == null ? other == null
						: this.getCodigo().equals(other.getCodigo()) && this.getIdSucursal() == null ? other == null
								: this.getIdSucursal().equals(other.getIdSucursal()) && this.getHoraEmision() == null
										? other == null
										: this.getHoraEmision().equals(other.getHoraEmision())
												&& this.getHoraInicioAtencion() == null
														? other == null
														: this.getHoraInicioAtencion()
																.equals(other.getHoraInicioAtencion())
																&& this.getHoraFinAtencion() == null
																		? other == null
																		: this.getHoraFinAtencion()
																				.equals(other.getHoraFinAtencion())
																				&& this.getIdSubgrupo() == null
																						? other == null
																						: this.getIdSubgrupo().equals(
																								other.getIdSubgrupo())
																								&& this.getHoraInicioReactivacion() == null
																										? other == null
																										: this.getHoraInicioReactivacion()
																												.equals(other
																														.getHoraInicioReactivacion())
																												&& this.getHoraFinReactivacion() == null
																														? other == null
																														: this.getHoraFinReactivacion()
																																.equals(other
																																		.getHoraFinReactivacion())
																																&& this.getFechaHoraProgAlg2Tiempo() == null
																																		? other == null
																																		: this.getFechaHoraProgAlg2Tiempo()
																																				.equals(other
																																						.getFechaHoraProgAlg2Tiempo())
																																				&& this.getEstado() == null
																																						? other == null
																																						: this.getEstado()
																																								.equals(other
																																										.getEstado())
																																								&& this.getSecuenciaAlgo3Proporcion() == null
																																										? other == null
																																										: this.getSecuenciaAlgo3Proporcion()
																																												.equals(other
																																														.getSecuenciaAlgo3Proporcion())
																																												&& this.getIdTicketDerivado() == null
																																														? other == null
																																														: this.getIdTicketDerivado()
																																																.equals(other
																																																		.getIdTicketDerivado())
																																																&& this.getNombreSubgrupo() == null
																																																		? other == null
																																																		: this.getNombreSubgrupo()
																																																				.equals(other
																																																						.getNombreSubgrupo())
																																																				&& this.getPrefijo() == null
																																																						? other == null
																																																						: this.getPrefijo()
																																																								.equals(other
																																																										.getPrefijo())
																																																								&& this.getIdVentanillaDerivacion() == null
																																																										? other == null
																																																										: this.getIdVentanillaDerivacion()
																																																												.equals(other
																																																														.getIdVentanillaDerivacion())
																																																												&& this.getActivaAudioTexto() == null
																																																														? other == null
																																																														: this.getActivaAudioTexto()
																																																																.equals(other
																																																																		.getActivaAudioTexto())
																																																																&& this.getTipoIdentificacion() == null
																																																																		? other == null
																																																																		: this.getTipoIdentificacion()
																																																																				.equals(other
																																																																						.getTipoIdentificacion())
																																																																				&& this.getNumeroIdentificacion() == null
																																																																						? other == null
																																																																						: this.getNumeroIdentificacion()
																																																																								.equals(other
																																																																										.getNumeroIdentificacion())
																																																																								&& this.getDescripcion() == null
																																																																										? other == null
																																																																										: this.getDescripcion()
																																																																												.equals(other
																																																																														.getDescripcion())
																																																																												&& this.getVentanillaIdUsuario() == null
																																																																														? other == null
																																																																														: this.getVentanillaIdUsuario()
																																																																																.equals(other
																																																																																		.getVentanillaIdUsuario())
																																																																																&& this.getTicketSecuencia() == null
																																																																																		? other == null
																																																																																		: this.getTicketSecuencia()
																																																																																				.equals(other
																																																																																						.getTicketSecuencia())
																																																																																				&& this.getEnviaAudio() == null
																																																																																						? other == null
																																																																																						: this.getEnviaAudio()
																																																																																								.equals(other
																																																																																										.getEnviaAudio())
																																																																																								&& this.getVentanillaCaja() == null
																																																																																										? other == null
																																																																																										: this.getVentanillaCaja()
																																																																																												.equals(other
																																																																																														.getVentanillaCaja())
																																																																																												&& this.getEvaluacion() == null
																																																																																														? other == null
																																																																																														: this.getEvaluacion()
																																																																																																.equals(other
																																																																																																		.getEvaluacion())
																																																																																																&& this.getFechaAtencion() == null
																																																																																																		? other == null
																																																																																																		: this.getFechaAtencion()
																																																																																																				.equals(other
																																																																																																						.getFechaAtencion());
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	@Override
	public int hashCode() {
		int hash = 23;
		if (getId() != null) {
			hash *= getId().hashCode();
		}
		if (getCodigo() != null) {
			hash *= getCodigo().hashCode();
		}
		if (getIdSucursal() != null) {
			hash *= getIdSucursal().hashCode();
		}
		if (getHoraEmision() != null) {
			hash *= getHoraEmision().hashCode();
		}
		if (getHoraInicioAtencion() != null) {
			hash *= getHoraInicioAtencion().hashCode();
		}
		if (getHoraFinAtencion() != null) {
			hash *= getHoraFinAtencion().hashCode();
		}
		if (getIdSubgrupo() != null) {
			hash *= getIdSubgrupo().hashCode();
		}
		if (getHoraInicioReactivacion() != null) {
			hash *= getHoraInicioReactivacion().hashCode();
		}
		if (getHoraFinReactivacion() != null) {
			hash *= getHoraFinReactivacion().hashCode();
		}
		if (getFechaHoraProgAlg2Tiempo() != null) {
			hash *= getFechaHoraProgAlg2Tiempo().hashCode();
		}
		if (getEstado() != null) {
			hash *= getEstado().hashCode();
		}
		if (getSecuenciaAlgo3Proporcion() != null) {
			hash *= getSecuenciaAlgo3Proporcion().hashCode();
		}
		if (getIdTicketDerivado() != null) {
			hash *= getIdTicketDerivado().hashCode();
		}
		if (getNombreSubgrupo() != null) {
			hash *= getNombreSubgrupo().hashCode();
		}
		if (getPrefijo() != null) {
			hash *= getPrefijo().hashCode();
		}
		if (getIdVentanillaDerivacion() != null) {
			hash *= getIdVentanillaDerivacion().hashCode();
		}
		if (getActivaAudioTexto() != null) {
			hash *= getActivaAudioTexto().hashCode();
		}
		if (getTipoIdentificacion() != null) {
			hash *= getTipoIdentificacion().hashCode();
		}
		if (getNumeroIdentificacion() != null) {
			hash *= getNumeroIdentificacion().hashCode();
		}
		if (getDescripcion() != null) {
			hash *= getDescripcion().hashCode();
		}
		if (getVentanillaIdUsuario() != null) {
			hash *= getVentanillaIdUsuario().hashCode();
		}
		if (getTicketSecuencia() != null) {
			hash *= getTicketSecuencia().hashCode();
		}
		if (getEnviaAudio() != null) {
			hash *= getEnviaAudio().hashCode();
		}
		if (getVentanillaCaja() != null) {
			hash *= getVentanillaCaja().hashCode();
		}
		if (getEvaluacion() != null) {
			hash *= getEvaluacion().hashCode();
		}
		if (getFechaAtencion() != null) {
			hash *= getFechaAtencion().hashCode();
		}
		return hash;
	}

	//  atributos adicionales
    private String descripcionEstado;
    private Integer idGrupo;
    private String nombreVentanilla;
    private String nombreUsuario;
    private String nombreGrupo;

	public String getDescripcionEstado() {
		return descripcionEstado;
	}

	public void setDescripcionEstado(String descripcionEstado) {
		this.descripcionEstado = descripcionEstado;
	}

	public Integer getIdGrupo() {
		return idGrupo;
	}

	public void setIdGrupo(Integer idGrupo) {
		this.idGrupo = idGrupo;
	}

	public String getNombreVentanilla() {
		return nombreVentanilla;
	}

	public void setNombreVentanilla(String nombreVentanilla) {
		this.nombreVentanilla = nombreVentanilla;
	}

	public String getNombreUsuario() {
		return nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getNombreGrupo() {
		return nombreGrupo;
	}

	public void setNombreGrupo(String nombreGrupo) {
		this.nombreGrupo = nombreGrupo;
	}
}