package pe.gob.ep.iclassq.negocio.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class TicketCriteria {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public TicketCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	protected TicketCriteria(TicketCriteria example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		protected void addCriterionForJDBCTime(String condition, Date value, String property) {
			addCriterion(condition, new java.sql.Time(value.getTime()), property);
		}

		protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				timeList.add(new java.sql.Time(iter.next().getTime()));
			}
			addCriterion(condition, timeList, property);
		}

		protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return this;
		}

		public Criteria andCodigoEqualTo(String value) {
			addCriterion("codigo =", value, "codigo");
			return this;
		}

		public Criteria andCodigoNotEqualTo(String value) {
			addCriterion("codigo <>", value, "codigo");
			return this;
		}

		public Criteria andCodigoGreaterThan(String value) {
			addCriterion("codigo >", value, "codigo");
			return this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(String value) {
			addCriterion("codigo >=", value, "codigo");
			return this;
		}

		public Criteria andCodigoLessThan(String value) {
			addCriterion("codigo <", value, "codigo");
			return this;
		}

		public Criteria andCodigoLessThanOrEqualTo(String value) {
			addCriterion("codigo <=", value, "codigo");
			return this;
		}

		public Criteria andCodigoLike(String value) {
			addCriterion("codigo like", value, "codigo");
			return this;
		}

		public Criteria andCodigoNotLike(String value) {
			addCriterion("codigo not like", value, "codigo");
			return this;
		}

		public Criteria andCodigoIn(List<String> values) {
			addCriterion("codigo in", values, "codigo");
			return this;
		}

		public Criteria andCodigoNotIn(List<String> values) {
			addCriterion("codigo not in", values, "codigo");
			return this;
		}

		public Criteria andCodigoBetween(String value1, String value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return this;
		}

		public Criteria andCodigoNotBetween(String value1, String value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return this;
		}

		public Criteria andIdSucursalIsNull() {
			addCriterion("id_sucursal is null");
			return this;
		}

		public Criteria andIdSucursalIsNotNull() {
			addCriterion("id_sucursal is not null");
			return this;
		}

		public Criteria andIdSucursalEqualTo(Integer value) {
			addCriterion("id_sucursal =", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotEqualTo(Integer value) {
			addCriterion("id_sucursal <>", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalGreaterThan(Integer value) {
			addCriterion("id_sucursal >", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_sucursal >=", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalLessThan(Integer value) {
			addCriterion("id_sucursal <", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalLessThanOrEqualTo(Integer value) {
			addCriterion("id_sucursal <=", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalIn(List<Integer> values) {
			addCriterion("id_sucursal in", values, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotIn(List<Integer> values) {
			addCriterion("id_sucursal not in", values, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalBetween(Integer value1, Integer value2) {
			addCriterion("id_sucursal between", value1, value2, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotBetween(Integer value1, Integer value2) {
			addCriterion("id_sucursal not between", value1, value2, "idSucursal");
			return this;
		}

		public Criteria andHoraEmisionIsNull() {
			addCriterion("hora_emision is null");
			return this;
		}

		public Criteria andHoraEmisionIsNotNull() {
			addCriterion("hora_emision is not null");
			return this;
		}

		public Criteria andHoraEmisionEqualTo(Date value) {
			addCriterionForJDBCTime("hora_emision =", value, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionNotEqualTo(Date value) {
			addCriterionForJDBCTime("hora_emision <>", value, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionGreaterThan(Date value) {
			addCriterionForJDBCTime("hora_emision >", value, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_emision >=", value, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionLessThan(Date value) {
			addCriterionForJDBCTime("hora_emision <", value, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_emision <=", value, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionIn(List<Date> values) {
			addCriterionForJDBCTime("hora_emision in", values, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionNotIn(List<Date> values) {
			addCriterionForJDBCTime("hora_emision not in", values, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_emision between", value1, value2, "horaEmision");
			return this;
		}

		public Criteria andHoraEmisionNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_emision not between", value1, value2, "horaEmision");
			return this;
		}

		public Criteria andHoraInicioAtencionIsNull() {
			addCriterion("hora_inicio_atencion is null");
			return this;
		}

		public Criteria andHoraInicioAtencionIsNotNull() {
			addCriterion("hora_inicio_atencion is not null");
			return this;
		}

		public Criteria andHoraInicioAtencionEqualTo(Date value) {
			addCriterionForJDBCTime("hora_inicio_atencion =", value, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionNotEqualTo(Date value) {
			addCriterionForJDBCTime("hora_inicio_atencion <>", value, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionGreaterThan(Date value) {
			addCriterionForJDBCTime("hora_inicio_atencion >", value, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_inicio_atencion >=", value, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionLessThan(Date value) {
			addCriterionForJDBCTime("hora_inicio_atencion <", value, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_inicio_atencion <=", value, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionIn(List<Date> values) {
			addCriterionForJDBCTime("hora_inicio_atencion in", values, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionNotIn(List<Date> values) {
			addCriterionForJDBCTime("hora_inicio_atencion not in", values, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_inicio_atencion between", value1, value2, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraInicioAtencionNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_inicio_atencion not between", value1, value2, "horaInicioAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionIsNull() {
			addCriterion("hora_fin_atencion is null");
			return this;
		}

		public Criteria andHoraFinAtencionIsNotNull() {
			addCriterion("hora_fin_atencion is not null");
			return this;
		}

		public Criteria andHoraFinAtencionEqualTo(Date value) {
			addCriterionForJDBCTime("hora_fin_atencion =", value, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionNotEqualTo(Date value) {
			addCriterionForJDBCTime("hora_fin_atencion <>", value, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionGreaterThan(Date value) {
			addCriterionForJDBCTime("hora_fin_atencion >", value, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_fin_atencion >=", value, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionLessThan(Date value) {
			addCriterionForJDBCTime("hora_fin_atencion <", value, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_fin_atencion <=", value, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionIn(List<Date> values) {
			addCriterionForJDBCTime("hora_fin_atencion in", values, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionNotIn(List<Date> values) {
			addCriterionForJDBCTime("hora_fin_atencion not in", values, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_fin_atencion between", value1, value2, "horaFinAtencion");
			return this;
		}

		public Criteria andHoraFinAtencionNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_fin_atencion not between", value1, value2, "horaFinAtencion");
			return this;
		}

		public Criteria andIdSubgrupoIsNull() {
			addCriterion("id_subgrupo is null");
			return this;
		}

		public Criteria andIdSubgrupoIsNotNull() {
			addCriterion("id_subgrupo is not null");
			return this;
		}

		public Criteria andIdSubgrupoEqualTo(Integer value) {
			addCriterion("id_subgrupo =", value, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoNotEqualTo(Integer value) {
			addCriterion("id_subgrupo <>", value, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoGreaterThan(Integer value) {
			addCriterion("id_subgrupo >", value, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_subgrupo >=", value, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoLessThan(Integer value) {
			addCriterion("id_subgrupo <", value, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoLessThanOrEqualTo(Integer value) {
			addCriterion("id_subgrupo <=", value, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoIn(List<Integer> values) {
			addCriterion("id_subgrupo in", values, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoNotIn(List<Integer> values) {
			addCriterion("id_subgrupo not in", values, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoBetween(Integer value1, Integer value2) {
			addCriterion("id_subgrupo between", value1, value2, "idSubgrupo");
			return this;
		}

		public Criteria andIdSubgrupoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_subgrupo not between", value1, value2, "idSubgrupo");
			return this;
		}

		public Criteria andHoraInicioReactivacionIsNull() {
			addCriterion("hora_inicio_reactivacion is null");
			return this;
		}

		public Criteria andHoraInicioReactivacionIsNotNull() {
			addCriterion("hora_inicio_reactivacion is not null");
			return this;
		}

		public Criteria andHoraInicioReactivacionEqualTo(Date value) {
			addCriterionForJDBCTime("hora_inicio_reactivacion =", value, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionNotEqualTo(Date value) {
			addCriterionForJDBCTime("hora_inicio_reactivacion <>", value, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionGreaterThan(Date value) {
			addCriterionForJDBCTime("hora_inicio_reactivacion >", value, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_inicio_reactivacion >=", value, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionLessThan(Date value) {
			addCriterionForJDBCTime("hora_inicio_reactivacion <", value, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_inicio_reactivacion <=", value, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionIn(List<Date> values) {
			addCriterionForJDBCTime("hora_inicio_reactivacion in", values, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionNotIn(List<Date> values) {
			addCriterionForJDBCTime("hora_inicio_reactivacion not in", values, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_inicio_reactivacion between", value1, value2, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraInicioReactivacionNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_inicio_reactivacion not between", value1, value2, "horaInicioReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionIsNull() {
			addCriterion("hora_fin_reactivacion is null");
			return this;
		}

		public Criteria andHoraFinReactivacionIsNotNull() {
			addCriterion("hora_fin_reactivacion is not null");
			return this;
		}

		public Criteria andHoraFinReactivacionEqualTo(Date value) {
			addCriterionForJDBCTime("hora_fin_reactivacion =", value, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionNotEqualTo(Date value) {
			addCriterionForJDBCTime("hora_fin_reactivacion <>", value, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionGreaterThan(Date value) {
			addCriterionForJDBCTime("hora_fin_reactivacion >", value, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_fin_reactivacion >=", value, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionLessThan(Date value) {
			addCriterionForJDBCTime("hora_fin_reactivacion <", value, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("hora_fin_reactivacion <=", value, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionIn(List<Date> values) {
			addCriterionForJDBCTime("hora_fin_reactivacion in", values, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionNotIn(List<Date> values) {
			addCriterionForJDBCTime("hora_fin_reactivacion not in", values, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_fin_reactivacion between", value1, value2, "horaFinReactivacion");
			return this;
		}

		public Criteria andHoraFinReactivacionNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("hora_fin_reactivacion not between", value1, value2, "horaFinReactivacion");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoIsNull() {
			addCriterion("fecha_hora_prog_alg_2_tiempo is null");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoIsNotNull() {
			addCriterion("fecha_hora_prog_alg_2_tiempo is not null");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoEqualTo(Date value) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo =", value, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoNotEqualTo(Date value) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo <>", value, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoGreaterThan(Date value) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo >", value, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo >=", value, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoLessThan(Date value) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo <", value, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo <=", value, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoIn(List<Date> values) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo in", values, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoNotIn(List<Date> values) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo not in", values, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo between", value1, value2, "fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andFechaHoraProgAlg2TiempoNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("fecha_hora_prog_alg_2_tiempo not between", value1, value2,
					"fechaHoraProgAlg2Tiempo");
			return this;
		}

		public Criteria andEstadoIsNull() {
			addCriterion("estado is null");
			return this;
		}

		public Criteria andEstadoIsNotNull() {
			addCriterion("estado is not null");
			return this;
		}

		public Criteria andEstadoEqualTo(Integer value) {
			addCriterion("estado =", value, "estado");
			return this;
		}

		public Criteria andEstadoNotEqualTo(Integer value) {
			addCriterion("estado <>", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThan(Integer value) {
			addCriterion("estado >", value, "estado");
			return this;
		}

		public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("estado >=", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThan(Integer value) {
			addCriterion("estado <", value, "estado");
			return this;
		}

		public Criteria andEstadoLessThanOrEqualTo(Integer value) {
			addCriterion("estado <=", value, "estado");
			return this;
		}

		public Criteria andEstadoIn(List<Integer> values) {
			addCriterion("estado in", values, "estado");
			return this;
		}

		public Criteria andEstadoNotIn(List<Integer> values) {
			addCriterion("estado not in", values, "estado");
			return this;
		}

		public Criteria andEstadoBetween(Integer value1, Integer value2) {
			addCriterion("estado between", value1, value2, "estado");
			return this;
		}

		public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
			addCriterion("estado not between", value1, value2, "estado");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionIsNull() {
			addCriterion("secuencia_algo_3_proporcion is null");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionIsNotNull() {
			addCriterion("secuencia_algo_3_proporcion is not null");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionEqualTo(Integer value) {
			addCriterion("secuencia_algo_3_proporcion =", value, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionNotEqualTo(Integer value) {
			addCriterion("secuencia_algo_3_proporcion <>", value, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionGreaterThan(Integer value) {
			addCriterion("secuencia_algo_3_proporcion >", value, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionGreaterThanOrEqualTo(Integer value) {
			addCriterion("secuencia_algo_3_proporcion >=", value, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionLessThan(Integer value) {
			addCriterion("secuencia_algo_3_proporcion <", value, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionLessThanOrEqualTo(Integer value) {
			addCriterion("secuencia_algo_3_proporcion <=", value, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionIn(List<Integer> values) {
			addCriterion("secuencia_algo_3_proporcion in", values, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionNotIn(List<Integer> values) {
			addCriterion("secuencia_algo_3_proporcion not in", values, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionBetween(Integer value1, Integer value2) {
			addCriterion("secuencia_algo_3_proporcion between", value1, value2, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andSecuenciaAlgo3ProporcionNotBetween(Integer value1, Integer value2) {
			addCriterion("secuencia_algo_3_proporcion not between", value1, value2, "secuenciaAlgo3Proporcion");
			return this;
		}

		public Criteria andIdTicketDerivadoIsNull() {
			addCriterion("id_ticket_derivado is null");
			return this;
		}

		public Criteria andIdTicketDerivadoIsNotNull() {
			addCriterion("id_ticket_derivado is not null");
			return this;
		}

		public Criteria andIdTicketDerivadoEqualTo(Integer value) {
			addCriterion("id_ticket_derivado =", value, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoNotEqualTo(Integer value) {
			addCriterion("id_ticket_derivado <>", value, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoGreaterThan(Integer value) {
			addCriterion("id_ticket_derivado >", value, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_ticket_derivado >=", value, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoLessThan(Integer value) {
			addCriterion("id_ticket_derivado <", value, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoLessThanOrEqualTo(Integer value) {
			addCriterion("id_ticket_derivado <=", value, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoIn(List<Integer> values) {
			addCriterion("id_ticket_derivado in", values, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoNotIn(List<Integer> values) {
			addCriterion("id_ticket_derivado not in", values, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoBetween(Integer value1, Integer value2) {
			addCriterion("id_ticket_derivado between", value1, value2, "idTicketDerivado");
			return this;
		}

		public Criteria andIdTicketDerivadoNotBetween(Integer value1, Integer value2) {
			addCriterion("id_ticket_derivado not between", value1, value2, "idTicketDerivado");
			return this;
		}

		public Criteria andNombreSubgrupoIsNull() {
			addCriterion("nombre_subgrupo is null");
			return this;
		}

		public Criteria andNombreSubgrupoIsNotNull() {
			addCriterion("nombre_subgrupo is not null");
			return this;
		}

		public Criteria andNombreSubgrupoEqualTo(String value) {
			addCriterion("nombre_subgrupo =", value, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoNotEqualTo(String value) {
			addCriterion("nombre_subgrupo <>", value, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoGreaterThan(String value) {
			addCriterion("nombre_subgrupo >", value, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoGreaterThanOrEqualTo(String value) {
			addCriterion("nombre_subgrupo >=", value, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoLessThan(String value) {
			addCriterion("nombre_subgrupo <", value, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoLessThanOrEqualTo(String value) {
			addCriterion("nombre_subgrupo <=", value, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoLike(String value) {
			addCriterion("nombre_subgrupo like", value, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoNotLike(String value) {
			addCriterion("nombre_subgrupo not like", value, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoIn(List<String> values) {
			addCriterion("nombre_subgrupo in", values, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoNotIn(List<String> values) {
			addCriterion("nombre_subgrupo not in", values, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoBetween(String value1, String value2) {
			addCriterion("nombre_subgrupo between", value1, value2, "nombreSubgrupo");
			return this;
		}

		public Criteria andNombreSubgrupoNotBetween(String value1, String value2) {
			addCriterion("nombre_subgrupo not between", value1, value2, "nombreSubgrupo");
			return this;
		}

		public Criteria andPrefijoIsNull() {
			addCriterion("prefijo is null");
			return this;
		}

		public Criteria andPrefijoIsNotNull() {
			addCriterion("prefijo is not null");
			return this;
		}

		public Criteria andPrefijoEqualTo(String value) {
			addCriterion("prefijo =", value, "prefijo");
			return this;
		}

		public Criteria andPrefijoNotEqualTo(String value) {
			addCriterion("prefijo <>", value, "prefijo");
			return this;
		}

		public Criteria andPrefijoGreaterThan(String value) {
			addCriterion("prefijo >", value, "prefijo");
			return this;
		}

		public Criteria andPrefijoGreaterThanOrEqualTo(String value) {
			addCriterion("prefijo >=", value, "prefijo");
			return this;
		}

		public Criteria andPrefijoLessThan(String value) {
			addCriterion("prefijo <", value, "prefijo");
			return this;
		}

		public Criteria andPrefijoLessThanOrEqualTo(String value) {
			addCriterion("prefijo <=", value, "prefijo");
			return this;
		}

		public Criteria andPrefijoLike(String value) {
			addCriterion("prefijo like", value, "prefijo");
			return this;
		}

		public Criteria andPrefijoNotLike(String value) {
			addCriterion("prefijo not like", value, "prefijo");
			return this;
		}

		public Criteria andPrefijoIn(List<String> values) {
			addCriterion("prefijo in", values, "prefijo");
			return this;
		}

		public Criteria andPrefijoNotIn(List<String> values) {
			addCriterion("prefijo not in", values, "prefijo");
			return this;
		}

		public Criteria andPrefijoBetween(String value1, String value2) {
			addCriterion("prefijo between", value1, value2, "prefijo");
			return this;
		}

		public Criteria andPrefijoNotBetween(String value1, String value2) {
			addCriterion("prefijo not between", value1, value2, "prefijo");
			return this;
		}

		public Criteria andIdVentanillaDerivacionIsNull() {
			addCriterion("id_ventanilla_derivacion is null");
			return this;
		}

		public Criteria andIdVentanillaDerivacionIsNotNull() {
			addCriterion("id_ventanilla_derivacion is not null");
			return this;
		}

		public Criteria andIdVentanillaDerivacionEqualTo(Integer value) {
			addCriterion("id_ventanilla_derivacion =", value, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionNotEqualTo(Integer value) {
			addCriterion("id_ventanilla_derivacion <>", value, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionGreaterThan(Integer value) {
			addCriterion("id_ventanilla_derivacion >", value, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_ventanilla_derivacion >=", value, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionLessThan(Integer value) {
			addCriterion("id_ventanilla_derivacion <", value, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionLessThanOrEqualTo(Integer value) {
			addCriterion("id_ventanilla_derivacion <=", value, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionIn(List<Integer> values) {
			addCriterion("id_ventanilla_derivacion in", values, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionNotIn(List<Integer> values) {
			addCriterion("id_ventanilla_derivacion not in", values, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionBetween(Integer value1, Integer value2) {
			addCriterion("id_ventanilla_derivacion between", value1, value2, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andIdVentanillaDerivacionNotBetween(Integer value1, Integer value2) {
			addCriterion("id_ventanilla_derivacion not between", value1, value2, "idVentanillaDerivacion");
			return this;
		}

		public Criteria andActivaAudioTextoIsNull() {
			addCriterion("activa_audio_texto is null");
			return this;
		}

		public Criteria andActivaAudioTextoIsNotNull() {
			addCriterion("activa_audio_texto is not null");
			return this;
		}

		public Criteria andActivaAudioTextoEqualTo(Integer value) {
			addCriterion("activa_audio_texto =", value, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoNotEqualTo(Integer value) {
			addCriterion("activa_audio_texto <>", value, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoGreaterThan(Integer value) {
			addCriterion("activa_audio_texto >", value, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoGreaterThanOrEqualTo(Integer value) {
			addCriterion("activa_audio_texto >=", value, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoLessThan(Integer value) {
			addCriterion("activa_audio_texto <", value, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoLessThanOrEqualTo(Integer value) {
			addCriterion("activa_audio_texto <=", value, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoIn(List<Integer> values) {
			addCriterion("activa_audio_texto in", values, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoNotIn(List<Integer> values) {
			addCriterion("activa_audio_texto not in", values, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoBetween(Integer value1, Integer value2) {
			addCriterion("activa_audio_texto between", value1, value2, "activaAudioTexto");
			return this;
		}

		public Criteria andActivaAudioTextoNotBetween(Integer value1, Integer value2) {
			addCriterion("activa_audio_texto not between", value1, value2, "activaAudioTexto");
			return this;
		}

		public Criteria andTipoIdentificacionIsNull() {
			addCriterion("tipo_identificacion is null");
			return this;
		}

		public Criteria andTipoIdentificacionIsNotNull() {
			addCriterion("tipo_identificacion is not null");
			return this;
		}

		public Criteria andTipoIdentificacionEqualTo(Integer value) {
			addCriterion("tipo_identificacion =", value, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionNotEqualTo(Integer value) {
			addCriterion("tipo_identificacion <>", value, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionGreaterThan(Integer value) {
			addCriterion("tipo_identificacion >", value, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionGreaterThanOrEqualTo(Integer value) {
			addCriterion("tipo_identificacion >=", value, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionLessThan(Integer value) {
			addCriterion("tipo_identificacion <", value, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionLessThanOrEqualTo(Integer value) {
			addCriterion("tipo_identificacion <=", value, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionIn(List<Integer> values) {
			addCriterion("tipo_identificacion in", values, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionNotIn(List<Integer> values) {
			addCriterion("tipo_identificacion not in", values, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionBetween(Integer value1, Integer value2) {
			addCriterion("tipo_identificacion between", value1, value2, "tipoIdentificacion");
			return this;
		}

		public Criteria andTipoIdentificacionNotBetween(Integer value1, Integer value2) {
			addCriterion("tipo_identificacion not between", value1, value2, "tipoIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionIsNull() {
			addCriterion("numero_identificacion is null");
			return this;
		}

		public Criteria andNumeroIdentificacionIsNotNull() {
			addCriterion("numero_identificacion is not null");
			return this;
		}

		public Criteria andNumeroIdentificacionEqualTo(String value) {
			addCriterion("numero_identificacion =", value, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionNotEqualTo(String value) {
			addCriterion("numero_identificacion <>", value, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionGreaterThan(String value) {
			addCriterion("numero_identificacion >", value, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionGreaterThanOrEqualTo(String value) {
			addCriterion("numero_identificacion >=", value, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionLessThan(String value) {
			addCriterion("numero_identificacion <", value, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionLessThanOrEqualTo(String value) {
			addCriterion("numero_identificacion <=", value, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionLike(String value) {
			addCriterion("numero_identificacion like", value, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionNotLike(String value) {
			addCriterion("numero_identificacion not like", value, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionIn(List<String> values) {
			addCriterion("numero_identificacion in", values, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionNotIn(List<String> values) {
			addCriterion("numero_identificacion not in", values, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionBetween(String value1, String value2) {
			addCriterion("numero_identificacion between", value1, value2, "numeroIdentificacion");
			return this;
		}

		public Criteria andNumeroIdentificacionNotBetween(String value1, String value2) {
			addCriterion("numero_identificacion not between", value1, value2, "numeroIdentificacion");
			return this;
		}

		public Criteria andDescripcionIsNull() {
			addCriterion("descripcion is null");
			return this;
		}

		public Criteria andDescripcionIsNotNull() {
			addCriterion("descripcion is not null");
			return this;
		}

		public Criteria andDescripcionEqualTo(String value) {
			addCriterion("descripcion =", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotEqualTo(String value) {
			addCriterion("descripcion <>", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThan(String value) {
			addCriterion("descripcion >", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
			addCriterion("descripcion >=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThan(String value) {
			addCriterion("descripcion <", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThanOrEqualTo(String value) {
			addCriterion("descripcion <=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLike(String value) {
			addCriterion("descripcion like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotLike(String value) {
			addCriterion("descripcion not like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionIn(List<String> values) {
			addCriterion("descripcion in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotIn(List<String> values) {
			addCriterion("descripcion not in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionBetween(String value1, String value2) {
			addCriterion("descripcion between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotBetween(String value1, String value2) {
			addCriterion("descripcion not between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andVentanillaIdUsuarioIsNull() {
			addCriterion("ventanilla_id_usuario is null");
			return this;
		}

		public Criteria andVentanillaIdUsuarioIsNotNull() {
			addCriterion("ventanilla_id_usuario is not null");
			return this;
		}

		public Criteria andVentanillaIdUsuarioEqualTo(Integer value) {
			addCriterion("ventanilla_id_usuario =", value, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioNotEqualTo(Integer value) {
			addCriterion("ventanilla_id_usuario <>", value, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioGreaterThan(Integer value) {
			addCriterion("ventanilla_id_usuario >", value, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioGreaterThanOrEqualTo(Integer value) {
			addCriterion("ventanilla_id_usuario >=", value, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioLessThan(Integer value) {
			addCriterion("ventanilla_id_usuario <", value, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioLessThanOrEqualTo(Integer value) {
			addCriterion("ventanilla_id_usuario <=", value, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioIn(List<Integer> values) {
			addCriterion("ventanilla_id_usuario in", values, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioNotIn(List<Integer> values) {
			addCriterion("ventanilla_id_usuario not in", values, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioBetween(Integer value1, Integer value2) {
			addCriterion("ventanilla_id_usuario between", value1, value2, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andVentanillaIdUsuarioNotBetween(Integer value1, Integer value2) {
			addCriterion("ventanilla_id_usuario not between", value1, value2, "ventanillaIdUsuario");
			return this;
		}

		public Criteria andTicketSecuenciaIsNull() {
			addCriterion("ticket_secuencia is null");
			return this;
		}

		public Criteria andTicketSecuenciaIsNotNull() {
			addCriterion("ticket_secuencia is not null");
			return this;
		}

		public Criteria andTicketSecuenciaEqualTo(Integer value) {
			addCriterion("ticket_secuencia =", value, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaNotEqualTo(Integer value) {
			addCriterion("ticket_secuencia <>", value, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaGreaterThan(Integer value) {
			addCriterion("ticket_secuencia >", value, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ticket_secuencia >=", value, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaLessThan(Integer value) {
			addCriterion("ticket_secuencia <", value, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaLessThanOrEqualTo(Integer value) {
			addCriterion("ticket_secuencia <=", value, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaIn(List<Integer> values) {
			addCriterion("ticket_secuencia in", values, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaNotIn(List<Integer> values) {
			addCriterion("ticket_secuencia not in", values, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaBetween(Integer value1, Integer value2) {
			addCriterion("ticket_secuencia between", value1, value2, "ticketSecuencia");
			return this;
		}

		public Criteria andTicketSecuenciaNotBetween(Integer value1, Integer value2) {
			addCriterion("ticket_secuencia not between", value1, value2, "ticketSecuencia");
			return this;
		}

		public Criteria andEnviaAudioIsNull() {
			addCriterion("envia_audio is null");
			return this;
		}

		public Criteria andEnviaAudioIsNotNull() {
			addCriterion("envia_audio is not null");
			return this;
		}

		public Criteria andEnviaAudioEqualTo(Integer value) {
			addCriterion("envia_audio =", value, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioNotEqualTo(Integer value) {
			addCriterion("envia_audio <>", value, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioGreaterThan(Integer value) {
			addCriterion("envia_audio >", value, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioGreaterThanOrEqualTo(Integer value) {
			addCriterion("envia_audio >=", value, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioLessThan(Integer value) {
			addCriterion("envia_audio <", value, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioLessThanOrEqualTo(Integer value) {
			addCriterion("envia_audio <=", value, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioIn(List<Integer> values) {
			addCriterion("envia_audio in", values, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioNotIn(List<Integer> values) {
			addCriterion("envia_audio not in", values, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioBetween(Integer value1, Integer value2) {
			addCriterion("envia_audio between", value1, value2, "enviaAudio");
			return this;
		}

		public Criteria andEnviaAudioNotBetween(Integer value1, Integer value2) {
			addCriterion("envia_audio not between", value1, value2, "enviaAudio");
			return this;
		}

		public Criteria andVentanillaCajaIsNull() {
			addCriterion("ventanilla_caja is null");
			return this;
		}

		public Criteria andVentanillaCajaIsNotNull() {
			addCriterion("ventanilla_caja is not null");
			return this;
		}

		public Criteria andVentanillaCajaEqualTo(Integer value) {
			addCriterion("ventanilla_caja =", value, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaNotEqualTo(Integer value) {
			addCriterion("ventanilla_caja <>", value, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaGreaterThan(Integer value) {
			addCriterion("ventanilla_caja >", value, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaGreaterThanOrEqualTo(Integer value) {
			addCriterion("ventanilla_caja >=", value, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaLessThan(Integer value) {
			addCriterion("ventanilla_caja <", value, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaLessThanOrEqualTo(Integer value) {
			addCriterion("ventanilla_caja <=", value, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaIn(List<Integer> values) {
			addCriterion("ventanilla_caja in", values, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaNotIn(List<Integer> values) {
			addCriterion("ventanilla_caja not in", values, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaBetween(Integer value1, Integer value2) {
			addCriterion("ventanilla_caja between", value1, value2, "ventanillaCaja");
			return this;
		}

		public Criteria andVentanillaCajaNotBetween(Integer value1, Integer value2) {
			addCriterion("ventanilla_caja not between", value1, value2, "ventanillaCaja");
			return this;
		}

		public Criteria andEvaluacionIsNull() {
			addCriterion("evaluacion is null");
			return this;
		}

		public Criteria andEvaluacionIsNotNull() {
			addCriterion("evaluacion is not null");
			return this;
		}

		public Criteria andEvaluacionEqualTo(Integer value) {
			addCriterion("evaluacion =", value, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionNotEqualTo(Integer value) {
			addCriterion("evaluacion <>", value, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionGreaterThan(Integer value) {
			addCriterion("evaluacion >", value, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionGreaterThanOrEqualTo(Integer value) {
			addCriterion("evaluacion >=", value, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionLessThan(Integer value) {
			addCriterion("evaluacion <", value, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionLessThanOrEqualTo(Integer value) {
			addCriterion("evaluacion <=", value, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionIn(List<Integer> values) {
			addCriterion("evaluacion in", values, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionNotIn(List<Integer> values) {
			addCriterion("evaluacion not in", values, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionBetween(Integer value1, Integer value2) {
			addCriterion("evaluacion between", value1, value2, "evaluacion");
			return this;
		}

		public Criteria andEvaluacionNotBetween(Integer value1, Integer value2) {
			addCriterion("evaluacion not between", value1, value2, "evaluacion");
			return this;
		}

		public Criteria andFechaAtencionIsNull() {
			addCriterion("fecha_atencion is null");
			return this;
		}

		public Criteria andFechaAtencionIsNotNull() {
			addCriterion("fecha_atencion is not null");
			return this;
		}

		public Criteria andFechaAtencionEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_atencion =", value, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionNotEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_atencion <>", value, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionGreaterThan(Date value) {
			addCriterionForJDBCDate("fecha_atencion >", value, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_atencion >=", value, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionLessThan(Date value) {
			addCriterionForJDBCDate("fecha_atencion <", value, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("fecha_atencion <=", value, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionIn(List<Date> values) {
			addCriterionForJDBCDate("fecha_atencion in", values, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionNotIn(List<Date> values) {
			addCriterionForJDBCDate("fecha_atencion not in", values, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_atencion between", value1, value2, "fechaAtencion");
			return this;
		}

		public Criteria andFechaAtencionNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("fecha_atencion not between", value1, value2, "fechaAtencion");
			return this;
		}
	}
}