package pe.gob.ep.iclassq.negocio.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VentanillaCriteria {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public VentanillaCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	protected VentanillaCriteria(VentanillaCriteria example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andDescripcionIsNull() {
			addCriterion("descripcion is null");
			return this;
		}

		public Criteria andDescripcionIsNotNull() {
			addCriterion("descripcion is not null");
			return this;
		}

		public Criteria andDescripcionEqualTo(String value) {
			addCriterion("descripcion =", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotEqualTo(String value) {
			addCriterion("descripcion <>", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThan(String value) {
			addCriterion("descripcion >", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
			addCriterion("descripcion >=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThan(String value) {
			addCriterion("descripcion <", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLessThanOrEqualTo(String value) {
			addCriterion("descripcion <=", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionLike(String value) {
			addCriterion("descripcion like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotLike(String value) {
			addCriterion("descripcion not like", value, "descripcion");
			return this;
		}

		public Criteria andDescripcionIn(List<String> values) {
			addCriterion("descripcion in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotIn(List<String> values) {
			addCriterion("descripcion not in", values, "descripcion");
			return this;
		}

		public Criteria andDescripcionBetween(String value1, String value2) {
			addCriterion("descripcion between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andDescripcionNotBetween(String value1, String value2) {
			addCriterion("descripcion not between", value1, value2, "descripcion");
			return this;
		}

		public Criteria andUbicacionIsNull() {
			addCriterion("ubicacion is null");
			return this;
		}

		public Criteria andUbicacionIsNotNull() {
			addCriterion("ubicacion is not null");
			return this;
		}

		public Criteria andUbicacionEqualTo(String value) {
			addCriterion("ubicacion =", value, "ubicacion");
			return this;
		}

		public Criteria andUbicacionNotEqualTo(String value) {
			addCriterion("ubicacion <>", value, "ubicacion");
			return this;
		}

		public Criteria andUbicacionGreaterThan(String value) {
			addCriterion("ubicacion >", value, "ubicacion");
			return this;
		}

		public Criteria andUbicacionGreaterThanOrEqualTo(String value) {
			addCriterion("ubicacion >=", value, "ubicacion");
			return this;
		}

		public Criteria andUbicacionLessThan(String value) {
			addCriterion("ubicacion <", value, "ubicacion");
			return this;
		}

		public Criteria andUbicacionLessThanOrEqualTo(String value) {
			addCriterion("ubicacion <=", value, "ubicacion");
			return this;
		}

		public Criteria andUbicacionLike(String value) {
			addCriterion("ubicacion like", value, "ubicacion");
			return this;
		}

		public Criteria andUbicacionNotLike(String value) {
			addCriterion("ubicacion not like", value, "ubicacion");
			return this;
		}

		public Criteria andUbicacionIn(List<String> values) {
			addCriterion("ubicacion in", values, "ubicacion");
			return this;
		}

		public Criteria andUbicacionNotIn(List<String> values) {
			addCriterion("ubicacion not in", values, "ubicacion");
			return this;
		}

		public Criteria andUbicacionBetween(String value1, String value2) {
			addCriterion("ubicacion between", value1, value2, "ubicacion");
			return this;
		}

		public Criteria andUbicacionNotBetween(String value1, String value2) {
			addCriterion("ubicacion not between", value1, value2, "ubicacion");
			return this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return this;
		}

		public Criteria andIdAreaIsNull() {
			addCriterion("id_area is null");
			return this;
		}

		public Criteria andIdAreaIsNotNull() {
			addCriterion("id_area is not null");
			return this;
		}

		public Criteria andIdAreaEqualTo(Integer value) {
			addCriterion("id_area =", value, "idArea");
			return this;
		}

		public Criteria andIdAreaNotEqualTo(Integer value) {
			addCriterion("id_area <>", value, "idArea");
			return this;
		}

		public Criteria andIdAreaGreaterThan(Integer value) {
			addCriterion("id_area >", value, "idArea");
			return this;
		}

		public Criteria andIdAreaGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_area >=", value, "idArea");
			return this;
		}

		public Criteria andIdAreaLessThan(Integer value) {
			addCriterion("id_area <", value, "idArea");
			return this;
		}

		public Criteria andIdAreaLessThanOrEqualTo(Integer value) {
			addCriterion("id_area <=", value, "idArea");
			return this;
		}

		public Criteria andIdAreaIn(List<Integer> values) {
			addCriterion("id_area in", values, "idArea");
			return this;
		}

		public Criteria andIdAreaNotIn(List<Integer> values) {
			addCriterion("id_area not in", values, "idArea");
			return this;
		}

		public Criteria andIdAreaBetween(Integer value1, Integer value2) {
			addCriterion("id_area between", value1, value2, "idArea");
			return this;
		}

		public Criteria andIdAreaNotBetween(Integer value1, Integer value2) {
			addCriterion("id_area not between", value1, value2, "idArea");
			return this;
		}

		public Criteria andIdSucursalIsNull() {
			addCriterion("id_sucursal is null");
			return this;
		}

		public Criteria andIdSucursalIsNotNull() {
			addCriterion("id_sucursal is not null");
			return this;
		}

		public Criteria andIdSucursalEqualTo(Integer value) {
			addCriterion("id_sucursal =", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotEqualTo(Integer value) {
			addCriterion("id_sucursal <>", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalGreaterThan(Integer value) {
			addCriterion("id_sucursal >", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_sucursal >=", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalLessThan(Integer value) {
			addCriterion("id_sucursal <", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalLessThanOrEqualTo(Integer value) {
			addCriterion("id_sucursal <=", value, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalIn(List<Integer> values) {
			addCriterion("id_sucursal in", values, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotIn(List<Integer> values) {
			addCriterion("id_sucursal not in", values, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalBetween(Integer value1, Integer value2) {
			addCriterion("id_sucursal between", value1, value2, "idSucursal");
			return this;
		}

		public Criteria andIdSucursalNotBetween(Integer value1, Integer value2) {
			addCriterion("id_sucursal not between", value1, value2, "idSucursal");
			return this;
		}

		public Criteria andTipoEvaluacionIsNull() {
			addCriterion("tipo_evaluacion is null");
			return this;
		}

		public Criteria andTipoEvaluacionIsNotNull() {
			addCriterion("tipo_evaluacion is not null");
			return this;
		}

		public Criteria andTipoEvaluacionEqualTo(Integer value) {
			addCriterion("tipo_evaluacion =", value, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionNotEqualTo(Integer value) {
			addCriterion("tipo_evaluacion <>", value, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionGreaterThan(Integer value) {
			addCriterion("tipo_evaluacion >", value, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionGreaterThanOrEqualTo(Integer value) {
			addCriterion("tipo_evaluacion >=", value, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionLessThan(Integer value) {
			addCriterion("tipo_evaluacion <", value, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionLessThanOrEqualTo(Integer value) {
			addCriterion("tipo_evaluacion <=", value, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionIn(List<Integer> values) {
			addCriterion("tipo_evaluacion in", values, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionNotIn(List<Integer> values) {
			addCriterion("tipo_evaluacion not in", values, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionBetween(Integer value1, Integer value2) {
			addCriterion("tipo_evaluacion between", value1, value2, "tipoEvaluacion");
			return this;
		}

		public Criteria andTipoEvaluacionNotBetween(Integer value1, Integer value2) {
			addCriterion("tipo_evaluacion not between", value1, value2, "tipoEvaluacion");
			return this;
		}

		public Criteria andPuertoIsNull() {
			addCriterion("puerto is null");
			return this;
		}

		public Criteria andPuertoIsNotNull() {
			addCriterion("puerto is not null");
			return this;
		}

		public Criteria andPuertoEqualTo(String value) {
			addCriterion("puerto =", value, "puerto");
			return this;
		}

		public Criteria andPuertoNotEqualTo(String value) {
			addCriterion("puerto <>", value, "puerto");
			return this;
		}

		public Criteria andPuertoGreaterThan(String value) {
			addCriterion("puerto >", value, "puerto");
			return this;
		}

		public Criteria andPuertoGreaterThanOrEqualTo(String value) {
			addCriterion("puerto >=", value, "puerto");
			return this;
		}

		public Criteria andPuertoLessThan(String value) {
			addCriterion("puerto <", value, "puerto");
			return this;
		}

		public Criteria andPuertoLessThanOrEqualTo(String value) {
			addCriterion("puerto <=", value, "puerto");
			return this;
		}

		public Criteria andPuertoLike(String value) {
			addCriterion("puerto like", value, "puerto");
			return this;
		}

		public Criteria andPuertoNotLike(String value) {
			addCriterion("puerto not like", value, "puerto");
			return this;
		}

		public Criteria andPuertoIn(List<String> values) {
			addCriterion("puerto in", values, "puerto");
			return this;
		}

		public Criteria andPuertoNotIn(List<String> values) {
			addCriterion("puerto not in", values, "puerto");
			return this;
		}

		public Criteria andPuertoBetween(String value1, String value2) {
			addCriterion("puerto between", value1, value2, "puerto");
			return this;
		}

		public Criteria andPuertoNotBetween(String value1, String value2) {
			addCriterion("puerto not between", value1, value2, "puerto");
			return this;
		}

		public Criteria andNotificacionIdIsNull() {
			addCriterion("notificacion_id is null");
			return this;
		}

		public Criteria andNotificacionIdIsNotNull() {
			addCriterion("notificacion_id is not null");
			return this;
		}

		public Criteria andNotificacionIdEqualTo(Integer value) {
			addCriterion("notificacion_id =", value, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdNotEqualTo(Integer value) {
			addCriterion("notificacion_id <>", value, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdGreaterThan(Integer value) {
			addCriterion("notificacion_id >", value, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("notificacion_id >=", value, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdLessThan(Integer value) {
			addCriterion("notificacion_id <", value, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdLessThanOrEqualTo(Integer value) {
			addCriterion("notificacion_id <=", value, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdIn(List<Integer> values) {
			addCriterion("notificacion_id in", values, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdNotIn(List<Integer> values) {
			addCriterion("notificacion_id not in", values, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdBetween(Integer value1, Integer value2) {
			addCriterion("notificacion_id between", value1, value2, "notificacionId");
			return this;
		}

		public Criteria andNotificacionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("notificacion_id not between", value1, value2, "notificacionId");
			return this;
		}
	}
}