package pe.gob.ep.iclassq.seguridad.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.seguridad.bean.UsuarioCriteria.Criteria;

public class UsuarioCriteria {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	public UsuarioCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	protected UsuarioCriteria(UsuarioCriteria example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIUsuarioIdIsNull() {
			addCriterion("I_USUARIO_ID is null");
			return this;
		}

		public Criteria andIUsuarioIdIsNotNull() {
			addCriterion("I_USUARIO_ID is not null");
			return this;
		}

		public Criteria andIUsuarioIdEqualTo(Integer value) {
			addCriterion("I_USUARIO_ID =", value, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdNotEqualTo(Integer value) {
			addCriterion("I_USUARIO_ID <>", value, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdGreaterThan(Integer value) {
			addCriterion("I_USUARIO_ID >", value, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_USUARIO_ID >=", value, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdLessThan(Integer value) {
			addCriterion("I_USUARIO_ID <", value, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdLessThanOrEqualTo(Integer value) {
			addCriterion("I_USUARIO_ID <=", value, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdIn(List<Integer> values) {
			addCriterion("I_USUARIO_ID in", values, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdNotIn(List<Integer> values) {
			addCriterion("I_USUARIO_ID not in", values, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdBetween(Integer value1, Integer value2) {
			addCriterion("I_USUARIO_ID between", value1, value2, "iUsuarioId");
			return this;
		}

		public Criteria andIUsuarioIdNotBetween(Integer value1, Integer value2) {
			addCriterion("I_USUARIO_ID not between", value1, value2, "iUsuarioId");
			return this;
		}

		public Criteria andVUsuarioUsernameIsNull() {
			addCriterion("V_USUARIO_USERNAME is null");
			return this;
		}

		public Criteria andVUsuarioUsernameIsNotNull() {
			addCriterion("V_USUARIO_USERNAME is not null");
			return this;
		}

		public Criteria andVUsuarioUsernameEqualTo(String value) {
			addCriterion("V_USUARIO_USERNAME =", value, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameNotEqualTo(String value) {
			addCriterion("V_USUARIO_USERNAME <>", value, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameGreaterThan(String value) {
			addCriterion("V_USUARIO_USERNAME >", value, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_USERNAME >=", value, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameLessThan(String value) {
			addCriterion("V_USUARIO_USERNAME <", value, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_USERNAME <=", value, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameLike(String value) {
			addCriterion("V_USUARIO_USERNAME like", value, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameNotLike(String value) {
			addCriterion("V_USUARIO_USERNAME not like", value, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameIn(List<String> values) {
			addCriterion("V_USUARIO_USERNAME in", values, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameNotIn(List<String> values) {
			addCriterion("V_USUARIO_USERNAME not in", values, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameBetween(String value1, String value2) {
			addCriterion("V_USUARIO_USERNAME between", value1, value2, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioUsernameNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_USERNAME not between", value1, value2, "vUsuarioUsername");
			return this;
		}

		public Criteria andVUsuarioPasswordIsNull() {
			addCriterion("V_USUARIO_PASSWORD is null");
			return this;
		}

		public Criteria andVUsuarioPasswordIsNotNull() {
			addCriterion("V_USUARIO_PASSWORD is not null");
			return this;
		}

		public Criteria andVUsuarioPasswordEqualTo(String value) {
			addCriterion("V_USUARIO_PASSWORD =", value, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordNotEqualTo(String value) {
			addCriterion("V_USUARIO_PASSWORD <>", value, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordGreaterThan(String value) {
			addCriterion("V_USUARIO_PASSWORD >", value, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_PASSWORD >=", value, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordLessThan(String value) {
			addCriterion("V_USUARIO_PASSWORD <", value, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_PASSWORD <=", value, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordLike(String value) {
			addCriterion("V_USUARIO_PASSWORD like", value, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordNotLike(String value) {
			addCriterion("V_USUARIO_PASSWORD not like", value, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordIn(List<String> values) {
			addCriterion("V_USUARIO_PASSWORD in", values, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordNotIn(List<String> values) {
			addCriterion("V_USUARIO_PASSWORD not in", values, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordBetween(String value1, String value2) {
			addCriterion("V_USUARIO_PASSWORD between", value1, value2, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioPasswordNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_PASSWORD not between", value1, value2, "vUsuarioPassword");
			return this;
		}

		public Criteria andVUsuarioApPaternoIsNull() {
			addCriterion("V_USUARIO_AP_PATERNO is null");
			return this;
		}

		public Criteria andVUsuarioApPaternoIsNotNull() {
			addCriterion("V_USUARIO_AP_PATERNO is not null");
			return this;
		}

		public Criteria andVUsuarioApPaternoEqualTo(String value) {
			addCriterion("V_USUARIO_AP_PATERNO =", value, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoNotEqualTo(String value) {
			addCriterion("V_USUARIO_AP_PATERNO <>", value, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoGreaterThan(String value) {
			addCriterion("V_USUARIO_AP_PATERNO >", value, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_AP_PATERNO >=", value, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoLessThan(String value) {
			addCriterion("V_USUARIO_AP_PATERNO <", value, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_AP_PATERNO <=", value, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoLike(String value) {
			addCriterion("V_USUARIO_AP_PATERNO like", value, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoNotLike(String value) {
			addCriterion("V_USUARIO_AP_PATERNO not like", value, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoIn(List<String> values) {
			addCriterion("V_USUARIO_AP_PATERNO in", values, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoNotIn(List<String> values) {
			addCriterion("V_USUARIO_AP_PATERNO not in", values, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoBetween(String value1, String value2) {
			addCriterion("V_USUARIO_AP_PATERNO between", value1, value2, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApPaternoNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_AP_PATERNO not between", value1, value2, "vUsuarioApPaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoIsNull() {
			addCriterion("V_USUARIO_AP_MATERNO is null");
			return this;
		}

		public Criteria andVUsuarioApMaternoIsNotNull() {
			addCriterion("V_USUARIO_AP_MATERNO is not null");
			return this;
		}

		public Criteria andVUsuarioApMaternoEqualTo(String value) {
			addCriterion("V_USUARIO_AP_MATERNO =", value, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoNotEqualTo(String value) {
			addCriterion("V_USUARIO_AP_MATERNO <>", value, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoGreaterThan(String value) {
			addCriterion("V_USUARIO_AP_MATERNO >", value, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_AP_MATERNO >=", value, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoLessThan(String value) {
			addCriterion("V_USUARIO_AP_MATERNO <", value, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_AP_MATERNO <=", value, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoLike(String value) {
			addCriterion("V_USUARIO_AP_MATERNO like", value, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoNotLike(String value) {
			addCriterion("V_USUARIO_AP_MATERNO not like", value, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoIn(List<String> values) {
			addCriterion("V_USUARIO_AP_MATERNO in", values, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoNotIn(List<String> values) {
			addCriterion("V_USUARIO_AP_MATERNO not in", values, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoBetween(String value1, String value2) {
			addCriterion("V_USUARIO_AP_MATERNO between", value1, value2, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioApMaternoNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_AP_MATERNO not between", value1, value2, "vUsuarioApMaterno");
			return this;
		}

		public Criteria andVUsuarioNombresIsNull() {
			addCriterion("V_USUARIO_NOMBRES is null");
			return this;
		}

		public Criteria andVUsuarioNombresIsNotNull() {
			addCriterion("V_USUARIO_NOMBRES is not null");
			return this;
		}

		public Criteria andVUsuarioNombresEqualTo(String value) {
			addCriterion("V_USUARIO_NOMBRES =", value, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresNotEqualTo(String value) {
			addCriterion("V_USUARIO_NOMBRES <>", value, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresGreaterThan(String value) {
			addCriterion("V_USUARIO_NOMBRES >", value, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_NOMBRES >=", value, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresLessThan(String value) {
			addCriterion("V_USUARIO_NOMBRES <", value, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_NOMBRES <=", value, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresLike(String value) {
			addCriterion("V_USUARIO_NOMBRES like", value, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresNotLike(String value) {
			addCriterion("V_USUARIO_NOMBRES not like", value, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresIn(List<String> values) {
			addCriterion("V_USUARIO_NOMBRES in", values, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresNotIn(List<String> values) {
			addCriterion("V_USUARIO_NOMBRES not in", values, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresBetween(String value1, String value2) {
			addCriterion("V_USUARIO_NOMBRES between", value1, value2, "vUsuarioNombres");
			return this;
		}

		public Criteria andVUsuarioNombresNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_NOMBRES not between", value1, value2, "vUsuarioNombres");
			return this;
		}

		public Criteria andCUsuarioIpIsNull() {
			addCriterion("C_USUARIO_IP is null");
			return this;
		}

		public Criteria andCUsuarioIpIsNotNull() {
			addCriterion("C_USUARIO_IP is not null");
			return this;
		}

		public Criteria andCUsuarioIpEqualTo(String value) {
			addCriterion("C_USUARIO_IP =", value, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpNotEqualTo(String value) {
			addCriterion("C_USUARIO_IP <>", value, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpGreaterThan(String value) {
			addCriterion("C_USUARIO_IP >", value, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpGreaterThanOrEqualTo(String value) {
			addCriterion("C_USUARIO_IP >=", value, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpLessThan(String value) {
			addCriterion("C_USUARIO_IP <", value, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpLessThanOrEqualTo(String value) {
			addCriterion("C_USUARIO_IP <=", value, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpLike(String value) {
			addCriterion("C_USUARIO_IP like", value, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpNotLike(String value) {
			addCriterion("C_USUARIO_IP not like", value, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpIn(List<String> values) {
			addCriterion("C_USUARIO_IP in", values, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpNotIn(List<String> values) {
			addCriterion("C_USUARIO_IP not in", values, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpBetween(String value1, String value2) {
			addCriterion("C_USUARIO_IP between", value1, value2, "cUsuarioIp");
			return this;
		}

		public Criteria andCUsuarioIpNotBetween(String value1, String value2) {
			addCriterion("C_USUARIO_IP not between", value1, value2, "cUsuarioIp");
			return this;
		}

		public Criteria andISucursalIsNull() {
			addCriterion("I_SUCURSAL is null");
			return this;
		}

		public Criteria andISucursalIsNotNull() {
			addCriterion("I_SUCURSAL is not null");
			return this;
		}

		public Criteria andISucursalEqualTo(Integer value) {
			addCriterion("I_SUCURSAL =", value, "iSucursal");
			return this;
		}

		public Criteria andISucursalNotEqualTo(Integer value) {
			addCriterion("I_SUCURSAL <>", value, "iSucursal");
			return this;
		}

		public Criteria andISucursalGreaterThan(Integer value) {
			addCriterion("I_SUCURSAL >", value, "iSucursal");
			return this;
		}

		public Criteria andISucursalGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_SUCURSAL >=", value, "iSucursal");
			return this;
		}

		public Criteria andISucursalLessThan(Integer value) {
			addCriterion("I_SUCURSAL <", value, "iSucursal");
			return this;
		}

		public Criteria andISucursalLessThanOrEqualTo(Integer value) {
			addCriterion("I_SUCURSAL <=", value, "iSucursal");
			return this;
		}

		public Criteria andISucursalIn(List<Integer> values) {
			addCriterion("I_SUCURSAL in", values, "iSucursal");
			return this;
		}

		public Criteria andISucursalNotIn(List<Integer> values) {
			addCriterion("I_SUCURSAL not in", values, "iSucursal");
			return this;
		}

		public Criteria andISucursalBetween(Integer value1, Integer value2) {
			addCriterion("I_SUCURSAL between", value1, value2, "iSucursal");
			return this;
		}

		public Criteria andISucursalNotBetween(Integer value1, Integer value2) {
			addCriterion("I_SUCURSAL not between", value1, value2, "iSucursal");
			return this;
		}

		public Criteria andIAreaIsNull() {
			addCriterion("I_AREA is null");
			return this;
		}

		public Criteria andIAreaIsNotNull() {
			addCriterion("I_AREA is not null");
			return this;
		}

		public Criteria andIAreaEqualTo(Integer value) {
			addCriterion("I_AREA =", value, "iArea");
			return this;
		}

		public Criteria andIAreaNotEqualTo(Integer value) {
			addCriterion("I_AREA <>", value, "iArea");
			return this;
		}

		public Criteria andIAreaGreaterThan(Integer value) {
			addCriterion("I_AREA >", value, "iArea");
			return this;
		}

		public Criteria andIAreaGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_AREA >=", value, "iArea");
			return this;
		}

		public Criteria andIAreaLessThan(Integer value) {
			addCriterion("I_AREA <", value, "iArea");
			return this;
		}

		public Criteria andIAreaLessThanOrEqualTo(Integer value) {
			addCriterion("I_AREA <=", value, "iArea");
			return this;
		}

		public Criteria andIAreaIn(List<Integer> values) {
			addCriterion("I_AREA in", values, "iArea");
			return this;
		}

		public Criteria andIAreaNotIn(List<Integer> values) {
			addCriterion("I_AREA not in", values, "iArea");
			return this;
		}

		public Criteria andIAreaBetween(Integer value1, Integer value2) {
			addCriterion("I_AREA between", value1, value2, "iArea");
			return this;
		}

		public Criteria andIAreaNotBetween(Integer value1, Integer value2) {
			addCriterion("I_AREA not between", value1, value2, "iArea");
			return this;
		}

		public Criteria andIEmpresaIsNull() {
			addCriterion("I_EMPRESA is null");
			return this;
		}

		public Criteria andIEmpresaIsNotNull() {
			addCriterion("I_EMPRESA is not null");
			return this;
		}

		public Criteria andIEmpresaEqualTo(Integer value) {
			addCriterion("I_EMPRESA =", value, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaNotEqualTo(Integer value) {
			addCriterion("I_EMPRESA <>", value, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaGreaterThan(Integer value) {
			addCriterion("I_EMPRESA >", value, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_EMPRESA >=", value, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaLessThan(Integer value) {
			addCriterion("I_EMPRESA <", value, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaLessThanOrEqualTo(Integer value) {
			addCriterion("I_EMPRESA <=", value, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaIn(List<Integer> values) {
			addCriterion("I_EMPRESA in", values, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaNotIn(List<Integer> values) {
			addCriterion("I_EMPRESA not in", values, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaBetween(Integer value1, Integer value2) {
			addCriterion("I_EMPRESA between", value1, value2, "iEmpresa");
			return this;
		}

		public Criteria andIEmpresaNotBetween(Integer value1, Integer value2) {
			addCriterion("I_EMPRESA not between", value1, value2, "iEmpresa");
			return this;
		}

		public Criteria andIVentanillaIsNull() {
			addCriterion("I_VENTANILLA is null");
			return this;
		}

		public Criteria andIVentanillaIsNotNull() {
			addCriterion("I_VENTANILLA is not null");
			return this;
		}

		public Criteria andIVentanillaEqualTo(Integer value) {
			addCriterion("I_VENTANILLA =", value, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaNotEqualTo(Integer value) {
			addCriterion("I_VENTANILLA <>", value, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaGreaterThan(Integer value) {
			addCriterion("I_VENTANILLA >", value, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_VENTANILLA >=", value, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaLessThan(Integer value) {
			addCriterion("I_VENTANILLA <", value, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaLessThanOrEqualTo(Integer value) {
			addCriterion("I_VENTANILLA <=", value, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaIn(List<Integer> values) {
			addCriterion("I_VENTANILLA in", values, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaNotIn(List<Integer> values) {
			addCriterion("I_VENTANILLA not in", values, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaBetween(Integer value1, Integer value2) {
			addCriterion("I_VENTANILLA between", value1, value2, "iVentanilla");
			return this;
		}

		public Criteria andIVentanillaNotBetween(Integer value1, Integer value2) {
			addCriterion("I_VENTANILLA not between", value1, value2, "iVentanilla");
			return this;
		}

		public Criteria andIRolEquipoIsNull() {
			addCriterion("I_ROL_EQUIPO is null");
			return this;
		}

		public Criteria andIRolEquipoIsNotNull() {
			addCriterion("I_ROL_EQUIPO is not null");
			return this;
		}

		public Criteria andIRolEquipoEqualTo(Integer value) {
			addCriterion("I_ROL_EQUIPO =", value, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoNotEqualTo(Integer value) {
			addCriterion("I_ROL_EQUIPO <>", value, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoGreaterThan(Integer value) {
			addCriterion("I_ROL_EQUIPO >", value, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_ROL_EQUIPO >=", value, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoLessThan(Integer value) {
			addCriterion("I_ROL_EQUIPO <", value, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoLessThanOrEqualTo(Integer value) {
			addCriterion("I_ROL_EQUIPO <=", value, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoIn(List<Integer> values) {
			addCriterion("I_ROL_EQUIPO in", values, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoNotIn(List<Integer> values) {
			addCriterion("I_ROL_EQUIPO not in", values, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoBetween(Integer value1, Integer value2) {
			addCriterion("I_ROL_EQUIPO between", value1, value2, "iRolEquipo");
			return this;
		}

		public Criteria andIRolEquipoNotBetween(Integer value1, Integer value2) {
			addCriterion("I_ROL_EQUIPO not between", value1, value2, "iRolEquipo");
			return this;
		}

		public Criteria andIMonitorTipoIsNull() {
			addCriterion("I_MONITOR_TIPO is null");
			return this;
		}

		public Criteria andIMonitorTipoIsNotNull() {
			addCriterion("I_MONITOR_TIPO is not null");
			return this;
		}

		public Criteria andIMonitorTipoEqualTo(Integer value) {
			addCriterion("I_MONITOR_TIPO =", value, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoNotEqualTo(Integer value) {
			addCriterion("I_MONITOR_TIPO <>", value, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoGreaterThan(Integer value) {
			addCriterion("I_MONITOR_TIPO >", value, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_MONITOR_TIPO >=", value, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoLessThan(Integer value) {
			addCriterion("I_MONITOR_TIPO <", value, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoLessThanOrEqualTo(Integer value) {
			addCriterion("I_MONITOR_TIPO <=", value, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoIn(List<Integer> values) {
			addCriterion("I_MONITOR_TIPO in", values, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoNotIn(List<Integer> values) {
			addCriterion("I_MONITOR_TIPO not in", values, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoBetween(Integer value1, Integer value2) {
			addCriterion("I_MONITOR_TIPO between", value1, value2, "iMonitorTipo");
			return this;
		}

		public Criteria andIMonitorTipoNotBetween(Integer value1, Integer value2) {
			addCriterion("I_MONITOR_TIPO not between", value1, value2, "iMonitorTipo");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpIsNull() {
			addCriterion("C_USUARIO_SOLICITA_IP is null");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpIsNotNull() {
			addCriterion("C_USUARIO_SOLICITA_IP is not null");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpEqualTo(String value) {
			addCriterion("C_USUARIO_SOLICITA_IP =", value, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpNotEqualTo(String value) {
			addCriterion("C_USUARIO_SOLICITA_IP <>", value, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpGreaterThan(String value) {
			addCriterion("C_USUARIO_SOLICITA_IP >", value, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpGreaterThanOrEqualTo(String value) {
			addCriterion("C_USUARIO_SOLICITA_IP >=", value, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpLessThan(String value) {
			addCriterion("C_USUARIO_SOLICITA_IP <", value, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpLessThanOrEqualTo(String value) {
			addCriterion("C_USUARIO_SOLICITA_IP <=", value, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpLike(String value) {
			addCriterion("C_USUARIO_SOLICITA_IP like", value, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpNotLike(String value) {
			addCriterion("C_USUARIO_SOLICITA_IP not like", value, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpIn(List<String> values) {
			addCriterion("C_USUARIO_SOLICITA_IP in", values, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpNotIn(List<String> values) {
			addCriterion("C_USUARIO_SOLICITA_IP not in", values, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpBetween(String value1, String value2) {
			addCriterion("C_USUARIO_SOLICITA_IP between", value1, value2, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andCUsuarioSolicitaIpNotBetween(String value1, String value2) {
			addCriterion("C_USUARIO_SOLICITA_IP not between", value1, value2, "cUsuarioSolicitaIp");
			return this;
		}

		public Criteria andIValidaDocumentoIsNull() {
			addCriterion("I_VALIDA_DOCUMENTO is null");
			return this;
		}

		public Criteria andIValidaDocumentoIsNotNull() {
			addCriterion("I_VALIDA_DOCUMENTO is not null");
			return this;
		}

		public Criteria andIValidaDocumentoEqualTo(Integer value) {
			addCriterion("I_VALIDA_DOCUMENTO =", value, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoNotEqualTo(Integer value) {
			addCriterion("I_VALIDA_DOCUMENTO <>", value, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoGreaterThan(Integer value) {
			addCriterion("I_VALIDA_DOCUMENTO >", value, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_VALIDA_DOCUMENTO >=", value, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoLessThan(Integer value) {
			addCriterion("I_VALIDA_DOCUMENTO <", value, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoLessThanOrEqualTo(Integer value) {
			addCriterion("I_VALIDA_DOCUMENTO <=", value, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoIn(List<Integer> values) {
			addCriterion("I_VALIDA_DOCUMENTO in", values, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoNotIn(List<Integer> values) {
			addCriterion("I_VALIDA_DOCUMENTO not in", values, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoBetween(Integer value1, Integer value2) {
			addCriterion("I_VALIDA_DOCUMENTO between", value1, value2, "iValidaDocumento");
			return this;
		}

		public Criteria andIValidaDocumentoNotBetween(Integer value1, Integer value2) {
			addCriterion("I_VALIDA_DOCUMENTO not between", value1, value2, "iValidaDocumento");
			return this;
		}

		public Criteria andIPideDocumentoIsNull() {
			addCriterion("I_PIDE_DOCUMENTO is null");
			return this;
		}

		public Criteria andIPideDocumentoIsNotNull() {
			addCriterion("I_PIDE_DOCUMENTO is not null");
			return this;
		}

		public Criteria andIPideDocumentoEqualTo(Integer value) {
			addCriterion("I_PIDE_DOCUMENTO =", value, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoNotEqualTo(Integer value) {
			addCriterion("I_PIDE_DOCUMENTO <>", value, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoGreaterThan(Integer value) {
			addCriterion("I_PIDE_DOCUMENTO >", value, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_PIDE_DOCUMENTO >=", value, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoLessThan(Integer value) {
			addCriterion("I_PIDE_DOCUMENTO <", value, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoLessThanOrEqualTo(Integer value) {
			addCriterion("I_PIDE_DOCUMENTO <=", value, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoIn(List<Integer> values) {
			addCriterion("I_PIDE_DOCUMENTO in", values, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoNotIn(List<Integer> values) {
			addCriterion("I_PIDE_DOCUMENTO not in", values, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoBetween(Integer value1, Integer value2) {
			addCriterion("I_PIDE_DOCUMENTO between", value1, value2, "iPideDocumento");
			return this;
		}

		public Criteria andIPideDocumentoNotBetween(Integer value1, Integer value2) {
			addCriterion("I_PIDE_DOCUMENTO not between", value1, value2, "iPideDocumento");
			return this;
		}

		public Criteria andIImprimeTicketIsNull() {
			addCriterion("I_IMPRIME_TICKET is null");
			return this;
		}

		public Criteria andIImprimeTicketIsNotNull() {
			addCriterion("I_IMPRIME_TICKET is not null");
			return this;
		}

		public Criteria andIImprimeTicketEqualTo(Integer value) {
			addCriterion("I_IMPRIME_TICKET =", value, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketNotEqualTo(Integer value) {
			addCriterion("I_IMPRIME_TICKET <>", value, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketGreaterThan(Integer value) {
			addCriterion("I_IMPRIME_TICKET >", value, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_IMPRIME_TICKET >=", value, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketLessThan(Integer value) {
			addCriterion("I_IMPRIME_TICKET <", value, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketLessThanOrEqualTo(Integer value) {
			addCriterion("I_IMPRIME_TICKET <=", value, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketIn(List<Integer> values) {
			addCriterion("I_IMPRIME_TICKET in", values, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketNotIn(List<Integer> values) {
			addCriterion("I_IMPRIME_TICKET not in", values, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketBetween(Integer value1, Integer value2) {
			addCriterion("I_IMPRIME_TICKET between", value1, value2, "iImprimeTicket");
			return this;
		}

		public Criteria andIImprimeTicketNotBetween(Integer value1, Integer value2) {
			addCriterion("I_IMPRIME_TICKET not between", value1, value2, "iImprimeTicket");
			return this;
		}

		public Criteria andIEvaluaIsNull() {
			addCriterion("I_EVALUA is null");
			return this;
		}

		public Criteria andIEvaluaIsNotNull() {
			addCriterion("I_EVALUA is not null");
			return this;
		}

		public Criteria andIEvaluaEqualTo(Integer value) {
			addCriterion("I_EVALUA =", value, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaNotEqualTo(Integer value) {
			addCriterion("I_EVALUA <>", value, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaGreaterThan(Integer value) {
			addCriterion("I_EVALUA >", value, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_EVALUA >=", value, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaLessThan(Integer value) {
			addCriterion("I_EVALUA <", value, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaLessThanOrEqualTo(Integer value) {
			addCriterion("I_EVALUA <=", value, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaIn(List<Integer> values) {
			addCriterion("I_EVALUA in", values, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaNotIn(List<Integer> values) {
			addCriterion("I_EVALUA not in", values, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaBetween(Integer value1, Integer value2) {
			addCriterion("I_EVALUA between", value1, value2, "iEvalua");
			return this;
		}

		public Criteria andIEvaluaNotBetween(Integer value1, Integer value2) {
			addCriterion("I_EVALUA not between", value1, value2, "iEvalua");
			return this;
		}

		public Criteria andIAnulaIsNull() {
			addCriterion("I_ANULA is null");
			return this;
		}

		public Criteria andIAnulaIsNotNull() {
			addCriterion("I_ANULA is not null");
			return this;
		}

		public Criteria andIAnulaEqualTo(Integer value) {
			addCriterion("I_ANULA =", value, "iAnula");
			return this;
		}

		public Criteria andIAnulaNotEqualTo(Integer value) {
			addCriterion("I_ANULA <>", value, "iAnula");
			return this;
		}

		public Criteria andIAnulaGreaterThan(Integer value) {
			addCriterion("I_ANULA >", value, "iAnula");
			return this;
		}

		public Criteria andIAnulaGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_ANULA >=", value, "iAnula");
			return this;
		}

		public Criteria andIAnulaLessThan(Integer value) {
			addCriterion("I_ANULA <", value, "iAnula");
			return this;
		}

		public Criteria andIAnulaLessThanOrEqualTo(Integer value) {
			addCriterion("I_ANULA <=", value, "iAnula");
			return this;
		}

		public Criteria andIAnulaIn(List<Integer> values) {
			addCriterion("I_ANULA in", values, "iAnula");
			return this;
		}

		public Criteria andIAnulaNotIn(List<Integer> values) {
			addCriterion("I_ANULA not in", values, "iAnula");
			return this;
		}

		public Criteria andIAnulaBetween(Integer value1, Integer value2) {
			addCriterion("I_ANULA between", value1, value2, "iAnula");
			return this;
		}

		public Criteria andIAnulaNotBetween(Integer value1, Integer value2) {
			addCriterion("I_ANULA not between", value1, value2, "iAnula");
			return this;
		}

		public Criteria andIAtencionIsNull() {
			addCriterion("I_ATENCION is null");
			return this;
		}

		public Criteria andIAtencionIsNotNull() {
			addCriterion("I_ATENCION is not null");
			return this;
		}

		public Criteria andIAtencionEqualTo(Integer value) {
			addCriterion("I_ATENCION =", value, "iAtencion");
			return this;
		}

		public Criteria andIAtencionNotEqualTo(Integer value) {
			addCriterion("I_ATENCION <>", value, "iAtencion");
			return this;
		}

		public Criteria andIAtencionGreaterThan(Integer value) {
			addCriterion("I_ATENCION >", value, "iAtencion");
			return this;
		}

		public Criteria andIAtencionGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_ATENCION >=", value, "iAtencion");
			return this;
		}

		public Criteria andIAtencionLessThan(Integer value) {
			addCriterion("I_ATENCION <", value, "iAtencion");
			return this;
		}

		public Criteria andIAtencionLessThanOrEqualTo(Integer value) {
			addCriterion("I_ATENCION <=", value, "iAtencion");
			return this;
		}

		public Criteria andIAtencionIn(List<Integer> values) {
			addCriterion("I_ATENCION in", values, "iAtencion");
			return this;
		}

		public Criteria andIAtencionNotIn(List<Integer> values) {
			addCriterion("I_ATENCION not in", values, "iAtencion");
			return this;
		}

		public Criteria andIAtencionBetween(Integer value1, Integer value2) {
			addCriterion("I_ATENCION between", value1, value2, "iAtencion");
			return this;
		}

		public Criteria andIAtencionNotBetween(Integer value1, Integer value2) {
			addCriterion("I_ATENCION not between", value1, value2, "iAtencion");
			return this;
		}

		public Criteria andVPuertoIsNull() {
			addCriterion("V_PUERTO is null");
			return this;
		}

		public Criteria andVPuertoIsNotNull() {
			addCriterion("V_PUERTO is not null");
			return this;
		}

		public Criteria andVPuertoEqualTo(String value) {
			addCriterion("V_PUERTO =", value, "vPuerto");
			return this;
		}

		public Criteria andVPuertoNotEqualTo(String value) {
			addCriterion("V_PUERTO <>", value, "vPuerto");
			return this;
		}

		public Criteria andVPuertoGreaterThan(String value) {
			addCriterion("V_PUERTO >", value, "vPuerto");
			return this;
		}

		public Criteria andVPuertoGreaterThanOrEqualTo(String value) {
			addCriterion("V_PUERTO >=", value, "vPuerto");
			return this;
		}

		public Criteria andVPuertoLessThan(String value) {
			addCriterion("V_PUERTO <", value, "vPuerto");
			return this;
		}

		public Criteria andVPuertoLessThanOrEqualTo(String value) {
			addCriterion("V_PUERTO <=", value, "vPuerto");
			return this;
		}

		public Criteria andVPuertoLike(String value) {
			addCriterion("V_PUERTO like", value, "vPuerto");
			return this;
		}

		public Criteria andVPuertoNotLike(String value) {
			addCriterion("V_PUERTO not like", value, "vPuerto");
			return this;
		}

		public Criteria andVPuertoIn(List<String> values) {
			addCriterion("V_PUERTO in", values, "vPuerto");
			return this;
		}

		public Criteria andVPuertoNotIn(List<String> values) {
			addCriterion("V_PUERTO not in", values, "vPuerto");
			return this;
		}

		public Criteria andVPuertoBetween(String value1, String value2) {
			addCriterion("V_PUERTO between", value1, value2, "vPuerto");
			return this;
		}

		public Criteria andVPuertoNotBetween(String value1, String value2) {
			addCriterion("V_PUERTO not between", value1, value2, "vPuerto");
			return this;
		}

		public Criteria andDUsuarioFecregistraIsNull() {
			addCriterion("D_USUARIO_FECREGISTRA is null");
			return this;
		}

		public Criteria andDUsuarioFecregistraIsNotNull() {
			addCriterion("D_USUARIO_FECREGISTRA is not null");
			return this;
		}

		public Criteria andDUsuarioFecregistraEqualTo(Date value) {
			addCriterion("D_USUARIO_FECREGISTRA =", value, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraNotEqualTo(Date value) {
			addCriterion("D_USUARIO_FECREGISTRA <>", value, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraGreaterThan(Date value) {
			addCriterion("D_USUARIO_FECREGISTRA >", value, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraGreaterThanOrEqualTo(Date value) {
			addCriterion("D_USUARIO_FECREGISTRA >=", value, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraLessThan(Date value) {
			addCriterion("D_USUARIO_FECREGISTRA <", value, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraLessThanOrEqualTo(Date value) {
			addCriterion("D_USUARIO_FECREGISTRA <=", value, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraIn(List<Date> values) {
			addCriterion("D_USUARIO_FECREGISTRA in", values, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraNotIn(List<Date> values) {
			addCriterion("D_USUARIO_FECREGISTRA not in", values, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraBetween(Date value1, Date value2) {
			addCriterion("D_USUARIO_FECREGISTRA between", value1, value2, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecregistraNotBetween(Date value1, Date value2) {
			addCriterion("D_USUARIO_FECREGISTRA not between", value1, value2, "dUsuarioFecregistra");
			return this;
		}

		public Criteria andDUsuarioFecmodificaIsNull() {
			addCriterion("D_USUARIO_FECMODIFICA is null");
			return this;
		}

		public Criteria andDUsuarioFecmodificaIsNotNull() {
			addCriterion("D_USUARIO_FECMODIFICA is not null");
			return this;
		}

		public Criteria andDUsuarioFecmodificaEqualTo(Date value) {
			addCriterion("D_USUARIO_FECMODIFICA =", value, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaNotEqualTo(Date value) {
			addCriterion("D_USUARIO_FECMODIFICA <>", value, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaGreaterThan(Date value) {
			addCriterion("D_USUARIO_FECMODIFICA >", value, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaGreaterThanOrEqualTo(Date value) {
			addCriterion("D_USUARIO_FECMODIFICA >=", value, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaLessThan(Date value) {
			addCriterion("D_USUARIO_FECMODIFICA <", value, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaLessThanOrEqualTo(Date value) {
			addCriterion("D_USUARIO_FECMODIFICA <=", value, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaIn(List<Date> values) {
			addCriterion("D_USUARIO_FECMODIFICA in", values, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaNotIn(List<Date> values) {
			addCriterion("D_USUARIO_FECMODIFICA not in", values, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaBetween(Date value1, Date value2) {
			addCriterion("D_USUARIO_FECMODIFICA between", value1, value2, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andDUsuarioFecmodificaNotBetween(Date value1, Date value2) {
			addCriterion("D_USUARIO_FECMODIFICA not between", value1, value2, "dUsuarioFecmodifica");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraIsNull() {
			addCriterion("V_USUARIO_DESUSUREGISTRA is null");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraIsNotNull() {
			addCriterion("V_USUARIO_DESUSUREGISTRA is not null");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraEqualTo(String value) {
			addCriterion("V_USUARIO_DESUSUREGISTRA =", value, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraNotEqualTo(String value) {
			addCriterion("V_USUARIO_DESUSUREGISTRA <>", value, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraGreaterThan(String value) {
			addCriterion("V_USUARIO_DESUSUREGISTRA >", value, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_DESUSUREGISTRA >=", value, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraLessThan(String value) {
			addCriterion("V_USUARIO_DESUSUREGISTRA <", value, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_DESUSUREGISTRA <=", value, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraLike(String value) {
			addCriterion("V_USUARIO_DESUSUREGISTRA like", value, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraNotLike(String value) {
			addCriterion("V_USUARIO_DESUSUREGISTRA not like", value, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraIn(List<String> values) {
			addCriterion("V_USUARIO_DESUSUREGISTRA in", values, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraNotIn(List<String> values) {
			addCriterion("V_USUARIO_DESUSUREGISTRA not in", values, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraBetween(String value1, String value2) {
			addCriterion("V_USUARIO_DESUSUREGISTRA between", value1, value2, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusuregistraNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_DESUSUREGISTRA not between", value1, value2, "vUsuarioDesusuregistra");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaIsNull() {
			addCriterion("V_USUARIO_DESUSUMODIFICA is null");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaIsNotNull() {
			addCriterion("V_USUARIO_DESUSUMODIFICA is not null");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaEqualTo(String value) {
			addCriterion("V_USUARIO_DESUSUMODIFICA =", value, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaNotEqualTo(String value) {
			addCriterion("V_USUARIO_DESUSUMODIFICA <>", value, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaGreaterThan(String value) {
			addCriterion("V_USUARIO_DESUSUMODIFICA >", value, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_DESUSUMODIFICA >=", value, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaLessThan(String value) {
			addCriterion("V_USUARIO_DESUSUMODIFICA <", value, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_DESUSUMODIFICA <=", value, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaLike(String value) {
			addCriterion("V_USUARIO_DESUSUMODIFICA like", value, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaNotLike(String value) {
			addCriterion("V_USUARIO_DESUSUMODIFICA not like", value, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaIn(List<String> values) {
			addCriterion("V_USUARIO_DESUSUMODIFICA in", values, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaNotIn(List<String> values) {
			addCriterion("V_USUARIO_DESUSUMODIFICA not in", values, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaBetween(String value1, String value2) {
			addCriterion("V_USUARIO_DESUSUMODIFICA between", value1, value2, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesusumodificaNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_DESUSUMODIFICA not between", value1, value2, "vUsuarioDesusumodifica");
			return this;
		}

		public Criteria andVUsuarioDesipregistraIsNull() {
			addCriterion("V_USUARIO_DESIPREGISTRA is null");
			return this;
		}

		public Criteria andVUsuarioDesipregistraIsNotNull() {
			addCriterion("V_USUARIO_DESIPREGISTRA is not null");
			return this;
		}

		public Criteria andVUsuarioDesipregistraEqualTo(String value) {
			addCriterion("V_USUARIO_DESIPREGISTRA =", value, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraNotEqualTo(String value) {
			addCriterion("V_USUARIO_DESIPREGISTRA <>", value, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraGreaterThan(String value) {
			addCriterion("V_USUARIO_DESIPREGISTRA >", value, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_DESIPREGISTRA >=", value, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraLessThan(String value) {
			addCriterion("V_USUARIO_DESIPREGISTRA <", value, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_DESIPREGISTRA <=", value, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraLike(String value) {
			addCriterion("V_USUARIO_DESIPREGISTRA like", value, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraNotLike(String value) {
			addCriterion("V_USUARIO_DESIPREGISTRA not like", value, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraIn(List<String> values) {
			addCriterion("V_USUARIO_DESIPREGISTRA in", values, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraNotIn(List<String> values) {
			addCriterion("V_USUARIO_DESIPREGISTRA not in", values, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraBetween(String value1, String value2) {
			addCriterion("V_USUARIO_DESIPREGISTRA between", value1, value2, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipregistraNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_DESIPREGISTRA not between", value1, value2, "vUsuarioDesipregistra");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaIsNull() {
			addCriterion("V_USUARIO_DESIPMODIFICA is null");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaIsNotNull() {
			addCriterion("V_USUARIO_DESIPMODIFICA is not null");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaEqualTo(String value) {
			addCriterion("V_USUARIO_DESIPMODIFICA =", value, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaNotEqualTo(String value) {
			addCriterion("V_USUARIO_DESIPMODIFICA <>", value, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaGreaterThan(String value) {
			addCriterion("V_USUARIO_DESIPMODIFICA >", value, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_DESIPMODIFICA >=", value, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaLessThan(String value) {
			addCriterion("V_USUARIO_DESIPMODIFICA <", value, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_DESIPMODIFICA <=", value, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaLike(String value) {
			addCriterion("V_USUARIO_DESIPMODIFICA like", value, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaNotLike(String value) {
			addCriterion("V_USUARIO_DESIPMODIFICA not like", value, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaIn(List<String> values) {
			addCriterion("V_USUARIO_DESIPMODIFICA in", values, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaNotIn(List<String> values) {
			addCriterion("V_USUARIO_DESIPMODIFICA not in", values, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaBetween(String value1, String value2) {
			addCriterion("V_USUARIO_DESIPMODIFICA between", value1, value2, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andVUsuarioDesipmodificaNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_DESIPMODIFICA not between", value1, value2, "vUsuarioDesipmodifica");
			return this;
		}

		public Criteria andIUsuarioEstadoIsNull() {
			addCriterion("I_USUARIO_ESTADO is null");
			return this;
		}

		public Criteria andIUsuarioEstadoIsNotNull() {
			addCriterion("I_USUARIO_ESTADO is not null");
			return this;
		}

		public Criteria andIUsuarioEstadoEqualTo(Integer value) {
			addCriterion("I_USUARIO_ESTADO =", value, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoNotEqualTo(Integer value) {
			addCriterion("I_USUARIO_ESTADO <>", value, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoGreaterThan(Integer value) {
			addCriterion("I_USUARIO_ESTADO >", value, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_USUARIO_ESTADO >=", value, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoLessThan(Integer value) {
			addCriterion("I_USUARIO_ESTADO <", value, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoLessThanOrEqualTo(Integer value) {
			addCriterion("I_USUARIO_ESTADO <=", value, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoIn(List<Integer> values) {
			addCriterion("I_USUARIO_ESTADO in", values, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoNotIn(List<Integer> values) {
			addCriterion("I_USUARIO_ESTADO not in", values, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoBetween(Integer value1, Integer value2) {
			addCriterion("I_USUARIO_ESTADO between", value1, value2, "iUsuarioEstado");
			return this;
		}

		public Criteria andIUsuarioEstadoNotBetween(Integer value1, Integer value2) {
			addCriterion("I_USUARIO_ESTADO not between", value1, value2, "iUsuarioEstado");
			return this;
		}

		public Criteria andVUsuarioEmailIsNull() {
			addCriterion("V_USUARIO_EMAIL is null");
			return this;
		}

		public Criteria andVUsuarioEmailIsNotNull() {
			addCriterion("V_USUARIO_EMAIL is not null");
			return this;
		}

		public Criteria andVUsuarioEmailEqualTo(String value) {
			addCriterion("V_USUARIO_EMAIL =", value, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailNotEqualTo(String value) {
			addCriterion("V_USUARIO_EMAIL <>", value, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailGreaterThan(String value) {
			addCriterion("V_USUARIO_EMAIL >", value, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailGreaterThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_EMAIL >=", value, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailLessThan(String value) {
			addCriterion("V_USUARIO_EMAIL <", value, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailLessThanOrEqualTo(String value) {
			addCriterion("V_USUARIO_EMAIL <=", value, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailLike(String value) {
			addCriterion("V_USUARIO_EMAIL like", value, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailNotLike(String value) {
			addCriterion("V_USUARIO_EMAIL not like", value, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailIn(List<String> values) {
			addCriterion("V_USUARIO_EMAIL in", values, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailNotIn(List<String> values) {
			addCriterion("V_USUARIO_EMAIL not in", values, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailBetween(String value1, String value2) {
			addCriterion("V_USUARIO_EMAIL between", value1, value2, "vUsuarioEmail");
			return this;
		}

		public Criteria andVUsuarioEmailNotBetween(String value1, String value2) {
			addCriterion("V_USUARIO_EMAIL not between", value1, value2, "vUsuarioEmail");
			return this;
		}

		public Criteria andIControlAsistenciaIsNull() {
			addCriterion("I_CONTROL_ASISTENCIA is null");
			return this;
		}

		public Criteria andIControlAsistenciaIsNotNull() {
			addCriterion("I_CONTROL_ASISTENCIA is not null");
			return this;
		}

		public Criteria andIControlAsistenciaEqualTo(Integer value) {
			addCriterion("I_CONTROL_ASISTENCIA =", value, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaNotEqualTo(Integer value) {
			addCriterion("I_CONTROL_ASISTENCIA <>", value, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaGreaterThan(Integer value) {
			addCriterion("I_CONTROL_ASISTENCIA >", value, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_CONTROL_ASISTENCIA >=", value, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaLessThan(Integer value) {
			addCriterion("I_CONTROL_ASISTENCIA <", value, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaLessThanOrEqualTo(Integer value) {
			addCriterion("I_CONTROL_ASISTENCIA <=", value, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaIn(List<Integer> values) {
			addCriterion("I_CONTROL_ASISTENCIA in", values, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaNotIn(List<Integer> values) {
			addCriterion("I_CONTROL_ASISTENCIA not in", values, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaBetween(Integer value1, Integer value2) {
			addCriterion("I_CONTROL_ASISTENCIA between", value1, value2, "iControlAsistencia");
			return this;
		}

		public Criteria andIControlAsistenciaNotBetween(Integer value1, Integer value2) {
			addCriterion("I_CONTROL_ASISTENCIA not between", value1, value2, "iControlAsistencia");
			return this;
		}

		public Criteria andDniIsNull() {
			addCriterion("DNI is null");
			return this;
		}

		public Criteria andDniIsNotNull() {
			addCriterion("DNI is not null");
			return this;
		}

		public Criteria andDniEqualTo(String value) {
			addCriterion("DNI =", value, "dni");
			return this;
		}

		public Criteria andDniNotEqualTo(String value) {
			addCriterion("DNI <>", value, "dni");
			return this;
		}

		public Criteria andDniGreaterThan(String value) {
			addCriterion("DNI >", value, "dni");
			return this;
		}

		public Criteria andDniGreaterThanOrEqualTo(String value) {
			addCriterion("DNI >=", value, "dni");
			return this;
		}

		public Criteria andDniLessThan(String value) {
			addCriterion("DNI <", value, "dni");
			return this;
		}

		public Criteria andDniLessThanOrEqualTo(String value) {
			addCriterion("DNI <=", value, "dni");
			return this;
		}

		public Criteria andDniLike(String value) {
			addCriterion("DNI like", value, "dni");
			return this;
		}

		public Criteria andDniNotLike(String value) {
			addCriterion("DNI not like", value, "dni");
			return this;
		}

		public Criteria andDniIn(List<String> values) {
			addCriterion("DNI in", values, "dni");
			return this;
		}

		public Criteria andDniNotIn(List<String> values) {
			addCriterion("DNI not in", values, "dni");
			return this;
		}

		public Criteria andDniBetween(String value1, String value2) {
			addCriterion("DNI between", value1, value2, "dni");
			return this;
		}

		public Criteria andDniNotBetween(String value1, String value2) {
			addCriterion("DNI not between", value1, value2, "dni");
			return this;
		}

		public Criteria andIConfirmaImpresionIsNull() {
			addCriterion("I_CONFIRMA_IMPRESION is null");
			return this;
		}

		public Criteria andIConfirmaImpresionIsNotNull() {
			addCriterion("I_CONFIRMA_IMPRESION is not null");
			return this;
		}

		public Criteria andIConfirmaImpresionEqualTo(Integer value) {
			addCriterion("I_CONFIRMA_IMPRESION =", value, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionNotEqualTo(Integer value) {
			addCriterion("I_CONFIRMA_IMPRESION <>", value, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionGreaterThan(Integer value) {
			addCriterion("I_CONFIRMA_IMPRESION >", value, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_CONFIRMA_IMPRESION >=", value, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionLessThan(Integer value) {
			addCriterion("I_CONFIRMA_IMPRESION <", value, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionLessThanOrEqualTo(Integer value) {
			addCriterion("I_CONFIRMA_IMPRESION <=", value, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionIn(List<Integer> values) {
			addCriterion("I_CONFIRMA_IMPRESION in", values, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionNotIn(List<Integer> values) {
			addCriterion("I_CONFIRMA_IMPRESION not in", values, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionBetween(Integer value1, Integer value2) {
			addCriterion("I_CONFIRMA_IMPRESION between", value1, value2, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIConfirmaImpresionNotBetween(Integer value1, Integer value2) {
			addCriterion("I_CONFIRMA_IMPRESION not between", value1, value2, "iConfirmaImpresion");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdIsNull() {
			addCriterion("I_USUARIO_PRINCIPAL_ID is null");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdIsNotNull() {
			addCriterion("I_USUARIO_PRINCIPAL_ID is not null");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdEqualTo(Integer value) {
			addCriterion("I_USUARIO_PRINCIPAL_ID =", value, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdNotEqualTo(Integer value) {
			addCriterion("I_USUARIO_PRINCIPAL_ID <>", value, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdGreaterThan(Integer value) {
			addCriterion("I_USUARIO_PRINCIPAL_ID >", value, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("I_USUARIO_PRINCIPAL_ID >=", value, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdLessThan(Integer value) {
			addCriterion("I_USUARIO_PRINCIPAL_ID <", value, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdLessThanOrEqualTo(Integer value) {
			addCriterion("I_USUARIO_PRINCIPAL_ID <=", value, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdIn(List<Integer> values) {
			addCriterion("I_USUARIO_PRINCIPAL_ID in", values, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdNotIn(List<Integer> values) {
			addCriterion("I_USUARIO_PRINCIPAL_ID not in", values, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdBetween(Integer value1, Integer value2) {
			addCriterion("I_USUARIO_PRINCIPAL_ID between", value1, value2, "iUsuarioPrincipalId");
			return this;
		}

		public Criteria andIUsuarioPrincipalIdNotBetween(Integer value1, Integer value2) {
			addCriterion("I_USUARIO_PRINCIPAL_ID not between", value1, value2, "iUsuarioPrincipalId");
			return this;
		}
	}
}