package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.negocio.bean.Area;
import pe.gob.ep.iclassq.negocio.bean.AreaCriteria;
import pe.gob.ep.iclassq.entidad.BeanId;

public interface AreaDAO {
    


//meotodos adicionales

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	int countByExample(AreaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	int deleteByExample(AreaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	void insert(Area record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	void insertSelective(Area record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	List<Area> selectByExample(AreaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	Area selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Area record, AreaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	int updateByExample(Area record, AreaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Area record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_area
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Area record);

	public List<BeanId> listarAreaGrupoID(Map<String, Object> params);
}