package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanReporteAsistencia;
import pe.gob.ep.iclassq.entidad.BeanTicketXArea;
import pe.gob.ep.iclassq.negocio.bean.Asistencia;
import pe.gob.ep.iclassq.negocio.bean.AsistenciaCriteria;

public interface AsistenciaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	int countByExample(AsistenciaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	int deleteByExample(AsistenciaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	void insert(Asistencia record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	void insertSelective(Asistencia record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	List<Asistencia> selectByExample(AsistenciaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	Asistencia selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Asistencia record, AsistenciaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	int updateByExample(Asistencia record, AsistenciaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Asistencia record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_asistencia
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Asistencia record);

	public List<BeanReporteAsistencia> listarReporteAsistencia(Map<String, Object> params);

	public List<BeanReporteAsistencia> listarDetalleReporte(Map<String, Object> paramet);
}