package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.negocio.bean.Dni;
import pe.gob.ep.iclassq.negocio.bean.DniCriteria;
import pe.gob.ep.iclassq.negocio.bean.TablaGeneral;
import pe.gob.ep.iclassq.entidad.BeanDni;

public interface DniDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	int countByExample(DniCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	int deleteByExample(DniCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	void insert(Dni record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	void insertSelective(Dni record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	List<Dni> selectByExample(DniCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	Dni selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Dni record, DniCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	int updateByExample(Dni record, DniCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Dni record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_dni
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Dni record);

	List<BeanDni> listarPersonaXDni(Map<String, Object> params);
}