package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanEncuesta;
import pe.gob.ep.iclassq.entidad.BeanEncuestaPreguntas;
import pe.gob.ep.iclassq.negocio.bean.EncuestaPreguntas;
import pe.gob.ep.iclassq.negocio.bean.EncuestaPreguntasCriteria;

public interface EncuestaPreguntasDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	int countByExample(EncuestaPreguntasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	int deleteByExample(EncuestaPreguntasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	void insert(EncuestaPreguntas record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	void insertSelective(EncuestaPreguntas record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	List<EncuestaPreguntas> selectByExample(EncuestaPreguntasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	EncuestaPreguntas selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(EncuestaPreguntas record, EncuestaPreguntasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	int updateByExample(EncuestaPreguntas record, EncuestaPreguntasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(EncuestaPreguntas record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_preguntas
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(EncuestaPreguntas record);
	
	public List<BeanEncuestaPreguntas> getActiveQuestionsBySurvey(Map<String, Object> paramet);
}