package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanEncuesta;
import pe.gob.ep.iclassq.negocio.bean.Encuesta;
import pe.gob.ep.iclassq.negocio.bean.EncuestaCriteria;

public interface EncuestaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	int countByExample(EncuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	int deleteByExample(EncuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	void insert(Encuesta record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	void insertSelective(Encuesta record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	List<Encuesta> selectByExample(EncuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	Encuesta selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Encuesta record, EncuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	int updateByExample(Encuesta record, EncuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Encuesta record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Encuesta record);
	
	public List<BeanEncuesta> getEncuestasByRangeDate(Map<String, Object> paramet);
}