package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanReporteEncuesta;
import pe.gob.ep.iclassq.negocio.bean.EncuestaRespuesta;
import pe.gob.ep.iclassq.negocio.bean.EncuestaRespuestaCriteria;

public interface EncuestaRespuestaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	int countByExample(EncuestaRespuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	int deleteByExample(EncuestaRespuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	void insert(EncuestaRespuesta record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	void insertSelective(EncuestaRespuesta record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	List<EncuestaRespuesta> selectByExample(EncuestaRespuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(EncuestaRespuesta record, EncuestaRespuestaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_encuesta_respuesta
	 * @ibatorgenerated
	 */
	int updateByExample(EncuestaRespuesta record, EncuestaRespuestaCriteria example);
	
	public List<BeanReporteEncuesta> listarReporteEncuesta(Map<String, Object> paramet);
}