package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import pe.gob.ep.iclassq.negocio.bean.Evaluador;
import pe.gob.ep.iclassq.negocio.bean.EvaluadorCriteria;

public interface EvaluadorDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    int countByExample(EvaluadorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    int deleteByExample(EvaluadorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    void insert(Evaluador record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    void insertSelective(Evaluador record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    List<Evaluador> selectByExample(EvaluadorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    Evaluador selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Evaluador record, EvaluadorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    int updateByExample(Evaluador record, EvaluadorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Evaluador record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_evaluador
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Evaluador record);
}