package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;

import pe.gob.ep.iclassq.negocio.bean.Maestra;
import pe.gob.ep.iclassq.negocio.bean.MaestraCriteria;

public interface MaestraDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    int countByExample(MaestraCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    int deleteByExample(MaestraCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    void insert(Maestra record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    void insertSelective(Maestra record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    List<Maestra> selectByExample(MaestraCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    Maestra selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Maestra record, MaestraCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    int updateByExample(Maestra record, MaestraCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Maestra record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_maestra
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Maestra record);
}