package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;

import pe.gob.ep.iclassq.negocio.bean.MonitorCajas;
import pe.gob.ep.iclassq.negocio.bean.MonitorCajasCriteria;

public interface MonitorCajasDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	int countByExample(MonitorCajasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	int deleteByExample(MonitorCajasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	void insert(MonitorCajas record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	void insertSelective(MonitorCajas record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	List<MonitorCajas> selectByExample(MonitorCajasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	MonitorCajas selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(MonitorCajas record, MonitorCajasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	int updateByExample(MonitorCajas record, MonitorCajasCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(MonitorCajas record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_monitor_cajas
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(MonitorCajas record);
}