package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;

import pe.gob.ep.iclassq.negocio.bean.Monitor;
import pe.gob.ep.iclassq.negocio.bean.MonitorCriteria;

public interface MonitorDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    int countByExample(MonitorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    int deleteByExample(MonitorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    void insert(Monitor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    void insertSelective(Monitor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    List<Monitor> selectByExample(MonitorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    Monitor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Monitor record, MonitorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    int updateByExample(Monitor record, MonitorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Monitor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_monitor
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Monitor record);
}