package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import pe.gob.ep.iclassq.negocio.bean.Parametro;
import pe.gob.ep.iclassq.negocio.bean.ParametroCriteria;

public interface ParametroDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int countByExample(ParametroCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int deleteByExample(ParametroCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(String codigo);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	void insert(Parametro record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	void insertSelective(Parametro record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	List<Parametro> selectByExampleWithBLOBs(ParametroCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	List<Parametro> selectByExampleWithoutBLOBs(ParametroCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	Parametro selectByPrimaryKey(String codigo);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Parametro record, ParametroCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int updateByExampleWithBLOBs(Parametro record, ParametroCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int updateByExampleWithoutBLOBs(Parametro record, ParametroCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Parametro record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Parametro record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_parametro
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeyWithoutBLOBs(Parametro record);
}