package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;

import pe.gob.ep.iclassq.negocio.bean.Publicidad;
import pe.gob.ep.iclassq.negocio.bean.PublicidadCriteria;

public interface PublicidadDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	int countByExample(PublicidadCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	int deleteByExample(PublicidadCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	void insert(Publicidad record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	void insertSelective(Publicidad record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	List<Publicidad> selectByExample(PublicidadCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	Publicidad selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Publicidad record, PublicidadCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	int updateByExample(Publicidad record, PublicidadCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Publicidad record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_publicidad
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Publicidad record);
}