package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanGrupoProporcion;
import pe.gob.ep.iclassq.entidad.BeanGrupoXTiempo;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoGrupo;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoGrupoCriteria;

public interface RolEquipoGrupoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    int countByExample(RolEquipoGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    int deleteByExample(RolEquipoGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    void insert(RolEquipoGrupo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    void insertSelective(RolEquipoGrupo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    List<RolEquipoGrupo> selectByExample(RolEquipoGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    RolEquipoGrupo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(RolEquipoGrupo record, RolEquipoGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    int updateByExample(RolEquipoGrupo record, RolEquipoGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(RolEquipoGrupo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_grupo
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(RolEquipoGrupo record);
    
    public List<BeanGrupoProporcion> getGrupoByRolEquipo(Map<String, Object> params);
    
//    int getRegistrosActuales(Map<String, Object> params);
    
    int getCantidadRegistrosActuales(Map<String, Object> params);
    
    public List<BeanGrupoXTiempo> listarGruposByTiempo(Map<String, Object> params);
    int getCantidadRegistrosActualesBalanceo(Map<String, Object> params);
    
}