package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanRolEquipoSubGrupo;
import pe.gob.ep.iclassq.entidad.BeanSubGrupoProporcion;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoSubGrupo;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoSubGrupoCriteria;

public interface RolEquipoSubGrupoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    int countByExample(RolEquipoSubGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    int deleteByExample(RolEquipoSubGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    void insert(RolEquipoSubGrupo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    void insertSelective(RolEquipoSubGrupo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    List<RolEquipoSubGrupo> selectByExample(RolEquipoSubGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    RolEquipoSubGrupo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(RolEquipoSubGrupo record, RolEquipoSubGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    int updateByExample(RolEquipoSubGrupo record, RolEquipoSubGrupoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(RolEquipoSubGrupo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_rol_equipo_subgrupo
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(RolEquipoSubGrupo record);
    
    
    List<BeanRolEquipoSubGrupo> listarSubGrupoXRol(Map<String, Object> params);
    public List<BeanSubGrupoProporcion> getSubGrupoByRolEquipo(Map<String, Object> params);
    int getCantidadRegistrosActualesSG(Map<String, Object> params);

}