package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanGrupoProporcion;
import pe.gob.ep.iclassq.entidad.BeanSucursal;
import pe.gob.ep.iclassq.negocio.bean.RolEquipo;
import pe.gob.ep.iclassq.negocio.bean.RolEquipoCriteria;

public interface RolEquipoDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	int countByExample(RolEquipoCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	int deleteByExample(RolEquipoCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	void insert(RolEquipo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	void insertSelective(RolEquipo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	List<RolEquipo> selectByExample(RolEquipoCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	RolEquipo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(RolEquipo record, RolEquipoCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	int updateByExample(RolEquipo record, RolEquipoCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(RolEquipo record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_rol_equipo
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(RolEquipo record);   
    
}