package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanSucursal;
import pe.gob.ep.iclassq.negocio.bean.Sucursal;
import pe.gob.ep.iclassq.negocio.bean.SucursalCriteria;

public interface SucursalDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	int countByExample(SucursalCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	int deleteByExample(SucursalCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	void insert(Sucursal record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	void insertSelective(Sucursal record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	List<Sucursal> selectByExample(SucursalCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	Sucursal selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Sucursal record, SucursalCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	int updateByExample(Sucursal record, SucursalCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Sucursal record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_sucursal
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Sucursal record);
	public List<BeanSucursal> listarSucursalByEmpresa(Map<String, Object> params);
    public List<BeanSucursal> listarSucursalByUsuario(Map<String, Object> params);
    public List<BeanSucursal> listarSucursalByZona(Map<String, Object> params);
    void reiniciarServicio(Integer idSucursal);
}