package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanGrupo;
import pe.gob.ep.iclassq.entidad.BeanTablaGeneral;
import pe.gob.ep.iclassq.entidad.BeanTicketAreaproxTurno;
import pe.gob.ep.iclassq.negocio.bean.TablaGeneral;
import pe.gob.ep.iclassq.negocio.bean.TablaGeneralCriteria;
import pe.gob.ep.iclassq.negocio.bean.TablaGeneralKey;
import pe.gob.ep.iclassq.negocio.bean.Ventanilla;

public interface TablaGeneralDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	int countByExample(TablaGeneralCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	int deleteByExample(TablaGeneralCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(TablaGeneralKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	void insert(TablaGeneral record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	void insertSelective(TablaGeneral record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	List<TablaGeneral> selectByExample(TablaGeneralCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	TablaGeneral selectByPrimaryKey(TablaGeneralKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(TablaGeneral record, TablaGeneralCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	int updateByExample(TablaGeneral record, TablaGeneralCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(TablaGeneral record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_tabla_general
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(TablaGeneral record);

	/*****************************************************/
	public List<TablaGeneral> listarTipoAtencion(Map<String, Object> tabla);
}