package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanTicketAreaproxTurno;
import pe.gob.ep.iclassq.entidad.BeanTicketId;
import pe.gob.ep.iclassq.entidad.BeanTicketIdSonido;
import pe.gob.ep.iclassq.entidad.BeanTicketLlamado;
import pe.gob.ep.iclassq.entidad.BeanTicketManagement;
import pe.gob.ep.iclassq.entidad.BeanTicketPreview;
import pe.gob.ep.iclassq.entidad.BeanTicketSecuencial;
import pe.gob.ep.iclassq.entidad.BeanTicketXAlgoritmo;
import pe.gob.ep.iclassq.entidad.BeanTicketXArea;
import pe.gob.ep.iclassq.entidad.BeanTicketXGrupo;
import pe.gob.ep.iclassq.entidad.BeanTicketXMesArea;
import pe.gob.ep.iclassq.entidad.BeanTicketXMesGrupo;
import pe.gob.ep.iclassq.entidad.BeanTicketXMesUsuario;
import pe.gob.ep.iclassq.entidad.BeanTicketXReporte;
import pe.gob.ep.iclassq.entidad.BeanTicketXUsuario;
import pe.gob.ep.iclassq.entidad.BeanUsuarioEstadoGestion;
import pe.gob.ep.iclassq.negocio.bean.Ticket;
import pe.gob.ep.iclassq.negocio.bean.TicketCriteria;
import pe.gob.ep.iclassq.entidad.BeanTicketAreaproxTurno;

public interface TicketDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	int countByExample(TicketCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	int deleteByExample(TicketCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	void insert(Ticket record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	void insertSelective(Ticket record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	List<Ticket> selectByExample(TicketCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	Ticket selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Ticket record, TicketCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	int updateByExample(Ticket record, TicketCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Ticket record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ticket
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Ticket record);
	//    metodos adicionales
    public List<BeanTicketXArea> listarAtencionesXArea(Map<String, Object> params);
    public List<BeanTicketXAlgoritmo> listarAtencionesXAlgoritmo(Map<String, Object> params);
    public List<BeanTicketXAlgoritmo> listaratencionestotalxalgoritmo(Map<String, Object> params);
    
    public List<BeanTicketXUsuario> listarAtencionesXUsuario(Map<String, Object> params);
    public List<BeanTicketXGrupo> listarAtencionesXGrupo(Map<String, Object> params);
    public List<BeanTicketXMesUsuario> listarAtencionesXMesUsuario(Map<String, Object> params);

    public List<BeanTicketXMesGrupo> listarAtencionesXMesGrupo(Map<String, Object> params);
    public List<BeanTicketXMesArea> listarAtencionesXMesArea(Map<String, Object> params);
    
    public List<BeanTicketXMesArea> listarAtencionesComparativo(Map<String, Object> params);
    
    public Ticket listarTicketSecuencial(Map<String, Object> params);
    
    public int getCantidadTicketEst30_Alg3(Map<String, Object> params);
    public int getMaximaSecuencia31_Alg3(Map<String, Object> params);
    public int getCantidadTicketGrupoEst31_Alg3(Map<String, Object> params);
    public BeanTicketId getNextTicketSubGrupoEst30_Alg3(Map<String, Object> params);
    public BeanTicketId getNextTicketGrupoEst31_Alg3(Map<String, Object> params);
    public BeanTicketId getNextTicketGrupo_Alg_1_2(Map<String, Object> params);
    public BeanTicketId getNextTicketEst0_Alg3(Map<String, Object> params);
    public BeanTicketId getNextTicketGrupo_Alg3(Map<String, Object> params);
    public BeanTicketId getNextTicketSubGrupo_Alg_1_2(Map<String, Object> params);
    public BeanTicketId getNextTicketSubGrupo_Alg_1_2_VS(Map<String, Object> params);
    public BeanTicketId getNextTicketSubGrupo_Alg_1_2_VA(Map<String, Object> params);
    public BeanTicketId getNextTicketByGrupoAlg1(Map<String, Object> params);
    public BeanTicketId getNextTicketByGrupoAlg2(Map<String, Object> params);
    
    public int getCantidadTicketEspera(Map<String, Object> params);
    public int getCantidadTicketEsperaAllGrupo(Map<String, Object> params);   
    public int getCantidadTicketEsperaByGrupo(Map<String, Object> params);   
    List<BeanTicketLlamado> getListTicketCallVoz(Map<String, Object> params);
    
    public List<BeanTicketXReporte> getResultConsultaTicket(Map<String, Object> params);
    public List<BeanTicketXReporte> getResultGestionTicket(Map<String, Object> params);
    public List<BeanTicketXArea> GestionTicket_1_Apellido(Map<String, Object> params);
    public List<BeanTicketXArea> GestionTicket_1_Codigo(Map<String, Object> params);    
    
    public BeanTicketIdSonido sonidoTimbreTicket(Map<String, Object> paramet) ;
  	public List<BeanTicketXArea> listarAtencionesXDni(Map<String, Object> params) ;
  	public List<BeanTicketAreaproxTurno> getProximosTurnosArea(Map<String, Object> params);
  	
  	//actualizacion de eventos desde JOB
  	public void actulizarMonitorcajas();

	public int getCantidadTicketEsperaAllSubGrupo(Map<String, Object> paramet);
	public int getCantidadTicketEsperaAllVentAdmin(Map<String, Object> paramet);
	
	
	// MATIAS: traer Nombre del grupo segun id subgrupo
	public List<BeanTicketXGrupo> getNombreGrupoByIdSucursal(Map<String, Object> params);
	
	public List<BeanTicketPreview> getDataTicketsPreview(Map<String, Object> params);
	
	public Ticket getOldestWaitingTicket(Map<String,Object> params);
    public int assignTicketToUser(Map<String, Object> params);
    public int contarTicketAtendidosDia(Map<String, Object> params);
    public List<BeanTicketManagement> getReportTicketManagement(Map<String, Object> paramet);
}
