package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import pe.gob.ep.iclassq.negocio.bean.TicketDerivacion;
import pe.gob.ep.iclassq.negocio.bean.TicketDerivacionCriteria;

public interface TicketDerivacionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    int countByExample(TicketDerivacionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    int deleteByExample(TicketDerivacionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    void insert(TicketDerivacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    void insertSelective(TicketDerivacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    List<TicketDerivacion> selectByExample(TicketDerivacionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    TicketDerivacion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(TicketDerivacion record, TicketDerivacionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    int updateByExample(TicketDerivacion record, TicketDerivacionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(TicketDerivacion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_ticket_derivacion
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(TicketDerivacion record);
}