package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import pe.gob.ep.iclassq.negocio.bean.TipoDocumento;
import pe.gob.ep.iclassq.negocio.bean.TipoDocumentoCriteria;

public interface TipoDocumentoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    int countByExample(TipoDocumentoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    int deleteByExample(TipoDocumentoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    void insert(TipoDocumento record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    void insertSelective(TipoDocumento record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    List<TipoDocumento> selectByExample(TipoDocumentoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    TipoDocumento selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(TipoDocumento record, TipoDocumentoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    int updateByExample(TipoDocumento record, TipoDocumentoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(TipoDocumento record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cat_tipo_documento
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(TipoDocumento record);
}