package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanUsuarioAusencia;
import pe.gob.ep.iclassq.negocio.bean.UsuarioAusencia;
import pe.gob.ep.iclassq.negocio.bean.UsuarioAusenciaCriteria;

public interface UsuarioAusenciaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    int countByExample(UsuarioAusenciaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    int deleteByExample(UsuarioAusenciaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    void insert(UsuarioAusencia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    void insertSelective(UsuarioAusencia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    List<UsuarioAusencia> selectByExample(UsuarioAusenciaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    UsuarioAusencia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(UsuarioAusencia record, UsuarioAusenciaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    int updateByExample(UsuarioAusencia record, UsuarioAusenciaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(UsuarioAusencia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_usuario_ausencia
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(UsuarioAusencia record);
    
    List<BeanUsuarioAusencia> getDataUserAbsence(Map<String, Object> params);
}