package pe.gob.ep.iclassq.negocio.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanTicketXArea;
import pe.gob.ep.iclassq.negocio.bean.Ventanilla;
import pe.gob.ep.iclassq.negocio.bean.VentanillaCriteria;



public interface VentanillaDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	int countByExample(VentanillaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	int deleteByExample(VentanillaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	void insert(Ventanilla record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	void insertSelective(Ventanilla record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	List<Ventanilla> selectByExample(VentanillaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	Ventanilla selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Ventanilla record, VentanillaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	int updateByExample(Ventanilla record, VentanillaCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Ventanilla record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table tbl_ventanilla
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Ventanilla record);

	/** query adicionales**/
	public List<Ventanilla> listarventanillasxparametroTipoDeriva(Map<String, Object> parametro);
		

}