package pe.gob.ep.iclassq.seguridad.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.iclassq.seguridad.bean.ReinicioServicio;
import pe.gob.ep.iclassq.seguridad.bean.ReinicioServicioCriteria;
import pe.gob.ep.iclassq.seguridad.dao.ReinicioServicioDAO;

public class ReinicioServicioDAOImpl extends SqlMapClientDaoSupport implements ReinicioServicioDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public ReinicioServicioDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public int countByExample(ReinicioServicioCriteria example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("aud_reinicio_servicio.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public int deleteByExample(ReinicioServicioCriteria example) {
		int rows = getSqlMapClientTemplate().delete("aud_reinicio_servicio.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		ReinicioServicio key = new ReinicioServicio();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("aud_reinicio_servicio.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public void insert(ReinicioServicio record) {
		getSqlMapClientTemplate().insert("aud_reinicio_servicio.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public void insertSelective(ReinicioServicio record) {
		getSqlMapClientTemplate().insert("aud_reinicio_servicio.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<ReinicioServicio> selectByExample(ReinicioServicioCriteria example) {
		List<ReinicioServicio> list = getSqlMapClientTemplate()
				.queryForList("aud_reinicio_servicio.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public ReinicioServicio selectByPrimaryKey(Integer id) {
		ReinicioServicio key = new ReinicioServicio();
		key.setId(id);
		ReinicioServicio record = (ReinicioServicio) getSqlMapClientTemplate()
				.queryForObject("aud_reinicio_servicio.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public int updateByExampleSelective(ReinicioServicio record, ReinicioServicioCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("aud_reinicio_servicio.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public int updateByExample(ReinicioServicio record, ReinicioServicioCriteria example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("aud_reinicio_servicio.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKeySelective(ReinicioServicio record) {
		int rows = getSqlMapClientTemplate().update("aud_reinicio_servicio.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	public int updateByPrimaryKey(ReinicioServicio record) {
		int rows = getSqlMapClientTemplate().update("aud_reinicio_servicio.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	private static class UpdateByExampleParms extends ReinicioServicioCriteria {
		private Object record;

		public UpdateByExampleParms(Object record, ReinicioServicioCriteria example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}