package pe.gob.ep.iclassq.seguridad.dao;

import java.util.List;
import pe.gob.ep.iclassq.seguridad.bean.ReinicioServicio;
import pe.gob.ep.iclassq.seguridad.bean.ReinicioServicioCriteria;

public interface ReinicioServicioDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	int countByExample(ReinicioServicioCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	int deleteByExample(ReinicioServicioCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	void insert(ReinicioServicio record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	void insertSelective(ReinicioServicio record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	List<ReinicioServicio> selectByExample(ReinicioServicioCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	ReinicioServicio selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(ReinicioServicio record, ReinicioServicioCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	int updateByExample(ReinicioServicio record, ReinicioServicioCriteria example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(ReinicioServicio record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table aud_reinicio_servicio
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(ReinicioServicio record);
}