package pe.gob.ep.iclassq.seguridad.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.iclassq.entidad.BeanUsuarioEstadoGestion;
import pe.gob.ep.iclassq.entidad.BeanUsuariosPermiso;
import pe.gob.ep.iclassq.seguridad.bean.Usuario;
import pe.gob.ep.iclassq.seguridad.bean.UsuarioCriteria;

public interface UsuarioDAO {
    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	int countByExample(UsuarioCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	int deleteByExample(UsuarioCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	int deleteByPrimaryKey(Integer iUsuarioId);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	void insert(Usuario record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	void insertSelective(Usuario record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	List<Usuario> selectByExample(UsuarioCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	Usuario selectByPrimaryKey(Integer iUsuarioId);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	int updateByExampleSelective(Usuario record, UsuarioCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	int updateByExample(Usuario record, UsuarioCriteria example);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	int updateByPrimaryKeySelective(Usuario record);
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table ctrl_seg_usuario
	 * @ibatorgenerated
	 */
	int updateByPrimaryKey(Usuario record);
	public List<Map<String, Object>> listarUsuariosTipoKiosko(Map<String, Object> params);
	public List<BeanUsuariosPermiso> listAllUsersPermissions(Map<String, Object> paramet);
	public List<BeanUsuarioEstadoGestion> getReportUserManagement(Map<String, Object> paramet);
}